### ISSUE TITLE
Changing source files are not triggering library rebuilds

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/dune#10365]
## Behavior

I have a minimal reproduction project at https://gitlab.com/diskuv/samples/my-dune-repro

If you run `opam exec -- make actual-failure` on the first commit (`git reset --hard fails`) it will fail.

If you run `opam exec -- make actual-failure` on the second commit (`git reset --hard succeeds`) it will succeed.

(Any opam switch should work as long as it has Dune and ocamlc.)

The change between the commits is: https://gitlab.com/diskuv/samples/my-dune-repro/-/commit/4fd759243d8a4bb8cab8bf3faaee66b54832b034. Red is `fails` and green is `succeeds`.

## Context

I am using Dune as the primary build tool for my DkCoder tool (confer https://discuss.ocaml.org/t/ann-dkcoder-0-1-0/14327). From a technical simplified perspective it generates a build system from a script:
1. Analyze a user-specified OCaml `.ml` "main" script from the project tree for module dependencies with `codept`
2. Create a `dune-project` and a tree of `dune` build scripts for those dependencies.
3. Run the generated Dune project.

You'll see those steps mimicked in the `Makefile`. The `do-50` target mimics the user building `src/DkHelloScript_Std/N0xxLanguage/Example050.ml` while `do-51`mimics `src/DkHelloScript_Std/N0xxLanguage/Example051.ml`.

I know I'm doing something unusual and may be stressing Dune to its maximum capabilities, but I think I shouldn't have to clean the build directory simply because the `dune-project` and/or `dune` files change. Even though the user may change their "main" script (ex. `Example051.ml`), if most of the main script's dependencies (ex. `Example050.ml` depends on `Example050.ml`) stay constant there is no reason to rebuild those dependencies.

(Yes, I could simply not use Dune since I have full control over dependencies and build file generation. But I very much would prefer to use Dune as the primary build tool for DkCoder. It gives a straightforward path for intermediate OCaml users to take the resulting Dune project tree and build their own native executables, publish to Opam, etc. And I don't want to re-invent dune watch mode and the merlin-lib integration)

## Mitigation

In my real environment, running the build first with `OCAMLLIB` unset ... and then setting `OCAMLLIB=$(ocamlc -config-var standard_library)` in the second build ... is enough to get the Dune generated builds to pass. It is ugly and the initial error is visible to the user, but it kinda works. But I couldn't replicate the `OCAMLLIB` trick in my minimal reproduction project.

So, I think that something is not being cached right, and my mitigation trick won't always work.

## Specifications

- Version of `dune` (output of `dune --version`): 3.14.2
- Version of `ocaml` (output of `ocamlc --version`): 4.14.2
- Operating system (distribution and version): macOS arm64

**Comment by emillon** [comment]
I had a look at this. It's a bit difficult to understand what's going on because it's generated code, but I think that the crux of the issue is that there's a mix of libraries generated by dune, and some code compiled by manually invoking `ocamlc` from dune rules. So it's likely that there are missing dependencies, for example when linking an executable, the transitive closure of all libraries is a dependency, not just the ones that appear on the command line.

Fixing this is going to be difficult, but I found a workaround that might be good enough:

```diff
-     "echo \"let enter _ = ignore @@ $RANDOM\""
+     "echo \"let enter _ = ignore @@ Sys.opaque_identity $RANDOM\""
```

For some reason, this makes the project rebuild correctly. I assume that's because the value of `RANDOM` is thrown away in an intermediate state (like a cmo or cma file) and dune is able to determine that it's not enough to trigger the rest of the compilation (in other words, the change is not significant enough). But I haven't specifically found where it happens. (and adding `Sys.opaque_identity` prevents this kind of optimisation from firing)

**Comment by jonahbeckford** [comment]
> So it's likely that there are missing dependencies, for example when linking an executable, the transitive closure of all libraries is a dependency, not just the ones that appear on the command line.

Ah ... that makes sense.

> I found a workaround that might be good enough:

I've ended up with a design workaround that completely avoids the `ocamlc` invocation at the core of this problem. I'm not sure how long I can avoid it, but for the foreseeable future I won't need the `Sys.opaque_identity` workaround.

I'm fine with closing the ticket until both a) I need to start using the `Sys.opaque_identity` workaround and b) the `Sys.opaque_identity` workaround breaks.

**Comment by emillon** [comment]
Great, let's do this!
