### ISSUE TITLE
Warning 9 included in standard

### ISSUE THREAD

**Issue by mmottl** [ocaml/dune#1046]
I assume the developers have thought carefully about the standard warnings that will be used for building `dune` projects during development.  Right now this includes warning 9 (missing fields in a record pattern).  Is this a deliberately agreed upon standard chosen by the `dune` developers (Jane Street)?

To me this flag seems a little excessive as a default and warns on a significant number of occasions in my code.  E.g. I frequently write:

```ocaml
  let { foo } as bar = f x in
```

Being able to bind a field while also binding the result of an expression is quite convenient.  Having to add `; _` for all these patterns with warning 9 can be quite annoying.  The vast majority of record pattern matches do not seem to benefit, because almost all seem to need `; _` anyway.

A paranoid developer can always use warning attributes for those exceedingly rare code sections where not handling added fields could be potentially dangerous.  I don't think I have ever run into a bug that was the result of not matching added record fields.

Would it be possible to relax this standard by removing warning 9?

**Comment by yminsky** [comment]
FWIW, within Jane Street, we strongly prefer including warning 9, because it makes exhaustive pattern matches on records easy to access, and we've found them to be a powerful tool. It's not the case for us that the vast majority of record matches use `_ ;`, perhaps because we tend to prefer dotted record field access for cases where exhaustion is not necessary.

We've found that record exhaustion checks are a powerful tool for catching bugs in evolving code, and making that a harder tool to reach for seems to me like a mistake. I think Dune's defaults here are just right.

**Comment by yminsky** [comment]
Cute!

That said, it's not so much that I crave the warning, it's that I want to be able to look at a record pattern and know that I haven't missed any fields...

**Comment by mmottl** [comment]
Fair enough, though one might argue that warning 4 should then be turned on by default, too.  I'd bet that mishandling new cases in a pattern match is a more likely source of error than not handling additional record fields.  Of course, variants and records are not quite comparable in that respect, because it is not that uncommon to see types with hundreds of variants whereas a record will virtually never become that big.

Note, too, that dotted access is often a bad idea with mutable record fields.  I always want to be sure about the state associated with a variable and hence explicitly bind mutable fields.

I wonder whether it might be a good idea to split up warning 9 to distinguish between `let / fun`-bindings and case matches (`match with / function`).  I sort of agree that exhaustiveness is desirable even with record fields, but let-bindings are typically used to just grab a couple of known fields regardless of what else is there.  Case matching will usually require more careful thinking about the contents of a record.

**Comment by yminsky** [comment]
I don't think 4 is analogous. Turning on 4 would be like warning when you decide to use `; _` in a record match. The analog instead would be to not warn at an incomplete pattern match without an explicit underscore, which is I believe warning 8, partial match. And 8 is on by default in our internal setup, and in Dune.

I worry that splitting 9 into two warnings is not a win here. My expectation for exhaustion is the same independent of the context (let, fun or match), and teaching users that match semantics are different in different contexts seems to me to make the language more complicated, and I don't really see the principle behind treating these contexts differently.

**Comment by mjambon** [comment]
I think it may simplify future discussions to proactively tell the following: Effectively `fun {x} -> x` is no longer supported, please use `fun p -> p.x` instead.

**Comment by mjambon** [comment]
Sure. I prefer "not recommended" over "not supported". I wouldn't recommend users to tweak the defaults, though, because most users don't want that and it can sound dismissive.

After some personal reflection (FWIW), when requiring people to change a behavior in some way, I might communicate the following:
1. acknowledge the benefits of the old way of doing things
2. give an example of the more important problem the change will solve
3. give a recipe for migrating

**Comment by mmottl** [comment]
To me the mentioned warnings boil down to what should happen when datatypes are extended.  Being strict with sum types would mean to disallow catch-all patterns, because that's the only way to avoid matching new cases silently.  Being strict with records would require explicit relaxation of the pattern to indicate that it is indeed safe to only look at certain fields.  It's in this light that I saw these two warnings as analogues.

When trading off safety vs convenience, it's usually a good idea to consider the likelihood of failure.  If it is small as with record patterns, require an annotation for strictness.  If it is high, require an annotation for relaxation.  Maybe a more natural approach for records would be a pattern like `{ foo; ! }` to indicate that it would be a failure for this record to have any more fields than specified.  The vast majority of code using record patterns works fine with extra fields.  This is pretty much the opposite of code using sum type patterns, which typically fails with extensions, in many if not most cases even with catch-all patterns.

**Comment by mmottl** [comment]
Change not likely going to happen.  It's easy enough to override defaults in the project-wide `dune` file.

**Comment by diml** [comment]
BTW, without considering warning 9 specifically, I have been thinking of a simple mechanism to share such defaults between projects so that you could just write: `(using myconf 1.0)`. For instance we might have `(using janestreet 1.0)`, `(using facebook 1.0)`, ... all with their own defaults written in the corresponding projects.

For the hardcoded defaults in dune, it's hard to change them without introducing a breaking change. I'm thinking that when we prepare the 2.0 version of the language, we'll re-evaluate the defaults at this point and re-adjust them.
