### ISSUE TITLE
Better documentation for install stanza

### ISSUE THREAD

**Issue by wieczyk** [ocaml/dune#1123]
I cannot understand documentation, it should contain more examples of stanzas.

My situation: I am getting an error:

```
wieczyk@tortilla:~/Repozytoria/Uczelnia/xic$ make
dune build
File "source/xic/dune", line 1, characters 0-115:
Error: I can't determine automatically which package this (install ...) stanza is for. I have the choice between these ones:
- xic (because of xic.opam)
- xif (because of xif.opam)
You need to add a (package ...) field in this (install ...) stanza
Makefile:6: recipe for target 'compile' failed
make: *** [compile] Error 1
```
...where I can see suggestion that I should add `package` field in the `install` stanza.

But I have the field in my `dune` file.

```
wieczyk@tortilla:~/Repozytoria/Uczelnia/xic$ cat source/xic/dune 
(executable 
    (name xic)
    (public_name xic)
    (install 
        (section bin)
        (package xic)
    )
)
```

Maybe I cannot understand documentation, but it should work ;/

**Comment by emillon** [comment]
Hi,

Thanks for the bug report.

I agree that the error message is not clear. What happens here is that you define several opam packages (presumably one for the library and one for the executable), and dune does not know how to do the mapping. In that case, an explicit `(package)` is required.

The problem is that the error message refers to a generated `(install)` stanza that is a low level detail. Dune is able to determine the correct section by itself, so you don't need to have an explicit `(install)` stanza. But a `(package)` option in `(executable)` directly will be used to determine the package. In other words, the following works:

    (executable
      (name xic)
      (public_name xic)
      (package xic)
    )

In addition, if you're using at least dune 1.1.0, you can remove `(name)` and it will use the `(public_name)` automatically.

I'll try to make the error message a bit more precise. Let me know if the above solution works. Thanks!

**Comment by wieczyk** [comment]
Works when added `package` to `executable`. Thank you.

Could you explain why `package` is not needed for `library`?

**Comment by emillon** [comment]
For libraries, the situation is a bit different: the `public_name` is directly the name of the opam package, so there's no ambiguity. The error message now displays the stanza that's causing the ambiguity.
