### ISSUE TITLE
Can't find the syntax to use %{ext_obj} in rule's targets?

### ISSUE THREAD

**Issue by ttamttam** [ocaml/dune#1189]
If I do something like

```(rule
         (targets something%{ext_obj})
     ....)
```

I get: 
```
dune build something.o
File "dune", line 2, characters 15-29:
Error: Atom or quoted string expected
```

while the following is working:

```(rule
         (targets something.o)
     ....)
```

I could not find th right syntax for this?

**Comment by rgrinberg** [comment]
We just didn't add support for this yet. If you'd like to work on this, we can give you some pointers on how to add this feature.

**Comment by ttamttam** [comment]
@emillon I'm not sure to understand?

@rgrinberg I think I could give a try on it if you can give me some pointers.

**Comment by rgrinberg** [comment]
# Preliminaries

Dune holds all stanza definitions in https://github.com/ocaml/dune/blob/master/src/dune_file.mli#L1

This is where we hold the definition for user defined rules and the `targets` field (see the `Targets` sub module).

Anything that accepts `%{var}` substitutions is called a template and is represented as `String_with_vars.t`. Notice how the dependency field (`Dep_conf.t`) accepts such templates as arguments.

# Action Plan

The target's type constructors needs to be modified to accept templates as arguments rather than strings. Once this is done, we should change the rule generation to expand the templates before generating the targets. Expansion is done through the family of functions defined in the super context: https://github.com/ocaml/dune/blob/master/src/super_context.mli#L83

One thing to note is that we can only expand "static" variables here. Dune must know the entire list of targets up front, that is, before the rules have been generated. Luckily for us, `%{ext_obj}` is one such static variable that comes from the context (`Context.t`).

If you have any questions, feel free to ask.

**Comment by ttamttam** [comment]
I had a look. More for learning than because I really need the functionality. I'll come back in some days (weeks) with some questions…

**Comment by rgrinberg** [comment]
nojb fixed this

**Comment by ttamttam** [comment]
Thanks to @nojb!
