### ISSUE TITLE
[RFC] Low-overhead sandboxing

### ISSUE THREAD

**Issue by diml** [ocaml/dune#1262]
To ensure correctness of builds, it is important that commands are properly specified and in particular that the build system knows exactly all the files a command may read and all the files it will write. Dune already has support for "sandoxing" a command: it can execute it in a directory where only the declared dependencies are visible. While this works, it requires one FS operation such as a symlink per dependency, which can become costly for commands that read a lot of files, such as the compiler.

One idea would be to write a `LD_PRELOAD` library that would override a few system calls such as `open`, `stat`, ... to return `ENOENT` when trying to access a file that wasn't declared as a dependency. Similarly the files written by the command should be written in a temporary directory and would be moved by the build system after the command has terminated.

**Comment by diml** [comment]
Another application of this would be narrowing dependencies: we could record what observations the command does and only consider these for incremental builds. That would yield faster rebuilds.

**Comment by Khady** [comment]
If this is not optional, it would break multiple things we are doing with dune. Including code generation and interactions with rust.

**Comment by avsm** [comment]
The LD_PRELOAD solution is very very brittle and non-portable. We could adapt the opam sandboxing scripts which work on osx as well as linux.

It may be worth making this just a command line flag rather than a dune rule, since it doesnt change the semantics of the build (in theory) and needs to be disabled dynamically in some situations (e.g. in Docker if we use namespaces for sandboxing as opam2 does)

**Comment by diml** [comment]
This kind of sandboxing won't work. AFAIK it is not possible to hide only parts of a directory this way. The overhead is likely to be way too high as well.

Where the LD_PRELOAD solution doesn't work, we will simply not sandbox. It is not necessary to sandbox builds, however it is a really good way to debug broken builds. In particular, it is extremely easy for rules authors to miss dependencies. Just specifying what the OCaml compiler does is an extremely tedious task for instance. The more we increase sharing and the more errors due to wrongly specified rules will propagate, so it is important to have good tools to find them as soon as possible.

BTW, even with a command line flag we still need a way to opt-out sandboxing for particular rules as some rules are just impossible to specify properly. For such rules, we simply can't share the results too much as we don't really know what they depend on.

**Comment by avsm** [comment]
> This kind of sandboxing won't work. AFAIK it is not possible to hide only parts of a directory this way. The overhead is likely to be way too high as well.

I think you can do very fine-grained sandboxing on osx, just by generating some sexpressions and piping it through sandbox-exec.  For example, look at [this sample profile](https://github.com/hellais/Buckle-Up/blob/master/profiles/template.sb) that has both regex and literal file specifications for read and write.  This seems to be the simplest and most low overhead way of testing rules out, since you just need to run `dune build` on a mac (a pretty common developer platform).

Linux, as usual, seems significantly more complex in terms of fine-grained sandboxing specification...

**Comment by diml** [comment]
Thanks. I'd like to have a good solution for Linux as well. Thinking about this again, the following would be simpler and would work as well as what initially proposed: a way to record all the files accessed by a process. Dune could check afterwards that the command didn't do anything it wasn't supposed to.

**Comment by avsm** [comment]
eBPF in Linux should be to provide that information via the syscall tracing subsystem -- that'll be faster and more robust than LD_PRELOAD I think

**Comment by rgrinberg** [comment]
Sandboxing has been added to dune. We can make separate issues for problems/improvements of the current implementation
