### ISSUE TITLE
Allow multiple targets from a set of .re source files

### ISSUE THREAD

**Issue by jaredly** [ocaml/dune#142]
I've got a library that has inline tests (implemented as `[@@attributes]` that are picked up my a ppx).
I'd like to be able to do something like this:
```
(library (
  (name blah)
  (preprocess (pps (my-test-ppx --strip)))
))
(executable (
  (name blah-test)
  (preprocess (pps (my-test-ppx)))
))
```

But I get the error
```
Multiple rules generated for _build/default/blah.ml
```

Is this something that's possible to do with jbuilder, or that you're open to supporting?

(I can imagine other scenarios where I'd want to e.g. generate a debug vs release version of an executable, etc.)

**Comment by diml** [comment]
You need to partition the set of modules by adding `(modules ...)` fields to your `library` and `executable` stanzas. The error reported by jbuilder could definitely be improved

**Comment by jaredly** [comment]
ohhh it appears that the problem is in the `reason` stuff.

If I have
```
example/
  jbuild
  hello.ml
```
and
```
(executable ((name hello)))
(library ((name hello_lib)))
```
then everything is fine.
If, however, I have `hello.re` instead of `hello.ml`, then if breaks, with
```
❯❯❯ jbuilder build example/hello.exe
Multiple rules generated for _build/default/example/hello.re.ml
```

**Comment by diml** [comment]
Sorry, I misunderstood your problem. Well the reason it works in the second case is a bit by chance really and it might not always work. Especially it might break when we switch to proper namespaces, because the filenames for artifacts will no longer be mangled. We need to implement a stronger check in jbuilder to avoid future surprises.

To support this scheme properly in a future proof way we'd need to save the artifacts in separate directories for different libraries or executables, which is starting to become complicated.

We have a similar setup for inline tests in Jane Street code, what we do is try to put the tests as much as possible in a separate directory and for the few tests that remain because they access non-exposed functions, we just accept that they end up in the final executable.

Alternatively, what you could do is write rules to copy the files to a different directory and setup the test executable there.

The ideal solution to this problem would be to have a way to generate several object files from a single ml file.

**Comment by rgrinberg** [comment]
@diml what do you think of lifting the restriction of sharing sources between executable stanzas? I can understand why we have the restriction in place for libraries as it's nice to know that we only have a single unit for sharing code (libraries), but for executables the limitation doesn't seem to buy much and also restricts things such as instantiating the same exe with 2 different virtual library implementations.

**Comment by diml** [comment]
That doesn't seem optimal to me:

- we don't know what settings merlin should use for the file
- when using menhir, we don't know what stanza to attach modules to
- the file will be compiled several times instead of 1

The situation can certainly be improved for inline tests, but I don't think manually duplicating the stanzas is the right way to go about it.

Regarding selecting different virtual library implementations, this can be achieved by splitting the code between a library and an executable. Additionally, we could add a dedicated stanza for just linking an executable, where the user would specify things such as libraries + a main function, rather than a main module.
