### ISSUE TITLE
[feature request] Please add support for libraries setting `-rectypes`

### ISSUE THREAD

**Issue by ejgallego** [ocaml/dune#1420]
Imagine library `foo`, compiled with `-rectypes`, and library `bar` that depends on `foo`. Compilation of library `bar` will fail unless we add `(flags -rectypes)` to its stanza.

In view of this problem it was suggested that `-rectypes` should not be used, however this turns out to be problematic in production code. Instead, as suggested by @diml, we could add a `(rectypes)` field to the stanza, so that depending libraries don't need to understand this the low-level implementation details of `foo`.

**Comment by rgrinberg** [comment]
Was the alternative to drop `-rectypes` in coq considered? As was mentioned before, it should always be possible to workaround having this feature.

**Comment by ejgallego** [comment]
It was considered and we were not against it but actually doing it seems not so straightforward, it would change the core API too, and maybe in ways that are not desired.

TTBOMK no developer is working on it.

**Comment by rgrinberg** [comment]
It seems like a bit of a serious limitation as you basically can't use any 3rd party OCaml library as is. So it seems like fixing this in dune is just a temporary band-aid. In any case, if it's too hard for coq to switch away from `-rectypes` in the short/medium term, we're willing to implement this band-aid.

**Comment by ejgallego** [comment]
I think we can use 3rd party libraries fine, the problem is more in that 3rd party development cannot link to Coq without also using `-rectypes` themselves.

Regarding the difficulty I forgot the details, (cc: @ppedrot) but if indeed we are talking about modification of the core kernel Term type, this will take a while.

I dunno what should Dune do. If you indeed think that the flag should be indeed fully deprecated in OCaml then IMHO no point on adding this just for Coq [we can live fine just requiring users to tweak the flag]; otherwise, indeed it may be useful.

**Comment by ppedrot** [comment]
FTR, I don't know how OCaml really fares on that topic, but AFAIU the term structure is not the problematic one.

First, because it uses rectypes under an abstract API, which OCaml seems to allow locally, i.e. one can pass the `-rectypes` option only to this `.ml` file, this flag having no effect on the runtime, only on the typing algorithm. Second, because in the worst case, thanks to the opacity, we can emulate the current behaviour with a dummy one-constructor inductive implementing the required indirection and compiling it away with `unbox` annotations. The latter trick actually justifies the first one, i.e. the fact that `-rectypes` can be applied locally to an abstracted type.

The real issue in our code base is the native compilation scheme that morally targets an untyped functional language, but uses OCaml verbatim as an intermediate representation. This forces Coq to hack around the typing system, inserting a lot of unsafe casts all around. In particular, the translation assumes that the un(i)typed calculus type `t` satisfies `t ≡ t -> t` in order to compile `[t u]` as `[t] [u]`. I have pieces of patches starting to fix this, but it is far from being that easy, and the patches are currently broken. I can invest a little more time if needed, but in the end, the better solution would be to target some other intermediate language in the style of [Malfunction](https://github.com/stedolan/malfunction).

**Comment by rgrinberg** [comment]
Given that coq is moving away from rectypes, I'm going to politely refuse this feature request.
