### ISSUE TITLE
compilation error on mac with dune-1.5.1

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#1550]
Hello,

When trying to compile the head of orandforest on a mac, I get this:
```
$ dune build @install
      ocamlc src/.orandforest.objs/orandforest.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /Users/berenger/.opam/4.06.1/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -w -49 -nopervasives -nostdlib -g -bin-annot -I src/.orandforest.objs -I src/.orandforest.objs/.private -no-alias-deps -opaque -o src/.orandforest.objs/orandforest.cmo -c -impl src/orandforest.ml-gen)
File "src/orandforest.ml-gen", line 1:
Error: Could not find the .cmi file for interface src/orandforest.mli.
```

Sources are here:
https://github.com/tobast/ORandForest

I don't get this error on Linux.

You can easily try on a mac using this command:
```
opam pin orandforest --dev-repo
```

Thanks for any help,
Francois.

**Comment by UnixJunkie** [comment]
I use opam version 2.0.1. Not sure if that matters though.

**Comment by diml** [comment]
Does this still happen if you rename the files `orandforest.ml{,i}` or the library `ORandForest`?

**Comment by UnixJunkie** [comment]
If I rename all files to be lower case, problem solved.
However, there is no need to do this on Linux.

**Comment by UnixJunkie** [comment]
If I remember correctly, macs have a case insensitive filesystem by default.

**Comment by UnixJunkie** [comment]
Funny, even after I renamed the files, git status doesn't see any change.
So, this is definitely mac filesystem related.

**Comment by UnixJunkie** [comment]
Full dune build log in the failing case:
https://gist.github.com/UnixJunkie/b121ab146b3a60990fa45c890946a5c5

**Comment by diml** [comment]
That's what I expected. Dune relies on the output of `readdir`, so it will always be sensible to the case. It would be quite complicated to mimic the behaviour of case-sensitive filesystems and it's likely that the compiler itself will do the same as Dune at some point, so it doesn't seem worth changing anything in Dune.

Possibly we could try to detect this case and provide a good error message, although that seems quite complicated to implement.

**Comment by UnixJunkie** [comment]
I can rename the files and do a major release, so thanks for the workaround, but that looks like a bug to me.

**Comment by dra27** [comment]
@UnixJunkie - for the git renaming, you either need to use `git mv -f` or you need to temporarily change `core.ignorecase`.

This I think is related to https://github.com/ocaml/ocaml/pull/1696. @diml - could this be solved by sandboxing the compilation of `orandforest.ml-gen` - the issue is just that `ORandForest.mli` is in the same directory when it's built.

**Comment by diml** [comment]
Indeed and ocaml/ocaml#2041 should have the same effect as well. Sandboxing might not have the desired effect, what we really want here is for Dune to realise that ORandForest.mli is the library interface module because it matches the name of the library. The only way to do that is to detect that we are using a on case insensitive FS. That seems a bit complicated, especially if this is not going to be supported by the next version of OCaml.

**Comment by rgrinberg** [comment]
It seeems that the conclusion here is that there's not much that can be done by dune.
