### ISSUE TITLE
support linking against cmo/cmi without source

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#1665]
There have been a few requests for building against cmo/cmi files without having the corresponding source code.  This is primarily for teaching purposes. Two threads on discuss here with more background here:

- https://discuss.ocaml.org/t/dune-link-against-cmo-cmi-without-source/2488
- https://discuss.ocaml.org/t/some-feedback-on-teaching-with-jbuilder-as-a-build-tool/3050

There are some workarounds suggested such as setting `OCAMLPATH` (from @diml):

```
$ OCAMLPATH=_libs:$OCAMLPATH dune ...
```

which will allow dune to find the cmos.

**Comment by rgrinberg** [comment]
There's now a 3rd workaround with dune-package files. You can write a dune-package file instead of a META file and set the environment accordingly.

I think this set of workarounds is sufficient so there's really not much to fix for this particular issue. You can even the set the environment in the workspace file, so there's really not much more we can do.
