### ISSUE TITLE
`@all` should not try to build -custom bytecode executables

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#1675]
When defining `byte` executables purely for the purpose of compiling to JS with `-no-check-prims` to avoid errors due to primitives which are only present in JS, they cause errors when compiling in `-custom` which makes `@all` unusable.

**Comment by diml** [comment]
Indeed, we talked about that with @rgrinberg. The only issue is that we can't remove the target when the `js` mode is not present without breaking backward compatibility. Although, we could add a field `(explicit_js_mode)` in the `dune-project` file to force the use of the `js` mode, and it would become the default in Dune 2.0.

**Comment by diml** [comment]
We just talk about this with @rgrinberg, putting it in the workspace file might break the build of vendored projects, so it should really only go in the `dune-project` file. Regarding the syntax, we could use either `(using explicit_js_mode 1.0)` or `(explicit_js_mode)`, but given that we expect this feature to not change until Dune 2.0 and to disappear with Dune 2.0, it seems simpler to just write `(explicit_js_mode)`. It's basically a property of the vanilla dune language rather than a proper extension.
