### ISSUE TITLE
How to emulate ocamlfind -dontlink lib?

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#1727]
Hi,

`ocamlfind` has some support for linking transitive dependencies (`-linkpkg`), while omitting certain archive files from the final binary (`-dontlink lib`).

This pattern is used in mirage: when building a xen unikernel, `-dontlink unix` is passed. This makes it possible to use libraries like `cstruct`, which otherwise would pull `unix` through `sexplib` and `bigarray`. `unix` cannot be linked because it requires C functions like `unix_readdir` which cannot be implemented.

The question is, how do we support this in dune? It's fairly easy to add a `(dontlink <lib_name list>)` field to executables, but this feels a bit low level. Is there a better way to achieve this?

Thanks!

**Comment by avsm** [comment]
I do think we can workaround this in the mirage base itself — requiring 4.07 due to the move to dune is reasonable as most of the ecosystem is there now (mirage-www needs a bump due to rrd, but it’s fairly easy to fix that)

**Comment by emillon** [comment]
It seems that making more libraries virtual, or splitting them to have more precise dependencies will solve most of this problem indeed.

But unfortunately, this is not only an issue with `sexplib` depending on `unix`. We're also "stripping" `str`, `num` and `threads`. This must be to circumvent similar overapproximations in the dependency graph, but I am not yet sure exactly which ones.

I can think of two other ways to fix this:
- we could generate fake C stubs (that just return an error) using an external tool. I think that jsoo does this.
- we could try to automatically shorten the list of library dependencies. The idea is that if the executable can be linked without a particular `.cmxa`, it should be omitted from the linking command line. (I don't know how to implement this. Is `ocamlobjinfo` output enough?)

In the meantime I'll check on some common unikernels what other paths pick the "blacklisted" libraries to see if it would be doable to just make some libraries virtual.

**Comment by avsm** [comment]
I think `str`, `num` and `thread` are special because they are in the standard library directory, and so "automatically" selected.  However, both `str` and `num` should work fine with Mirage, since the stubs should be available on all the hardware platforms supported (certainly this is true for Str, and can be made to be true for Num).

Threads is a different case.  We need to build without threads for Mirage if at all possible... this is related to #1724

**Comment by emillon** [comment]
@rgrinberg do you think it would be useful to use `*.ooi-deps` (maybe in an opt-in way) to remove the objects that are referenced as interfaces but not implementations? That would effectively be an automatic `(dontlink)`.

**Comment by rgrinberg** [comment]
> I think str, num and thread are special because they are in the standard library directory, and so "automatically" selected.

Indeed, but this should be fixed: https://github.com/ocaml/ocaml/pull/1569

In fact, we don't even have to wait for this to be fixed in dune. We could fairly easily re-create this directory layout in dune to avoid this issue.

> do you think it would be useful to use *.ooi-deps (maybe in an opt-in way) to remove the objects that are referenced as interfaces but not implementations? That would effectively be an automatic (dontlink).

Isn't this how linking already works in OCaml? If a module isn't referenced in an implementation, it will not be linked in. If not, then I suppose it's fine that we do this but it's a bit weird to be doing the linker's job here.

**Comment by diml** [comment]
One thing I have been thinking for a while is that we could also have an alternative distribution of OCaml that would build with dune and install things cleanly in separated directories. For most users it should be transparent and the experience would be improved.

**Comment by emillon** [comment]
So in the end we might not need that - the issue on the mirage side is tracked at mirage/mirage#969, we can close this issue once it's confirmed as not required.

**Comment by rgrinberg** [comment]
We now have a `(forbidden_libraries ..)` that sort of emulates this. Please re-open or create a new issue if it's not enough.
