### ISSUE TITLE
Experience report on trying to use Dune to build a Coq project.

### ISSUE THREAD

**Issue by Zimmi48** [ocaml/dune#2042]
1. `dune init` has been introduced in 1.9.0 but obviously it does not support Coq. No problem, it is easy enough to create a `dune` file based on the examples in the doc.
2. I add a single `dune` file, it creates a `dune-project` file automatically and put the following in it:
    ```scheme
    (lang dune 1.9)
    (using coqlib 0.1)
    ```
3. I try to rebuild, Dune says `Error: Unknown extension "coqlib"`.
4. I remove the "lib" part from `dune-project` that is an obvious (small) mistake and try to rebuild. Dune says `Error: Program ocamlc not found in the tree or in PATH (context: default)`
5. I add `ocamlc` to my `PATH` (even if it's a pure Coq project) and try to rebuild. It works :tada:

**Comment by ejgallego** [comment]
Thanks for the feedback @Zimmi48 !

Regarding 4, there has been some talk indeed on having `(using ocaml 1.0)` in Dune 2.0 so dune could work without OCaml; I'm afraid this is not the case today.

The biggest hurdle I've seen so far is due to `coqdep` oddities, in particular `coqdep` likes to do `exit 0` even when there are errors, this greatly confuses Dune as it tries to continue the build. I guess we will see how often that happens in the wild and maybe improve error messages here.

Likely the most important thing we need [apart from composition which is almost ready] is to have a good `dune-release` workflow for the Coq's opam repos; and of course coqdoc support.

**Comment by rgrinberg** [comment]
For 4, we'll need to factor the codebase a bit more. `Context.t` needs to be a little less OCaml specific and not require the OCaml bits so eagerly. It should be possible to do so today, even without having an explicit OCaml extension in dune.

**Comment by cpitclaudel** [comment]
I ran into issue 2/3 as well: `Info: appending this line to dune-project: (using coq.theory 0.1)` is wrong; it needs to append `(using coq 0.1)` instead.  I also mistakenly used `filename.v` instead of `filename` at first in the list of module; it would be nice to have examples in the doc.

**Comment by ejgallego** [comment]
Thanks to all, we can close this report for now I think; please open a bug if you would like to work towards being able to run Dune without `ocaml` in the path.
