### ISSUE TITLE
Build action by default?

### ISSUE THREAD

**Issue by ksromanov** [ocaml/dune#2062]
Is it possible to run `build` action, when `dune` is invoked without parameters? This probably would be more convenient in most cases than showing manual page (hardcore enterprise style).

**Comment by ksromanov** [comment]
It is just inconvenient to me - _build_ is the most frequent operation. Currently it is worked around with `Makefile`, where the default action is always or almost always _build_.

I am really sorry, but it looks like the interface of `dune` did not have that much attention as performance. And this is the reason, why people use `make` as a frontend to `dune`. This might be a design decision and totally ok. On the other hand, `make`-alone becomes more convenient than `dune+make` for programs of _Hello world_ class.

**Comment by diml** [comment]
Well, that seems like an unfair judgement to me. We are putting a lot of effort into the interface of dune. I believe the main reason why people use `make` as a frontend is because that's what they are used to do, and also because you can't define your own commands as conveniently. i.e. the equivalent of `make foo` is something like `dune build @foo`, which is longer.

Initially `build` was the default action and `dune X` meant `dune build X` unless `X` was an action. However, this was ambiguous and not very future proof either, so we decided to change this behavior.

Now, we could make `dune`  and `dune arg1 arg2 ...` when `arg1` starts with a `-` mean `dune build ...`. That seems fine. However, it does mean that someone new typing `dune` might get a surprising behavior. So we have to be careful how we design this feature.

There are several ways to approch the problem:
- we could do the change suggested above, although I'm not sure we should do it before dune 2.0.0
- we could add an option in the configuration file
- we could allow to define user commands in `dune-project` files and allow to override the default command

**Comment by ksromanov** [comment]
>Well, that seems like an unfair judgement to me.

Sorry, this means that I misunderstood and that was a design decision. Closing.

**Comment by diml** [comment]
Yes, that was a design decision. However, I have been wondering about it for a while and I'd like to improve the current situation. I submitted a concrete proposal in #2097
