### ISSUE TITLE
[RFC] Improving the CLI

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#2097]
I propose to change the CLI as follow:

- when the first argument starts with a letter, it is always considered as a command name (as now)
- otherwise, the `build` command is implicitly assumed if at least one ancestor directory contains a `dune`, `dune-project` or `dune-workspace` file

The idea is to allow the user to type simply `dune` or `dune @all` rather than `dune build` or `dune build @all`. The first rule prevents ambiguities and the condition on the second rule is to make sure that `dune` doesn't crawl the whole hard drive when called outside a project.

**Comment by trefis** [comment]
Does that imply that `dune --help` would show me the manpage of the build command instead of the manpage listing the available commands?

**Comment by diml** [comment]
That's a good point. I don't think it should, it should be the same as the current `dune --help`. However, we should extend this man page to document the new behaviour.

**Comment by ksromanov** [comment]
I checked selection of `OPAM` packages (1472 packages, Github-only), out of them:

1. 126 use _dune_ only
2. 643 use _make_ only
3. 451 use both _make_ and _dune_

Among these 451, default _Makefile_ targets about 445 are various flavors of `dune build <args>`. Most common are `dune build` (236) and `dune build @install` (74) and `dune build @install --profile=release` (16), `dune build --profile release` (10) ,various `jbuilder build ...`  (20, half of which have `--dev`, half - not).

These are rough numbers, since I discarded more than 1/3 of repos (total 2288 repos in `OPAM`)

**Comment by ksromanov** [comment]
Since this is a `CLI` proposal - what about adding `run` target, similar to `stack run xxx`?

Syntax: `dune run` or `dune run hello_world` or `dune run hello_world.exe`

Purpose: simplify write-build-test loop for small projects: you do not need to dig into depth of `_build` directory to run anything. Semantics similar to `./program_name`.

Behavior:

1. Only runs an executable in `_build` directory, under corresponding profile, if executable is present. Does not try to build anything for simplicity of semantics. May warn that source code is newer than task, but executes anyway. Does not change current directory, when executing program!

2. If there is only one executable target and it is present, `dune run` runs it without requiring to specify name of the task. Otherwise it asks to specify correct executable.

Examples:
For `hello_world.exe` it it `dune run` in any subdirectory of the project.

For project with two executable targets `hello.exe` and `world.exe`:
1. `dune run` should output 
   "There are several targets: hello.exe, world.exe. Please specify the correct target, for instance dune run hello"
   and quit.

2. `dune run hello` === `dune run hello.exe`, runs `hello.exe` if the executable is build.

**Comment by hcarty** [comment]
@ksromanov Does `dune exec` do what you're looking for?

**Comment by avsm** [comment]
I'm generally in favour of simpler consistency for the CLI, subcommands since higher level tools (e.g. VSCode rules, or Makefiles) invoke dune directly.  For them, calling `dune build @all` isn't a burden at all.

**Comment by ksromanov** [comment]
> @ksromanov Does `dune exec` do what you're looking for?

Unfortunately it does not :-(. But yes, you are right - I missed `exec`. Updating comment above.

**Comment by diml** [comment]
@ksromanov I feel like we are diverging from the original conversation. Please open a separate ticket to discuss improvements to `dune exec`.

**Comment by ksromanov** [comment]
@diml does it worth it?

**Comment by Chris00** [comment]
If the motivation is to type less, wouldn't a shell completion mode be better?

**Comment by diml** [comment]
That's a fair point. In particular, I wonder how much we would still want the shorter command line if we add shell completion. Linking the ticket for shell completion: #126

**Comment by rgrinberg** [comment]
I also think that shell completion would be far more effective and that adding any kind of cleverness is gratuitous. If we make a few straight forward improvements to polling mode, that would cut down on the dune invocations by 90% for me. And as Anil said, proper integration would make this even less relevant.
