### ISSUE TITLE
Fun project: convert opam files to dune-project fields

### ISSUE THREAD

**Issue by ghost** [ocaml/dune#2128]
The goal is to make `dune upgrade` turn existing `<package>.opam` files into `dune-project` fields. More precisely, given a set of manually written `<package>.opam` files, `dune upgrade` would do the following:

- extract all the fields from `<package>.opam` files that:
  + are allowed at the toplevel of the dune-project file
  + are the same between all `<package>.opam` files
- add these fields to the `dune-project` file
- for each `<package>.opam` file, add a `(package ...)` stanza with the fields that dune knows about
- for each `<package>.opam`, filter out the fields that were added to the `dune-project` file either at the toplevel or in a package stanza and if there are any fields or comments left, wrote those in a new `<package>.opam.template` file

**Comment by avsm** [comment]
This would be amazingly useful!

**Comment by ksromanov** [comment]
Name suggestion - `dune convert-opam`, `dune from-opam` or smth like that.

`upgrade` is very generic, it is highly likely that you'll need to use this word to identify some automatic conversion between different versions of `dune`, `dune-project` or `dune-workspace`.

**Comment by diml** [comment]
My thinking was that `dune upgrade` is supposed to bring your project to the latest best standard.

**Comment by avsm** [comment]
I agree that putting this in `dune upgrade` makes sense. There have been no instances where I've run the command in recent times for the jbuilder->dune updates where it's done the wrong thing. So it would be good to continue that with this feature (and perhaps even add a check into dune-release to warn the user if there is value to be had from running `dune upgrade` prior to release)

**Comment by ksromanov** [comment]
> My thinking was that `dune upgrade` is supposed to bring your project to the latest best standard.

There are several problems with that:

1. _Best standard_ is not formalized, and it is highly likely that it will change. So, the semantics of `dune upgrade` will be unclear for most users, who have not read source code of `dune` recently. Currently it is very simple and straightforward "Upgrade jbuilder projects to dune" (yet the name does not say anything about _jbuilder_, though intuitively `upgrade` works with the same program, but different versions :-( ).

2. In tool hierarchy `dune` is normally below `opam`, which in turn should be below `rpm`/`dpkg`. Of course, a special utility can be made to update files belonging to lower levels from upper, but it should be an exceptional, manual operation. 
   So, during normal operation `OPAM` should update `.opam` files from `dune` files, not vice versa.

3. Overall, automatic update of hand-written files does not smell right. Sometimes leads to loss of formatting / comments, merge conflicts and etc. Generally it is better to separate human-written text from machine-written. It is similar to `pure` functions and functions with `side-effects`.
   So, it looks better to have one tool, which reads and executes `dune` files, and another one, which updates `dune` files. This way one `bash` function is "pure", another has "side-effects", and they are clearly separated.

An illustration for objection 2.  Suppose, in 5 years everybody forgot about `jbuilder` and `dune upgrade` does mechanical upgrade of `dune` files. One of the simplest use-cases is to work on the old project on the machine without `OPAM`. This way `dune` file is heavily edited, while `project.opam` is untouched and is no more valid. If we suddenly realize that we need to upgrade `dune*` files, we will unexpectedly add obsolete fields from `project.opam`.

-------------------------------
So, from my point of view `feature` is good, but the name is misleading. My proposal - separate utility `populate_dune_fields_from_opam` (it should not start with `dune` for more convenient tab-completion in shell).

**Comment by diml** [comment]
You are right that automatic update of hand-written files is a tedious operation. However, `dune upgrade` already takes care of preserving comments. It does reformat the files though, but in a world where we use more and more automatic formatters, that doesn't seem too bad. What are your thoughts regarding automatic formatters?

Regarding the name `dune upgrade`, we did intentionally use a generic term with the idea that we would keep it later to upgrade projects to the latest version of the dune language. I agree with you that *Best standard* is not formalized in general. However, I do believe that at any point in time there are generally accepted best practices. Additionally, the `(lang dune x.y)` in the dune-project tells dune which version of dune the user relied on the last time they worked on their project. In the end, I see *Best standard* as a function that depends on this version written in the `dune-project` file. Then `dune upgrade` simply brings a project from an older best standard to a newer one.

Initially, I did consider distributing this feature as a separate utility that wouldn't even be part of dune.  However, this is adding more burden on the dune team as we would now have to maintain one additional separate tool. Distributing it as part of dune might work, however I'm not too keen on dune installing too many things in bin/. That doesn't smell right to me :) Additionally, it goes against the principle I mentioned in my previous paragraph. For instance, if you wanted to bring a 5 years old project up to date, you would have to remember to go through all the steps corresponding to things that happened during these 5 years by hand, instead of being able to just rely on `dune upgrade`.

All that being said, I do understand your point of view, and I wouldn't be surprised if other users feel the same way. So I'm thinking of the following compromise: we go ahead with the proposed feature and once it is ready I'll prepare a branch on my dune fork that will add a separate utility offering only this feature. I will then drop a link to it here and will let either you or anyone else interested take care of packaging this utility. This way, `dune upgrade` remains as the dune developers intended it, but users who do not like it can still benefit from the opam->dune-project migration.

BTW, it is the first time I read about "tool hierarchy" :) The way I see it, there is just a bunch of tools that interact with each others in various ways, but none is really on top of the other.

**Comment by ksromanov** [comment]
> Initially, I did consider distributing this feature as a separate utility that wouldn't even be part of dune. 

My point is that `write-to-dune-file` functionality should be removed from main `dune`. So there is no reason to make an additional utility, if you leave `dune upgrade` _fully functional_. This semi-solution just incorporates bad sides of both solutions - additional executable and write functionality in main `dune`.

> BTW, it is the first time I read about "tool hierarchy" :) The way I see it, there is just a bunch of tools that interact with each others in various ways, but none is really on top of the other.

Unfortunately is not very well articulated, but it is obvious that this hierarchy is present. There is a bootstrap order, which, of course, is obvious to anyone, who tried to bootstrap `ocaml` ecosystem or just to work with `ocaml` before `OPAM`. This actually defines hierarchy. However, this hierarchy comes up not only during build time.

In many systems `ocaml` ecosystem is partially installed (not everyone works in corporate environment, where everything is preinstalled by-default ;-) ). We can find out that some tools are useless without some others. For instance, there is no use in `OPAM` or `dune` without `ocaml`. In turn, `OPAM` is significantly impaired, if `dune` or `git` are not installed.

So, in many `Linux` distributions you can find only tools up to some level. For instance, `opam` is not mandatory. On the other hand, if you are compiling, say, `hevea` from sources, you do not need to install `OPAM` or `dune` - just compiler is enough.

And, of course, it is just a good architect practice - to organize software into layers.

**Comment by diml** [comment]
But if `dune upgrade` does not rewrite dune files, then what's its purpose? :) I admit that I'm not completely following what you are asking for in the end. In your first message your proposed to distribute an additional `populate_dune_fields_from_opam` binary, and now you say that an additional executable is not good. 

> In many systems ocaml ecosystem is partially installed (not everyone works in corporate environment, where everything is preinstalled by-default ;-) )

Absolutely! Making it easier to get a fully functional ocaml ecosystem is something we definitely want to improve. In particular, that is something OCamlLabs is actively working on. @avsm can tell you a lot about it :)

Regarding the hierarchy, I'm not sure I completely agree. At the end of the day, you can install a ton of applications written in C on your system without ever installing a C compiler or build system. Similarly, someone might download a prebuilt version of opam and then use it to install an OCaml compiler. Dune can build a project against multiple unrelated versions of OCaml simultaneously, so it is definitely not tied to one compiler. opam and dune just happens to be an application written in OCaml. So in a way, we could see opam and dune as above OCaml.

All we can say is that there are relationships and many different combination:
- opam and dune are written in OCaml and require a working ocaml installation to build themselves
- opam can install and manage one or more OCaml installation
- opam can install dune
- opam builds with ocaml and dune
- dune can build against several opam installations in parallel

In one use case, a tool is above the other, in another one, it is the opposite.

**Comment by avsm** [comment]
Thanks for the very interesting discussion points above! Some thoughts on them from me:

### "Dune should be purely functional"

When invoking `dune`, all the input parameters (source tree, environment, external filesystem) are tracked and checksummed, and the output artefacts are usually stored in `_build`.  However, there are several ways that `dune` can modify the source tree:

- `dune promote` will mutate the source tree if diffs are present in the `_build` directory in the form of `.corrected` files. This mutation can happen as part of `dune build` if `--auto-promote` is specified.
- `dune build` will write some metadata files into the source tree such as `.merlin`. These are intended to be ignored by version control, and in the longer term won't be needed as services interact via the Language Server Protocol. 
- `dune upgrade` will directly modify files in the source tree as a one-off service.

So the theme here is that invoking `dune` has carefully controlled _effects_, rather than being purely functional.  For each CLI invocation, we can define precisely what set of files will change -- for example, a `dune build` will only have the effect of modifying `_build/**` and `**/.merlin`, whereas `dune build --auto-promote` will have those effects as well as potentially modifying `./**`. Crucially, it never writes outside of the source tree and only reads from those files.

Having these effects is completely manageable for the developer because behind every dune tree usually lies a VCS. We can depend on the VCS to help us revert or stage particular changes, and generally to manage the "commit" phase of effects. One of the questionable features in `dune upgrade` in my mind is that it automatically `git add`s the new files -- this is dangerously close to wandering into territory that should almost certainly be owned by the developer and not dune.  But aside from that, any other effects from dune can be undone very easily. 

So my thoughts on `dune upgrade` are that it should continue to do the mutations, but we could be very clear in the docs on what the expected effects are for a particular mutating CLI command like `dune upgrade`.

### Is there an OCaml tool hierarchy?

This is also a really interesting observation @ksromanov!  I agree with @diml that the tool hierarchy is more of a graph of relations than a strict hierarchy.  In your initial example, `opam` would definitely sit beside `rpm` and `deb` (since they work independently on `dune` projects), but `opam` would be below `npm` (which normally wraps opam).

From a `dune` perspective, it's heading straight down to the bottom of the dependency graph since it fulfills the same purpose as `make`.  There is already fledgling support for building OCaml itself with `dune`, and we are considering decoupling the `dune.configurator` OCaml libraries from the `dune` binary. This will make it simple to package install the `dune` host binary as the first package, then use that to build ocaml and opam.

Having a rich build language at the base of the dependency tree is extremely useful from a metadata perspective, since other higher level tools can use this knowledge.  In the case of `dune-project`, moving the opam metadata in there means that it can also be used by generators of other packaging -- for example to create reliable deb/rpm packaging with source epochs regularly incremented to reflect changes in the binary outputs.  That's very hard to do from opam, but tractable from the build system which has fine-grained dependency information.

The role of `dune upgrade` in all this is therefore quite important -- it can take a _batch_ of dune projects (all of which might have different dune versions) and bring them all up to a common ground. This is only possible reliably because of the versioning in the metadata files.  Whether or not the programmer _accepts_ these changes is down to their use of the VCS.  In the worst case, if `dune upgrade` does something I only 50% want, I can only stage my desired changes. It's never an automatic operation.

Having said that, it might be good to give it a few CLI options to skip individual passes (e.g. `--skip-jbuild` or `--skip-opam`).  I've yet to see a concrete reason for this yet, since it's been easy enough to fix the functionality in `dune upgrade` and stick to one behaviour.  I've probably upgraded around 100 libraries from jbuild->dune, and by the end it was fully automatic.

**Comment by ksromanov** [comment]
> But if `dune upgrade` does not rewrite dune files, then what's its purpose? :)

A bit different angle from @avsm - `dune` is a function in shell language. We want it to be predictable, so, the best would be to avoid `dune upgrade` at all. So, it would be more _pure_.

If you can't avoid it, it would be better to at least remove circular dependencies between `dune` project file and `<project>.opam`. So that

```ocaml
val dune : "dune-file" ref -> ("_build", "project.opam")
```

instead of proposed

```ocaml
val dune : "dune-file" ref -> "project.opam" -> ("_build", "project.opam")
```

Ideally I would like to have `dune` program absolutely pure on input data. Just like we have `clang` compiler and `clang-format`. Despite `clang-format` is essentially a stripped compiler, we have a clear separation between mutable and immutable shell functions.

The build system problem is very very very complicated. And, as I continue observe, it is very hard for build system authors to have them reasonably simple for the end user. And clear separation between mutable and immutable shell functions can help simplicity.

But, again, if think that `dune upgrade` should go a different way, I am perfectly ok with that.

> Regarding the hierarchy, I'm not sure I completely agree. At the end of the day, you can install a ton of applications written in C on your system without ever installing a C compiler or build system.

Of course this hierarchy is not strict or absolute. Of course, you can install OPAM without installing compiler. But in this situation OPAM is almost absolutely useless. Of course, there are some rare situations, say when you want to install just OPAM to show your friend connection speed. But we are not mathematicians from classic joke, right?

And there are many situations, when we are ok without OPAM and the rest of ocaml ecosystem. Just with plain compiler. And from engineering point of view it would be better to have these layers separate, or ocaml ecosystem will become a tightly coupled mess.

**Comment by diml** [comment]
The idea is that there is an inversion of ownership when you start using the dune feature to generate opam files. i.e.,

- before: the user manually edits dune-project and package.opam files
- after: the user only manually edits dune-project and (optionally) package.opam.template files, but package.opam files are under the control of dune and shouldn't be edited by the user

`dune upgrade` simply upgrade the project from one state to the other.

Then, there is a step 3: eventually opam will be able to call `dune something` to generate the opam files on the fly, which means that we will no longer need to commit package.opam files in the repository.

**Comment by avsm** [comment]
Right, it sounds like we are all in agreement here: dune and opam shouldn't be tightly coupled.

The inversion of ownership @diml notes above  is really important, since it puts `dune` in charge of that project metadata instead of `opam`, and from then on you _do not need opam_ to use that metadata.  Therefore it will continue to work in an environment which only has `dune` (and `ocaml`) installed.

Is there some way we can make this transfer of ownership explicit?  @rgrinberg added an `x-generated-by` field to the .opam to indicate it was autogenerated, but we pulled it from the final PR for reasons of aesthetics.

**Comment by diml** [comment]
Maybe we could just generate a comment? For instance:

```
# This file is generated by dune, DO NOT EDIT
```

**Comment by ksromanov** [comment]
> Maybe we could just generate a comment? For instance:
> 
> ```
> # This file is generated by dune, DO NOT EDIT
> ```

That would be very appreciated!

**Comment by avsm** [comment]
That makes sense. The reason @jonludlam and I didn't do that in the original revision of the PR was that we could partially override files. Now with the `opam.template` support, there is no need to ever edit the `opam` file, so the comment does make sense.

I prefer something a little less shouty though :-) e.g.

```
# This file is generated by `dune build`, edit `dune-project` instead
```

**Comment by rgrinberg** [comment]
#2155

**Comment by ksromanov** [comment]
> I prefer something a little less shouty though :-) e.g.

That is better, because it tells, what to fix.

**Comment by rgrinberg** [comment]
There's already plenty of dune-project files in the wild that isn't necessary anymore.
