### ISSUE TITLE
Optionally un-vendor bundled dependencies?

### ISSUE THREAD

**Issue by TC01** [ocaml/dune#220]
Hi,

I've been working on getting opam officially packaged on Fedora. Since opam now needs jbuilder to build I'm also working on getting jbuilder packaged on Fedora.

The vendored dependencies in jbuilder (re, cmdliner, opam-file-format) are all build requirements for opam as well, so I've already created packages for them. I was wondering if it would be possible to easily unbundle them from jbuilder. However it seems that it's *not* possible-- I attempted to remove vendor/opam-file-format and then remove the "jbuilder_" prefix from all references to opam-file-format in the sources. However, the bootstrap build still complains about a missing dependency after doing so.

I find this slightly confusing because [the jbuild file](https://github.com/janestreet/jbuilder/blob/master/src/jbuild) also refers to the "unix" package, which is built into OCaml, so... presumably the bootstrap build process is capable of looking up shared dependencies. I admit I don't fully understand the jbuilder bootstrapping process, though.

Anyway, can I confirm if this is indeed impossible, or is it something that should be doable? [Fedora packaging policy](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#Bundling_and_Duplication_of_system_libraries) allows bundled deps provided upstream is at least contacted publicly. So if the answer is "please don't do this", that's okay.

**Comment by diml** [comment]
Basically there is no standard location for OCaml libraries, except for the one installed by the compiler itself. The accepted standard is that `ocamlfind printconf path` reports the paths where one should look for installed libraries. That's what jbuilder does when it starts.

For the build of jbuilder itself, since we are using no other external libraries than the ones distributed by the compiler itself, we disable the call to `ocamlfind` to avoid issues. The call to `ocamlfind` during the bootstrap did cause problems in the past.

We could sort that out and allow jbuilder to use the installed versions of the libraries it vendors. However, I feel like this is a dead end. Some of these libraries have already or are planning to switch to jbuilder, so we'd end up with a recursive dependency problem. Additionally, even if we could sort out this issue, in the future jbuilder will be exposed as a library in addition to an executable. Then we'd end up in a situation where in Fedora the jbuilder library would reference the installed version of ocaml-re while in opam the jbuilder library would reference the vendored version of ocaml-re, which is likely to be a recipe for disaster.

Compilers and build system are the tools where it's hard avoid vendoring entirely.

**Comment by rgrinberg** [comment]
Something like this would be possible with a conjunction of features:

* My [vendoring proposal](https://github.com/ocaml/dune/issues/1016) which would remove all the code modifications we've made to 3rd party libraries.

* A workspace file that ignores the vendored sub directory.

However, I'll still close this ticket as WONTFIX. Even if it is possible, dune reserves the right to make whatever modifications are necessary to its own internal libraries so this is not recommended and not supported.

**Comment by jeremiedimino** [comment]
I was thinking again about this recently. There is a circular dependency here that is difficult to break given that many of the projects vendored by dune also require dune to build. However, I believe there is something that could be done to help distribution packaging.

My understanding is that for distributions, it is important to not duplicate code because of bug/security fixes. More precisely, if a library is duplicated in N projects, then when you need to backport a fix you end up having to go through all the vendored versions of this library and it is not sustainable.

While we can't break the cycle, we could at least allow to share the source code between the one that is needed to build dune itself and the code that is needed to build the third-party library as a standalone package.

More precisely, a distribution such as Fedora could tell the build of dune: go take the source code of cmdliner there rather than use the copy embed in Dune. "there" would be Fedora's version of cmdliner, which might contain Fedora's patches. Cmdliner would still be built twice, once for building Dune and once for building cmdliner itself, however patches to cmdliner would be shared.

I don't know if Linux distributions support this kind of "source-only" dependencies, but that could a path to explore.

**Comment by Et7f3** [comment]
@jeremiedimino can dune use git submodule or at least call git clone at specific hash ? So the update process is just changing sha. The last method is the one used by google https://github.com/google/skia/blob/master/DEPS if introducing git as deps can't be done it can fallback to vendor with git as optional deps. Git should be widely accessible even on windows.

**Comment by jeremiedimino** [comment]
That's one way of doing it. But the most important question is whether the high-level idea would work for Linux distributions. And I'm not sure git would be the answer here given that often packages are created from release tarballs.

Generally, you just have packages depending on other packages. Here, you want to say: the "ocaml-dune" package depends on "the sources of the cmdliner package". And thing that is "the sources of the cmdliner package" must not depend on the "cmdliner" package.
