### ISSUE TITLE
dune upgrade fails if files not in version control

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#2232]
It should probably just do a `mv` if `git mv` fails.  When running `dune upgrade` at the toplevel in a duniverse, I get:

```
yak:duniverse avsm$ dune upgrade
Info: creating file duniverse/stringext/dune-project with this contents:
| (lang dune 1.0)
| (name stringext)

Upgrading duniverse/stringext/stringext.opam...
Upgrading duniverse/stringext/lib_test/jbuild to duniverse/stringext/lib_test/dune...
         git (internal) (exit 128)
/usr/bin/git mv duniverse/stringext/lib_test/jbuild duniverse/stringext/lib_test/dune
fatal: not under version control, source=duniverse/stringext/lib_test/jbuild, destination=duniverse/stringext/lib_test/dune
```

**Comment by avsm** [comment]
(This is because duniverse doesn't `git add` the vendored directory by default, so they genuinely aren't known to git.  The `dune upgrade` works fine after a `git add duniverse`)

**Comment by diml** [comment]
We can add a `--no-vcs-integration` option to `dune upgrade`.

**Comment by rgrinberg** [comment]
I think `--no-vcs-integration` is a bit too manual. Can't dune detect this?

I'm marking this a requirement for 2.0 since `$ dune upgrade` will become even more important.

**Comment by diml** [comment]
The idea is to prevent dune from integrating with the VCS even if one is present.

I originally thought integration with the VCS was a nice feature as it allowed to just do `git reset --hard` to go back to the previous state rather than do `git reset --hard && git clean -dfx`. However, I'm not too fussy about it, so if you guys think it's extra I have no objection to removing it altogether.

**Comment by diml** [comment]
This was fixed in master
