### ISSUE TITLE
Run tests with options

### ISSUE THREAD

**Issue by hongchangwu** [ocaml/dune#2278]
Similar to https://github.com/ocaml/dune/issues/2145, currently it's not possible to pass options  to  `dune runtest` or `dune build @runtest`.

Most unit test frameworks (such as OUnit) supports additional options when running tests, such as running a subset of tests. This can be useful when you are developing a new feature or fixing a specific bug.

The only workaround I know is to use `dune exec` to run the test directly. Is there a better way?

**Comment by rgrinberg** [comment]
There's no better way (at the moment).

Running a subset of the tests is best done by splitting your test suite into logical groups with directories. Then `$ dune runtest <dir>` will only run the tests in that directory.

In the end, this isn't an issue specific to tests. It's not really possible to pass flags to specific actions in the command line because it's not clear how that feature would look like.

**Comment by hongchangwu** [comment]
Actually to think about it, even if there is some way to pass options it probably wouldn't work for `runtest`—since it is just a collection of test program, there may not be a single list of options that will work for all. 

For that to work I guess you need something other than `runtest`, i.e. some kind of built-in support for a testing framework. In general dune is opinionated, choosing the best tool for a given task (e.g. merlin for editor support, odoc for documentation, utop for top-level/REPL), however this is not the case for tests. Indeed this seems to have cause some confusion (e.g. #2257). Is this because there is no clear candidate yet?

**Comment by diml** [comment]
It's a combination of reasons. One is historical; switching from one build system to another is already quite a bit of work, so if you need to convert you whole test suite at the same time it can become too much. As a result Dune needed to support various different way of writing and running tests.

Another one is that currently there is no framework that covers all kind of tests one would want to write. Inline expectation tests are good for unit tests but not so good for integration tests.

Finally, Dune and tests framework such as ppx_inline_test/ppx_expect have very different development and release cycles so it's easier to make Dune agnostic against such test frameworks.

**Comment by hongchangwu** [comment]
@diml thanks for the background info. It makes a lot of sense now. It doesn't seem there is anything that can be done at this point so I'll close this.

Maybe a separate issue can be opened if someone has a concrete proposal to support a standardized testing framework..

**Comment by rgrinberg** [comment]
Rather than a standardized framework, another alternative is to design a dune <-> test framework interface. This way, dune will not impose a particular testing framework on users but still provide users with basic features like output style, test selection, passing options.

**Comment by diml** [comment]
Indeed. Here is a very simple proposal to help a bit the situation: we had a field `(promote_runner_as test)` to the `(inline_tests ...)` field. It would mean to use `test.exe` for the test runner rather than `.xxx.inline-tests/run.exe` and it would also promote it to the source tree. This would allow the user to manually run tests with the options they want directly from the source tree
