### ISSUE TITLE
Coq - how to do a 'Require Import' for libraries

### ISSUE THREAD

**Issue by nickbetteridge** [ocaml/dune#2378]
@ejgallego
I'm having no issues with using:
```
From my_dune_lib Require Import handlers.Mycode.
From my_dune_lib Require Import handlers.Mycode1.
```
which references Mycode.v and Mycode1.v

However, I'd like to be able to import the whole library so that I can discretely reference Mycode and Mycode1 - ie:
```
From my_dune_lib Require Import handlers.

Mycode.choose param
Mycode1.reverse another_param
```
however, trying to do this always gives me a:
```
*** Warning: in file Test.v, library my_dune_lib.handlers is required and has not been found in the loadpath!
```
Is there currently a way of doing what I'm trying to achieve?

**Comment by ejgallego** [comment]
That's a very good question, I assume you have files `handlers/Mycode.v` and `handlers/Mycode1.v`

Then in this case your scenario is not very well supported by Coq itself, in the past people used the `-R` option, however I'm a bit reluctant to add it (yet), but will study it.

I see several choices here:
- we could generate a `handlers` wrapper module, then your code should work, however the semantics of `Export` are still tricky upstream.
- we could add to Coq `Require Import foo as bar.` but that wouldn't exactly solve your problem.
- you could do `Module Mycode := handlers.Mycode`, however Coq doesn't have module aliases (yet) so that may cost you.

I'll think a bit more about it and come back with proposals, some Coq devs that are knowledgeable in this topic (@maximedenes, @herbelin, @ppedrot, @skyskimmer)

**Comment by herbelin** [comment]
Hi, at some long time ago, I was thinking at giving a semantics to `Require LogicalName` when `LogicalName` was bound to a physical directory.

A possible semantics is to look for a file of same name `LogicalName.v` in the directory and to require it (that would have matched the situation of Coq standard libraries where we typically have modules such `Bool.v` in a directory `Bool` and so on). Basically, this would be a short-hand for `Require LogicalName.LogicalName`. The `-R` approach is here also possible so that `Require LogicalName` finds the so-wrapping file `LogicalName.v` (as @ejgallego suggested in his first point).

Another semantics would be to load all vo files of the directory in some canonical order of dependency (maybe also ensuring that all .v of the directory have their .vo compiled). That would be cool and (based on your question) apparently intuitive.

**Comment by nickbetteridge** [comment]
Just got to a point where this would be highly beneficial :-) Is there any chance you could sneak in the -R option in time for the Dune 2.0 release?

@herbelin - yeah, loading all of the vo files of the library directrory would be very cool

@maximedenes - quick question - would your recent Import/Export changes help with this issue?

**Comment by maximedenes** [comment]
I'm a bit lost in the discussion, so sorry if I miss the point. IIUC what you want can be done using a wrapper module (listing all the `Require` directives). I don't see how this needs `Export`.

Assuming you have `handlers/Mycode.v` and `handlers/Mycode1.v`, you can write in `./handlers.v`:

```coq
From my_dune_lib Require handlers.Mycode.
From my_dune_lib Require handlers.Mycode1.
```

then from `test.v`:

```coq
From my_dune_lib Require Import handlers.

Mycode.choose param
Mycode1.reverse another_param
```

Basically, it seems to me that the only missing bit in you original example is the `handlers.v` file. If you don't put it in the `handlers` folder, but rather at the root of your library, I don't see why you'd need the feature described by @herbelin.

Again, sorry if I'm missing the point.

**Comment by nickbetteridge** [comment]
@maximedenes Apologies for referring to Export - I'm just starting out with Coq and my coding art is very much Ocaml at the moment - hence the request for being able to directly use references like ```Mycode.choose param```. 

Thanks also for your ```test.v``` example - however, this kind of highlights the point I'm trying to make. If I'm writing a large Coq codeset, with multiple directories/libraries, and some of of the Coq files in each library need to reference different functions then I'm going to need a unique ```handlers.v``` for each file. This really bloats the whole codeset.

I still think that @herbelin feature would be a useful addition to have.

**Comment by maximedenes** [comment]
> I'm going to need a unique `handlers.v` for each file

I thought you'd have a `foo.v` file for each `foo` *directory* that you want to load as a unit. Is that what you meant?

**Comment by ejgallego** [comment]
> Is there any chance you could sneak in the -R option in time for the Dune 2.0 release?

The main problem with -R is that it cannot be given a proper declarative semantics, other than indeed removing all the libraries boundaries which seems a bit far-fetched. It could be the case that adding `-R` to Coq was a mistake in the first place.

In OCaml land you can add `-open Foo` to flags, but I am not sure how this would be in Coq.

We could say that `(import_theories foo)` does add `foo` with option `-R`, however how to handle module clashes now?

**Comment by nickbetteridge** [comment]
@maximedenes - learning as I go along :) - I'm trying to use a set of old libraries in something I'm trying to build and I'm getting a ```required library List matches several files in path``` - hence my request for an ocaml-like module+function reference.

I guess my only current way forward is to re-write the old libraries and assign different names to the clashing libraries.

**Comment by ejgallego** [comment]
> @maximedenes - learning as I go along :) - I'm trying to use a set of old libraries in something I'm trying to build and I'm getting a `required library List matches several files in path` - hence my request for an ocaml-like module+function reference.
> 
> I guess my only current way forward is to re-write the old libraries and assign different names to the clashing libraries.

The solution for this would be to use `From Coq Require List` and `From mylib Require List`.

After thinking a bit I'm not sure how useful this automatic wrapper generation would be, I am leaning thus towards closing this issue with a won't fix. WDYT?

**Comment by nickbetteridge** [comment]
Fine by me
