### ISSUE TITLE
hello_world: "No rule found for alias ..."

### ISSUE THREAD

**Issue by mars0i** [ocaml/dune#240]
I cloned [jbuilder](https://github.com/janestreet/jbuilder), cd'ed to jbuilder/example/sample-projects/hello_world, and entered `jbuilder build @install`, as specified in README.org in that directory.  I get this error:

`No rule found for alias example/sample-projects/hello_world/install`

This is with OCaml 4.05.0 after `opam update` and `opam upgrade`. 

On discuss.ocaml.org, Thomas Leonard pointed out that adding `--root=.` to the `jbuilder build` command line fixes the problem, and that "Moving the example directory outside of the main jbuilder tree also fixes it."  He suggested that it might have to do with the jbuild-ignore file.  I assume he means the one in the examples directory.

Removing examples/jbuild-ignore allows `jbuilder build @install` to compile hello_world.exe, although then it's placed under a _build directory in the root of the jbuilder repo.

**Comment by dra27** [comment]
Yes, the jbuilder tree itself is somewhat complicated by the need to stop jbuilder from always building examples and tests (since tests for jbuilder necessarily include `jbuild` files themselves, the composability of jbuilder of kinda not our friend here!).

The obvious fix is to update README.org, but I wonder if we need an additional step in the determination of the root (see also #234, which is loosely related) - I've had it on other projects where it would be useful if determination of the root didn't go past directories which are supposed to be ignored (opam's latest build system sets up all kind of weirdness in src_ext both to vendor libraries and bootstrap jbuild itself as part of its own build system). Two possible mechanisms:

1. Introduce a new file `jbuild-stop` - the traversal in `bin/main.ml` would know that the workspace root is not allowed to be considered above this directory. Thus, if we put `example/sample-projects/jbuild-stop` and `example/sample-projects/hello_world/jbuild-workspace.dev` then `cd example/sample-projects/hello_world && jbuilder build` would work, since the root `jbuild-workspace.dev` would not be traversed.
2. Do (1) implicitly based on `jbuild-ignore` and require that the root may not be in a directory which involves passing through an ignored directory. In this case the `sample-projects` entry in `example/jbuild-ignore` would mean that the `jbuild-workspace.dev` in the repo root would be ignored and the root would be computed as `example/sample-projects`.

I think (2) is probably the better idea - (1) may be explicit, but it adds yet another piece of clutter in the worktree...

/cc @diml, @lpw25, @rgrinberg

**Comment by diml** [comment]
(2) seems fine to me since jbuilder does nothing interesting in an ignored sub-tree

**Comment by jordwalke** [comment]
I requested a feature like `jbuild-stop` [here](https://github.com/janestreet/jbuilder/issues/318#issuecomment-342795013).
The reason why I suggested a `jbuild-stop`, is because I can't control the contents of other packages/repos/dependencies, which I might be building in a directory like `./temporary_build_sandbox`. I can't make them include a `jbuild-workspace.dev`, or even a `jbuild-ignore`. I can, however, force there to be a `jbuild-stop` at `./temporary_build_sandbox` (or perhaps a `temporary_build_sandbox/jbuild-ignore` that includes `./temporary_build_sandbox` within itself.

**Comment by rgrinberg** [comment]
IMO `jbuild-stop` would also be a good feature. Though, I would prefer to call it `jbuild-root`.

**Comment by jordwalke** [comment]
As long as there's *some* way to prevent jbuilder from climbing higher, it will work for us. Files are nice because they're easy to debug and witness from the command line. Environment variables need to be set by your package builder/test suites and once the tests/builds are done running it's hard to dig in and prove it was setting the environment variable correctly at the right time

**Comment by rgrinberg** [comment]
@jordwalke 

> I can't make them include a jbuild-workspace.dev, or even a jbuild-ignore

Can't you already do this with `$ touch jbuilder-workspace`? Jbuilder will still traverse up in this situation to look for a higher level `jbuilder-workspace` but it will not find it in your case. Seems like it would ignore exactly as a `jbuild-stop` in your case.

**Comment by rgrinberg** [comment]
I believe this issue has been solved by dune-project files
