### ISSUE TITLE
dune always install ml files

### ISSUE THREAD

**Issue by hannesm** [ocaml/dune#2415]
sorry if this has been answered before, I was unable to find it in the issue tracker or on readthedocs.

I'm curious whether there is an option to not copy ml files around? Is there a specific reason for copying all ml files into `~/.opam/switch/lib/<library>`? (I understand that `mli` files are used by e.g. merlin)

**Comment by rgrinberg** [comment]
.ml files are used by merlin as well. Consider sources without .mli files for example. I also recall an option for merlin to always jump the .ml file as well.

**Comment by hannesm** [comment]
well, yes - i ended up there, my emacs showing me an implementation, and me modifying that instead of my git clone (and quite some wasted work discovering this)... that actually brought me to opening this issue here... so, is there an option in dune to disable installation of ml files?

**Comment by rgrinberg** [comment]
There's no such option. While unfortunate, your problem doesn't seem like something that dune should solve

**Comment by emillon** [comment]
Maybe we can install them read-only?

**Comment by diml** [comment]
Installing them read-only seems like a good idea to me. After all, these are not supposed to be modified by the user. For this to work with opam, `opam-installer` would need to be modified as well.

FTR, Dune initially installed only mli files, except for ml-only modules. We changed that to installing both ml and mli files because merlin allows to jump to the implementation of functions from installed libraries.

**Comment by rgrinberg** [comment]
Sounds good to me. Let's do it for mlis as well then

**Comment by hannesm** [comment]
@emillon thanks for the suggestion, yes installing them read-only would solve my issue.

thanks again!

**Comment by rgrinberg** [comment]
Dune already makes them read only but opam overwrites the permissions.
