### ISSUE TITLE
Dune-generated object cannot be compiled with C++

### ISSUE THREAD

**Issue by inumanag** [ocaml/dune#2618]
We have an OCaml component that is used within a larger C++ application. So far we were generating a library through dune via `(modes (native shared_object))`, but that necessitated dynamic linking of asmrun during the C++ build stage (via `-lasmrun`). This was not good as we want to ship the app without any external OCaml dependencies.

We tried generating object via `(modes (native object))` and passing it to our C++ build stage, but were not able to get it working. While dune produces an object, any attempt to compile it on Linux fails with:

```
/build/glibc-KRRWSm/glibc-2.29/nptl/allocatestack.c:526: undefined reference to `_dl_stack_flags'
/usr/bin/ld: /build/glibc-KRRWSm/glibc-2.29/nptl/allocatestack.c:646: undefined reference to `_dl_stack_flags'
/usr/bin/ld: seqparser.o: in function `do_set_elision_enable':
/build/glibc-KRRWSm/glibc-2.29/nptl/../sysdeps/unix/sysv/linux/x86/elision-conf.c:67: undefined reference to `_dl_x86_cpu_features'
/usr/bin/ld: seqparser.o: in function `__pthread_initialize_minimal_internal':
/build/glibc-KRRWSm/glibc-2.29/nptl/nptl-init.c:280: undefined reference to `_dl_cpuclock_offset'
/usr/bin/ld: /build/glibc-KRRWSm/glibc-2.29/nptl/nptl-init.c:397: undefined reference to `_dl_pagesize'
/usr/bin/ld: /build/glibc-KRRWSm/glibc-2.29/nptl/nptl-init.c:406: undefined reference to `_dl_pagesize'
/usr/bin/ld: /build/glibc-KRRWSm/glibc-2.29/nptl/nptl-init.c:422: undefined reference to `_dl_init_static_tls'
```

This seems to be an issue with ctypes on Linux (macOS has no such issues), as they somehow embed pthreads within .o that makes all this mess. A hack around this on Linux was to use
```
ln -s /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a build/libpthread.a
```
but the new versions of glibc do not ship libpthread_nonshared.a anymore.

Does anybody has a similar problem? Is there any way we can get a "clean" object without embedded pthread mess?

For the reference, my dune file is:

```
(env
   (dev (flags (:standard -w @a-4-29-40-41-42-44-45-48-58-59-60-40-26-27 -warn-error -A))))
(executable
   (name main)
   (libraries
      base core ctypes ctypes.foreign ctypes.stubs
      our_lib)
   (modes (native object))
   (link_flags (:standard -I ../../../build -I %{env:DUNE_LIBRARY_PATH=.}))
   (preprocess (pps ppx_sexp_conv ppx_deriving.show)))
```

(as a side note, we had to explicitly pass a `DUNE_LIBRARY_PATH` variable (set to `/usr/lib/x86_64-linux-gnu`) to dune as it was not otherwise able to locate any system libraries such as libffi that are needed for ctypes).

**Comment by diml** [comment]
Reading this PR, it's not clear to me whether the issue is with Dune or ctypes. I suggest to open a ticket on ctypes as well with a link to this issue so that ctypes authors are aware of this issue as well.

**Comment by inumanag** [comment]
Hi @diml,

here is a minimal working example that does not depend on Ctypes:

main.ml:
```
open Core
let main () = 
  printf "hello!\n"
main ()
```

dune:
```
(executable
   (name main)
   (libraries base core)
   (modes (native object)))
```

`dune build main.exe.o` results in:

```
    ocamlopt main.exe.o (exit 2)
ld: cannot find -lpthread
ld: cannot find -lrt
File "caml_startup", line 1:
Error: Error during linking
```

I am really puzzled why is any linking step (ld) involved when making an object file?
This can be fixed with adding  explicit -I /usr/lib/x86_64-linux-gnu link flag, but then it causes problems when I try to use .o file.

FYI, it's dune 1.11.3 on ocaml 4.08.1.

**Comment by diml** [comment]
Ah, this looks very similar to a problem we stumbled upon with @aalekseyev the other day. IIRC, this is a problem that is not easy to solve right now. When producing a `.exe.o` file:

- the C libraries for the C stubs should be linked statically
- the global C libraries such as `pthread` or `rt` shouldn't be linked at all, and should instead be linked by the application that will link in `main.exe.o`

The only problem is that currently both kind of libraries are specified at the same level directly in `cmxa/cma` files. You can see that if you run `ocamlobjinfo` on `core.cmxa` for instance. The compiler uses this information to know what C libraries to link in when linking the final executable.

It seems difficult to solve this problem in dune only, i.e. without changing the compiler. However, here is an idea we could try:
- when linking a `.exe.o`, we pass `-noautolink` to `ocamlopt` so that it doesn't try to link in the C stubs
- we manually pass the `-l` for all the stubs transitively
- we produce a separate `.exe.o.clibs` files with the list of linker flags to pass to the executable that will statically link the `.exe.o`

That requires collecting the information about the stubs/linker flags outside of cmxa files, so it would only work when all the transitive dependencies are using Dune. But that seems acceptable.

**Comment by inumanag** [comment]
Thanks @diml for the explanation!

Yeah, what we ended up doing yesterday was pretty much what you suggested: pass `-noautolink` and then fish for 20 stubs that need to be linked statically.  At least it works without any weird path hacks.

Do you know is there a more principled approach for finding all different stubs? E.g. they differ on macOS/Linux (integers/libintegers_stubs.a vs integers/libintegers.a) and between different Ocaml versions (right now we have a huge list that we iterate over and pick whichever stub is available, but this can break anytime).

**Comment by diml** [comment]
It's going to be difficult to do outside of Dune. Could you give a try to #2632?

**Comment by rgrinberg** [comment]
Please re-open if the proposed workaround didn't work for you.
