### ISSUE TITLE
`dune clean` does not remove an opam file

### ISSUE THREAD

**Issue by nekketsuuu** [ocaml/dune#2624]
If we enable [`generate_opam_files`](https://jbuilder.readthedocs.io/en/latest/dune-files.html#generate-opam-files), Dune automatically generates a suitable opam file from `dune-project`.

I noticed that if we run `dune clean` after generating the opem file, Dune does not remove the file. I wonder if this behavior is intended. I think this behavior may be useful for publishing a library to the OPAM repository, but this behavior is against a help of `dune clean`; it says "`dune clean` removes files **added** by dune" (bold by me).

If this behavior is intended, then I want to write a document to clarify that.

### How to Reproduce

```sh-session
$ ls
[... some files ...] dune-project
$ dune build
$ ls
[... some files ...] _build dune-project myproject.install myproject.opam
$ dune clean
$ ls
[... some files ...] dune-project myproject.opam
```

### Environment

* Dune 1.11.3
* OPAM 2.0.5
* OCaml 4.08.1

**Comment by diml** [comment]
This is indeed intended. For `opam pin` to work well with development versions, it is important that the opam files are still committed in the repositories. That's why `dune clean` leaves them in the source tree.

In the future, we expect that opam will allow to generate opam files on the fly via dune and at this point it will no longer be necessary to commit opam files in repositories.

**Comment by nekketsuuu** [comment]
@diml Thanks for your detailed explanation. Now I understand why there is no documentation for this; it will be unnecessary in the future. I close this issue :)
