### ISSUE TITLE
man pages go into wrong directory

### ISSUE THREAD

**Issue by olafhering** [ocaml/dune#2670]
make install shold install the man pages into `/usr/share/man`.
Right now they go straight into `/usr/man`, and there seems to be no way to override this directory.

**Comment by diml** [comment]
Indeed. We should add a `--mandir` option to `dune install`

**Comment by rgrinberg** [comment]
@olafhering do you want to try implementing this? it should be fairly short.

**Comment by olafhering** [comment]
It would be enough to have this via `configure.ml`. But then, if it exists there, it might be easy to have it also as a global knob at runtime. I will try it, yes.

**Comment by toots** [comment]
I concur with this. This is particularly relevant because it is explicitly documented in the FHS here: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html#usrsharemanManualPages

There is a similar issue with `/usr/share/doc/<package>` but this one is not referenced in the standard so it's less pressing.

**Comment by ejgallego** [comment]
Wait, `dune install --mandir` already works, right?

**Comment by rgrinberg** [comment]
Yeah, not only that but it's also possible to configure the default dir when building dune. This was introduced in 2.1.0 as far as I can tell.
