### ISSUE TITLE
Multiple rules generated for _build/default/tests/findlib_initl.cmo

### ISSUE THREAD

**Issue by aantron** [ocaml/dune#2674]
Caqti 0.11.0 build fails with

```
Error: Multiple rules generated for _build/default/tests/findlib_initl.cmo:
- <internal location>
- <internal location>
```

Steps:

```
git clone https://github.com/paurkedal/ocaml-caqti.git
git checkout v0.11.0
opam install --unset-root lwt
opam install --deps-only ./caqti.opam
dune build
```

I'm not sure if this issue is valid. More recent versions of Caqti don't have the problem. It could be a bad build configuration in old Caqti, but perhaps it is worth looking at.

The problem first appears in Dune 1.10.0. Earlier versions don't seem to have it.

**Comment by aantron** [comment]
The latest version I tried was 1.11.3.

**Comment by diml** [comment]
AFAICT, the opam build succeed, it's just building the tests that fails. Can you confirm?

This is due to the use of a `jbuild` file rather than a `dune` file. In particular, the error is gone in the master of caqti when the `jbuild` file has been replaced by a `dune` one. Jbuilder used to put artifacts in the main directory while dune puts them in a dot-subdirectory. For backward compatibility, dune was symlinking the artifacts to the main directory when a `jbuild` file was used. The `Findlib_intl` module is generated for every `executable`/`test` that uses `findlib.dynload`, that's where the issue came from.

**Comment by aantron** [comment]
> AFAICT, the opam build succeed, it's just building the tests that fails. Can you confirm?

I had this on ordinary builds of `caqti-lwt` with the dependencies installed, not test builds, as you can see from the repro instructions, and also the command in the opam CI log.

You're welcome to close this issue. I am not sure if you think it is worth fixing.

**Comment by diml** [comment]
Alright, upgrading from `jbuild` to `dune` files is the right fix in this case :) So closing this issue
