### ISSUE TITLE
[dune_memory] get rid of Sexp.t in favor of Dyn.t

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#2800]
`Sexp.t` is obsolete.

cc @diml.

**Comment by diml** [comment]
For the protocol, `Dyn` won't be enough as we also need some versioning. Originally, I was thinking of replacing `Sexp.t` by `Dune_lang.t`, but on the other hand it's introducing a too high-level language for something that is essentially machine read and written.

So instead, I'm thinking of the following plan:
- generalise `Dune_lang.Decoder` so that it is independent of the format. I.e. the `Decoder` module will no longer depend on `Dune_lang`. One will be able to write a decoder and at the time we want to actually parse something in dune_lang, sexp, json, ..., we'll glue things together
- use `Decoder` in the memory and keep the low-level s-expression format
- come up with something similar for `Encoder`

**Comment by rgrinberg** [comment]
Sexp.t was replaced with Csexp in the end.
