### ISSUE TITLE
Feature request: run actions in install environment

### ISSUE THREAD

**Issue by stedolan** [ocaml/dune#289]
`jbuilder exec` allows me to run programs in an environment in which the package appears to be installed, by manipulating `$PATH` and friends. 

However, I can't seem to define an `(action ...)` in a jbuild file that has a similar effect. `(action (run ...))` leaves `$PATH` as-is, so binaries that are built by the package are not available except by knowing the build path. (I would like to do this in order to test the command-line interface of a binary the package installs).

**Comment by rgrinberg** [comment]
I've had a brief look at this and one thing to note about having such an action is that it will depend on all public (`@install`) binaries to be built. This also makes jbuild projects that depend on such actions a bit annoying to vendor. Since the target of `@install` binaries will grow much larger.

@stedolan are you OK with such caveats?

**Comment by stedolan** [comment]
Those caveats sound right to me! My use case is an action in `runtest` that tests the command-line interface of the installed binaries, so it would be incorrect not to depend on @install.

**Comment by rgrinberg** [comment]
I believe this is solved by having `(package ..)` dependencies. Btw, we'd like to make the dependency language fine grained enough that you can simply depend on the particular executables that you'd like to have in PATH.

**Comment by stedolan** [comment]
`(package ...)` dependencies solve my problem perfectly, thanks!
