### ISSUE TITLE
diff? error: Rule failed to generate the following targets

### ISSUE THREAD

**Issue by anton-trunov** [ocaml/dune#2990]
Please consider the following self-contained example in the form of a `dune` file:

```
(executable
 (name print)
 (modules print))

(rule
 (with-stdout-to print.ml
  (echo "let () = print_endline \"MESSAGE\"")))

(rule
 (alias runtest)
 (action
  (progn
   (with-stdout-to output.expected (echo "MESSAGE\n"))
   (with-stdout-to output.actual (run ./print.exe))
   (diff? output.expected output.actual))))
```

When I run `dune runtest` it generates the following error message which I find confusing:

```shell
$ dune runtest
File "dune", line 9, characters 0-195:
 9 | (rule
10 |  (alias runtest)
11 |  (action
12 |    (progn
13 |     (with-stdout-to output.expected (echo "MESSAGE\n"))
14 |     (with-stdout-to output.actual (run ./print.exe))
15 |     (diff? output.expected output.actual))))
Error: Rule failed to generate the following targets:
- output.actual
```

According to the manual,
>(diff? <file1> <file2>) is similar to (diff <file1> <file2>) except that <file2> should be produced by a part of the same action rather than be a dependency, is optional and will be consumed by diff?.

In this case (please correct me if I'm wrong) <file2> is produced as a part of the same action, so I would expect no error. Changing `(diff? ...` to `(diff ...` works as expected. Perhaps it's a documentation issue?

**Comment by diml** [comment]
The documentation looks correct; it states that `diff?` will consume `output.actual`. That's why it doesn't appear as a target. However, the problem is that dune targets inference doesn't detect this case. i.e. it should know that `diff?` will delete `output.actual` and so should consider `output.actual` as a target.

**Comment by diml** [comment]
If you'd like to take a stab at fixing this issue, the code to change is in the `Infer` sub-module in `src/dune/action_unexpanded.ml`. In the `| Diff` branch of the `infer` function, if `optional` is true we need to remove `file2` from the set of targets.

Otherwise, one of us will look at this at some point.

**Comment by greedy** [comment]
I was bitten by this bug too so I took a stab at a fix.

**Comment by jeremiedimino** [comment]
This has been fixed.
