### ISSUE TITLE
dune-project: support singular (author)

### ISSUE THREAD

**Issue by emillon** [ocaml/dune#3004]
Hi,

I was playing with opam file generation and noticed that the keys in the dune-project file map directly to opam ones, so it is necessary to use `(authors "Frank Herbert")` even when there is only one author.

I was wondering if we could allow `(author "Frank Herbert")` as an alternative syntax where there is only one author (and it fails in the case of several authors).

As a bonus, this would fail in the case where several authors are passed by mistake, for example `(authors Frank Herbert)` corresponds to two authors ("Frank" and "Herbert") but `(author Frank Herbert)` is an error case.

Of course, this applies to `(maintainers)` as well, and maybe to `(tags)` (though I'm not sure about that last one).

What do you think?

(cc @voodoos)

**Comment by shonfeder** [comment]
FWIW, I think I personally prefer having a single, general way to specify such data when it is so straight forward rather than multiple ways with subtle differences for special cases. Both in terms of the data model and as a user, if a field can have multiple values, I'd rather it just be a `value list` rather than a `Singular of value | Plural of value list`. I can see how reasonable people would have a difference of opinion on this though!

**Comment by rgrinberg** [comment]
I don't think this is a good idea either. I would prefer if dune files stayed as canonical as possible and I even regret all the pluralized versions of stanzas that were added.

**Comment by emillon** [comment]
Makes sense. All right, let's scrap that idea!
