### ISSUE TITLE
Dune should accept lablgtk as library instead of lablgtk2

### ISSUE THREAD

**Issue by OCamlPro-mattiasdrp** [ocaml/dune#3049]
## Expected Behavior

With lablgtk installed through opam and trying to compile with dune, `(libraries lablgtk)` should allow me to compile when using lablgtk inside my program.

## Actual Behavior

Dune answers 
> Error : Library "lablgtk" not found.

## Reproduction

1. Create a dummy file 
> main.ml
>```ocaml
>let () = ignore (GMain.init ())
>```
1. Create a dune file 

> dune
> ```
> (executable
>   (name main)
>     (libraries lablgtk)
> )
> ```

1. Have lablgtk installed (through `opam install lablgtk` for example)
1. Compile `dune build main.exe`

To circumvent this issue you need to change the dune file : 

> dune
> ```
> (executable
>   (name main)
>     (libraries lablgtk2)
> )
> ```

Problem is, by doing so if lablgtk is not installed on your computer, dune will tell you to try install lablgtk2 which is not an available package.

## Specifications

- Version of `dune` (output of `dune --version`) : 2.1.3
- Version of `ocaml` (output of `ocamlc --version`) : 4.09.0
- Operating system (distribution and version) : Ubuntu 19.10

**Comment by diml** [comment]
Unfortunately there is not much we can do in Dune. The problem is the following:
- the opam package is called `lablgtk`
- the opam package installs a library that is called `lablgtk2`

Dune doesn't know about installed opam packages, it only knows about installed OCaml libraries. So it doesn't know anything about a library called `lablgtk`. You can see what installed libraries `dune` can see by typing:

```
$ dune installed-libraries
```

Nowadays, it is considered good practice to name libraries after the opam package name. However, this wasn't always the case and that's why for some packages such as lablgtk the name of the library doesn't match the name of the opam package. The good news is that if you use lablgtk3, the name of the opam package and library are matching.

**Comment by OCamlPro-mattiasdrp** [comment]
Ok, I understand. Good thing there is now good practice but this means that everytime an opam package doesn't have the same name as the library it installs dune will fail on it. Since dune gives as an hint "have you tried `opam install <missing_package>` wouldn't it be interesting to update dune to manage these kind of behaviours.

From my understanding it looks like the consensus is : one package = one library but what if in the near future we have opam packages installing multiple libraries?

I may be completely wrong ;-)

**Comment by diml** [comment]
Well, dune enforces that the package name and library name must match and the majority of OCaml packages are now build with dune, so it doesn't seem worth complicating dune for packages that don't follow this convention.

Regarding an opam package installing multiple libraries, that's fine as well. The good practice in this case is to name the various libraries either `<package>` or `<package>.something`. For instance `lablgtk.foo`, `lablgtk.foo.bar`, etc...

**Comment by OCamlPro-mattiasdrp** [comment]
That's what I saw and thought. Hope everyone will comply with this useful standard ;-)
