### ISSUE TITLE
dune init appears to ignore its name argument

### ISSUE THREAD

**Issue by emengd** [ocaml/dune#3088]
Dune version:  2.1.3

When I do `dune init exe myexe` I get the following `dune` file:
```scheme
(executable
 (name main))
```
plus a file `main.ml`.

I expect `name myexe` and a `myexe.ml` file. Did I misunderstand what `dune init` is supposed to do?

**Comment by shonfeder** [comment]
Thanks for the report, @emengd! 

So, under the current behavior, the name argument for `executable` components only applies to the `public_name` field. E.g., (note the addition of the `--public` flag):

```sh
[sf@comp dune_test]$ dune init exe myexe --public
Success: initialized executable component named myexe
[sf@comp dune_test]$ cat dune 
(executable
 (public_name myexe)
 (name main))
```

This entails that all initialized `.ml` files for executable components (whether public or private) will be called `main.ml`.  The (admittedly confusing) result is that the name is simply ignored when the executable component is not public! I can't recall whether this was a design error or an implementation error, but it is confusing behavior regardless.

- re: **private components**, it seems like the right thing to do is to name the `.ml` files the way you were expecting.
- re: **public components**, I am not sure whether or not we want to change the behavior, since it might be viewed as a positive that we enforce the (imo, reasonable) convention that the main module of public executables is named `main`.

**Comment by emengd** [comment]
Thanks for the answer! One thing I can say is that I would definitely expect to get `(name myexe)` based on the current documentation (by which I mean `dune init --help`). The meta-variable is called `NAME`, and there is a `--public` option that sets the public name and “defaults to the name”, so you expect this argument to become the `name` field.

I would also find it confusing if the positional argument had a different meaning depending on whether `--public` is present.

Here are two states that I find not confusing:

1. The argument is called `PUBLIC_NAME`. Components are public when it is present, and it determines the value of `public_name`. Otherwise they are private. There could be an option to set the `name` that defaults to `main` (with perhaps no argument meaning “same as public”).

2. The argument is `NAME`. It sets `name` in all cases. The public name can only come from `--public` (the behaviour I was expecting).

**Comment by shonfeder** [comment]
I agree with your reasoning. Indeed, the current inline help (which I wrote) is incorrect, as it reads:

```
       Define an executable component named 'myexe' in a dune file in the
       current directory:

                 dune init exe myexe
```

I prefer option 2, as it keeps the CLI more uniform across components. I'll plan to fix things in that way, unless I hear opinions otherwise.
