### ISSUE TITLE
generate_opam_files: pin-depends

### ISSUE THREAD

**Issue by vogler** [ocaml/dune#3231]
`generate_opam_files` ([doc](https://dune.readthedocs.io/en/stable/opam.html#generating-opam-files)) has no `pin-depends` field, which would be nice to have.
Putting it in `pkg.opam.template` works, but it would be better to have everything in `dune-project`.

**Comment by rgrinberg** [comment]
This is something that was intentionally omitted. Ephemeral information such as where to fetch the package is not part of package metadata as dune defines. IMO, opam mixing this information together is a mistake and I'd like to not repeat it in dune.

**Comment by vogler** [comment]
I use it to specify another self-owned dependency without having to release a version in opam for every change and without having to include its source in the same project.
Is there an alternative for that use case?

**Comment by rgrinberg** [comment]
If you aren’t releasing to opam, you don’t really need an opam file. If you insist on using pins, consider using git submodules or just writing your opam file.

**Comment by vogler** [comment]
It's also released to opam, just not every change. `pin-depends` is generated via `pkg.opam.template`, I can stick with that.
Git submodule as `vendored_dirs` works as well. I was a bit put off by the idea that `dune clean`/`dune build` then also apply to the subproject and to any (even uncommitted) change, but that can be avoided by working in another checkout of the sub-repo.

**Comment by NightBlues** [comment]
> If you aren’t releasing to opam, you don’t really need an opam file. If you insist on using pins, consider using git submodules or just writing your opam file.

@rgrinberg if you have a workspace with multiple projects depending on each other, you have to use public_name stanza (as described in docs), but dune forces you to create project.opam file to allow public_name stanza

**Comment by cdaringe** [comment]
> If you aren’t releasing to opam, you don’t really need an opam file

while true, there isn't a standard format to declare a project's dependencies otherwise. `.opam` is the defacto mechanism to declare required dependencies for a project, regardless of publishing or not.

> Ephemeral information such as where to fetch the package is not part of package metadata as dune defines

This statement was surprising to me. `generate_opam_files` is all about producing for the `opam` data model. It seems to me that `generate_opam_files` should be minimally the inclusive set of opam fields, a superset if dune wants to extend it, or none at all. `dune` picking and choosing which parts of the opam spec it likes & dislikes creates a hidden implicit model, which currently is unknown to users. Perhaps [calling out that the full opam model is not supported with a big warning](https://dune.readthedocs.io/en/stable/opam.html#generating-opam-files) is worthwhile?  i had expectations of opam compatibility based on the docs. after adoption & usage of the feature, i feel mislead having now learned that the data model is some-kindof-unknown subset.

not critiquing, just sharing experience.

> If you insist on using pins, ... or just writing your opam file.

- I think we'd all agree using pins _stinks_. I don't think anyone ever _wants_ to do it. It's just a required flow for certain cases. i haven't started an ocaml project yet where i didn't need a pin, at least during the exploration phase. currently, I'm trying to experiment with a [jsoo-react](https://github.com/jchavarri/jsoo-react#existing-project), which explicitly calls for pinning. anytime i make a change to my project, I want to ensure that it is rapidly and easily reproducible elsewhere. this means updating a dependency declaration. this transitively means updating my dune-project, which transitively means updating my opam file. thus, pinning is a project management requirement, and `.opam` is the place to do it :/

- writing your own opam file is certainly an option. i will probably take this option. however, dune should consider outright removing generation support if it cannot reflect the opam model. i really want `dune` to be the place for this though. the fewer tools i need to engage with for managing my ocaml projects the better.
- i strongly challenge the suggestion that opam mixing installation source metadata is a mistake. `opam`'s role is to install dependencies into an environment. package location is just another input to that core functionality, which just by happenstance is configured with sensible defaults, pointing to the formal public repository. most adjacent programming communities let you specify the registry to install from with their associated dependency tools. [py](https://github.com/pypa/pip/pull/4175), [npm](https://docs.npmjs.com/cli/v7/using-npm/registry), [cargo](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-other-registries), java tools like gradle let you partition your dependency sources as well. dune claiming "this is a bad practice" i think is not considering the diverse set of ways developers use ocaml tools.
