### ISSUE TITLE
dune build freezes with cache enabled

### ISSUE THREAD

**Issue by artempyanykh** [ocaml/dune#3233]
## Expected Behavior

`dune build` finishes

## Actual Behavior

`dune build` freezes.

## Reproduction

I've added `(cache enabled)` to `~/.config/dune/config`.

Then setup infer [Infer](https://github.com/facebook/infer) with `./configure && make`.

Then under `infer/src` I ran `dune cache start --foreground` in one terminal and `dune build` in the other.

`dune cache` output is

```
# accept client: 127.0.0.1:49327
# 127.0.0.1:49327: received command: (set-build-root /Users/arr/infer/infer/src/_build)
# 127.0.0.1:49327: ended
```

At the same time `dtruss` on `dune build` process shows a bunch of:
```
select(0x0, 0x0, 0x0, 0x0, 0x70000CA20F90)               = 0 0
```
which is very weird -- basically, `dune build` does polling on 0 file descriptors.

## Specifications

- Version of `dune` (output of `dune --version`): 2.3.1
- Version of `ocaml` (output of `ocamlc --version`): 4.08.1
- Operating system (distribution and version): MacOS 10.15.3

**Comment by artempyanykh** [comment]
I also tried the same steps on CentOS 7.6 and everything worked just fine. Seems like it might be MacOS specific problem.

**Comment by diml** [comment]
/cc @mefyl 

The select is probably from the OCaml ticker thread.

**Comment by mefyl** [comment]
This might be the same as https://github.com/ocaml/dune/issues/2973. I haven't been able to look into this because I must get my hands on a Mac.

Normally, once the client closes the connection (as we can see in the daemon logs), the daemon will shutdown (2) the socket, and the client read should terminate gracefully with an EOF - unless that's a wrong non-POSIX Linux centric assumptions, but I don't think so. Here it seems the clients stays stuck forever on the read, despite the TCP shutdown.

A workaround would be to send an end message to force the client to quit, but it pains me to deteriorate and complexify the code like that. If that's a glitch in the Ocaml TCP bindings on OSX, it would be great to catch it too.

I'll try my best to find a Mac, or if someone with OSX wants to look into it I'm happy to help in any  way.

**Comment by artempyanykh** [comment]
@mefyl thanks for you reply! 

I've found a change that fixes the freeze on MacOS, and also makes cache-trimming tests pass. I need to check that it doesn't break anything on Linux. Will do it sometime on Monday.

**Comment by artempyanykh** [comment]
@mefyl submitted a PR #3249 . The change is like a couple lines, so should be a quick review.
