### ISSUE TITLE
`dune fmt` command suggestion to run ocamlformat when installed

### ISSUE THREAD

**Issue by XVilka** [ocaml/dune#3244]
Sorry if it is a duplicate. I remember it was discussed somewhere, but not in the GitHub, so opening this issue to clarify the feature request.

## Desired Behavior

Idea to provide exactly the similar feature to Rust `cargo fmt` when `rustfmt` is installed.
https://github.com/rust-lang/rustfmt#on-the-stable-toolchain

## Example

1. `dune fmt` to run reformat of the whole dune project (akin to `cargo fmt`
2. `dune fmt -- --check` to check if there will be differences after running formatter (akin to `cargo fmt -- --check`)

**Comment by XVilka** [comment]
Sorry, a duplicate of https://github.com/ocaml/dune/issues/3170

**Comment by XVilka** [comment]
Nevermind, it's different - it was speaking about the reformatting OCaml code, not the dune files themselves.

**Comment by rgrinberg** [comment]
fmt formats both dune files and OCaml source. I don't think there should be a distinction here.

Adding `$ dune fmt` sounds fine to me I suppose. We already have `runtest`, so I don't see anything wrong with it.

@shonfeder @emillon what do you think?

**Comment by emillon** [comment]
Yes, I agree that a high level command to drive the formatter is very useful. It was part of the initial plan. And as you said in #3170, it should hide the diff.

At the moment, hooking formatters to editors is also a bit clunky: since `ocamlformat` is directly called by the editor, it has to walk the filesystem to find the config file, find whether this file is disabled, etc. Dune already knows most of this.

So I'd like to make sure that we can use `dune fmt` directly in `neoformat`, `emacs` and ocaml-lsp rather than the individual formatters. This will also make sure that formatting for dialects will work out of the box.

I think that this require a way to run the formatter without hooking their output to promotion. So probably that `dune fmt` would not be a strict alias to `dune build @fmt`. Do you see what I mean?

**Comment by rgrinberg** [comment]
> So I'd like to make sure that we can use dune fmt directly in neoformat, emacs and ocaml-lsp rather than the individual formatters. This will also make sure that formatting for dialects will work out of the box.

Why bother with editor specific backends? Both vim & emacs have fully functional lsp clients. So I think it would be best to optimize `$ dune fmt` for batch formatting in the command line.

> I think that this require a way to run the formatter without hooking their output to promotion. So probably that dune fmt would not be a strict alias to dune build @fmt. Do you see what I mean?

At first I would accept `$ dune fmt` to be roughly equivalent to `$ dune build @fmt --auto-promote` with the diff hidden. If we want to extend it with further functionality such as formatting individual files, that could also be done.

**Comment by emillon** [comment]
Hmm, yes I got things backwards with LSP/dune integration.

So I think I agree with your plan!

The only point I'm wondering about is what LSP will use to format a particular file. I think dune needs to be involved because it knows about the configuration; but I don't think formatting in an editor should change the state of the build system, so it should bypass promotion.

**Comment by rgrinberg** [comment]
We now have a `dune fmt` command. Please create issues for concrete suggestions on how to improve it.
