### ISSUE TITLE
`(copy#` should add entry to `.merlin`.

### ISSUE THREAD

**Issue by jordwalke** [ocaml/dune#3266]
`(copy_files#` ensures that an entry is added to the generated `.merlin`, but `(copy#` does not. I believe `(copy#` should behave like `(copy_files#` and ensure there is a `S` source directive in the generated merlin file.

**Comment by diml** [comment]
It's a bit more complicated for `copy#` because they can be nested deep inside actions.

@trefis @let-def, are these `S` directives needed at all in the case of `copy_files#/copy#` BTW? Looking at the merlin doc,  my understanding is that they are needed when the .ml/.mli files are scattered in several directories. However, in the case of `copy_files#` or `copy#`, there will be a file in one of the specified source directory pointing to the remote file via a line directive.

**Comment by jordwalke** [comment]
@diml This was definitely needed in my case. That's why I had to use several several `copy_files#` - one for each file (the glob pattern was the file path). Without it, merlin would not find the right locations when jumping to location etc. Since `copy#` didn't ensure an entry was added I had to use `copy_files#` or merlin wouldn't work correctly.

**Comment by diml** [comment]
I see. Basically, it seems ad-hoc to me that dune has to produce such lines in the `.merlin` in response to `copy_files#` stanzas, and the code to do that for `copy#` would be even more ad-hoc. So I'm wondering if there is not something we can change in merlin so that this is not needed.

**Comment by diml** [comment]
@voodoos had a look at the merlin side of things and we convinced ourselves that generating `S` lines for `copy_files#` was necessary. What I had in mind would amount to merlin doing some sort of "copy detection" rather than having dune tell merlin about the copies.

Regarding `copy#` producing `S` lines as well, I suppose it could make sense but it would complicate the code more than it is worth. So let's say it is a known limitation.

BTW, note that you can also use a single `copy_files#`:

```
(copy_files# dir/{file1,file2,...})
```

It is better than say, a single rule with multiple `copy#` such as:

```
(rule
 (progn
  (copy# ...)
  (copy# ...)))
```

given that with `copy_files#` the files will be updated independently while in the second case they will all be updated as a block when any of them changes.
