### ISSUE TITLE
Install .merlin files

### ISSUE THREAD

**Issue by copy** [ocaml/dune#3276]
## Desired Behavior

dune should install .merlin files so that jump to definition works from files installed in `~/.opam/…/lib`.

## Example

- Open `~/.opam/4.10.0/lib/core_kernel/list.ml` in vim/emacs with merlin
- Try MerlinLocate on any module

**Comment by DouglasGray** [comment]
Just to illustrate where this might be useful with an example, if I have the below in a file in my Dune project:

`(* my_project_file.ml *)`
`let _ = Async.with_timeout`

Then I can jump to `Async.with_timeout` ok. However it turns out this definition is re-exported and defined as:

`(* async_unix.ml *)`
`let with_timeout = Clock.with_timeout`

And jumping directly to `Clock.with_timeout` is not currently possible, though it would be very handy.

**Comment by diml** [comment]
That's a valid request, however it seems to me that the information contained in these .merlin files would simply duplicate the one available in `META` and `dune-package` files.

Since there is a work in progress (https://github.com/ocaml/RFCs/pull/7) to standardise the way libraries are installed and the way library dependencies are stored, it seems to me that we should just wait for that.

**Comment by ygrek** [comment]
installing .merlin files sounds like a quick fix without any downsides that works immediately without any large-scale changes to the infrastructure?

**Comment by rgrinberg** [comment]
> installing .merlin files sounds like a quick fix without any downsides that works immediately without any large-scale changes to the infrastructure?

Not quite. We'll need to generate a separate set of merlin files that don't refer to directories in _build. If you'd like to work on that as a temporary stop gap, you're welcome to do it. I'd prefer to work on a longer term solution with our limited resources.

**Comment by diml** [comment]
I thought a bit more about this. To make this a general feature, we'd need to handle ppx rewriters and other preprocessors. More generally, we'd need to setup install directories so that they can be built from source. Not only this is not currently their purpose, but it also opens the door to a stream of complications I'm not particularly excited about.

For this reason, dune will not install .merlin files.

However, it is very easy with dune to "drop" the sources of your dependencies in your workspace. And in this case, merlin will work well on your dependencies. I believe esy also support installing the `_build` directory for the exact same purpose. That might be another direction to look at.

**Comment by ddickstein** [comment]
> However, it is very easy with dune to "drop" the sources of your dependencies in your workspace. And in this case, merlin will work well on your dependencies.
Can you give a full example of how this works? This sounds like the vendoring approach lindig mentioned here https://discuss.ocaml.org/t/merlin-goto-definition-inside-installed-libraries/2788/14 but I have found no luck getting this configured properly with merlin despite many attempts.

> I believe esy also support installing the _build directory for the exact same purpose. That might be another direction to look at.
I'm not sure what this means. Can you elaborate?

**Comment by diml** [comment]
> Can you give a full example of how this works? This sounds like the vendoring approach lindig mentioned here https://discuss.ocaml.org/t/merlin-goto-definition-inside-installed-libraries/2788/14 but I have found no luck getting this configured properly with merlin despite many attempts.

For instance, if you are using library `foo` from package `foo` at version `1.42` (installed via opam), you can do this:

```
$ touch dune-workspace # to mark the root of the workspace
$ git clone <my-repo>
$ opam source foo.1.42
```

and then dune will build and use the local `foo` rather than the one installed via opam. You can repeat the `opam source` command for all dependencies for which you want to explore the source code. The [duniverse tool](https://github.com/ocamllabs/duniverse) will automate this, however this tool is not yet released so you'd be a tester.

> I'm not sure what this means. Can you elaborate?

Neither am I. I only heard about this from someone.

**Comment by ddickstein** [comment]
I've tried using `opam source` but I run into issues every time I try to get it working with Core/Core_kernel/Base. I elaborated on it [here](https://discuss.ocaml.org/t/merlin-goto-definition-inside-installed-libraries/2788/11?u=ddickstein), which might be a better place to continue the discussion.

**Comment by diml** [comment]
Ok. I have got it to work in the past. If you have a minimal reproduction case, we can look into it. BTW, there is also the [duniverse tool](https://github.com/ocamllabs/duniverse) which will hopefully make all this easier.
