### ISSUE TITLE
dune-build-info transitively used from ppx rewriter

### ISSUE THREAD

**Issue by xclerc** [ocaml/dune#3336]
(note: I am not sure the use case below is supposed to be supported, as the documentation states that build info can be embedded in executables, but does not explicitly mention whether it can be embedded in libraries.)

## Expected Behavior
Define a library depending on `dune-build-info` and have a ppx rewriter depending on said library.

## Actual Behavior
Dune fails with:
```
File ".ppx/98cd9c27bc47def1a842c7a721af4e6b/_ppx.ml", line 1:
Error: No implementations provided for the following modules:
         Build_info__Build_info_data referenced from /Users/xclerc/.opam/4.10.0/lib/dune-build-info/build_info.cmxa(Build_info)
```

## Reproduction

[repro.zip](https://github.com/ocaml/dune/files/4440231/repro.zip)

## Specifications

- Version of `dune` (output of `dune --version`): 2.4.0
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): macOS

**Comment by diml** [comment]
Well, the build info are not filled during the build process. I.e. we just leave a blank in the executable and rewrite it at install time. So if we supported this, the lib would report dummy values. Though we could still support it just to avoid this error and so that you can use a library that depends on dune-build-info in a ppx.

**Comment by xclerc** [comment]
Sorry, I am a bit confused: it looks like executables in the `_build`
directory do contain *e.g.* the version. I am pretty sure I have
seen it working for an executable depending on a library itself
depending on `dune-build-info`.

**Comment by diml** [comment]
Only if it is known statically, i.e. if you are building from a release tarball. If the version comes from git, it will be left blank inside `_build`.

**Comment by xclerc** [comment]
Thanks for the clarification.

**Comment by diml** [comment]
Do you want to take a look at this BTW?

**Comment by xclerc** [comment]
I am afraid my knowledge of dune's code base is wildly outdated...

**Comment by rgrinberg** [comment]
I think that this issue is caused by the fact that we don't handle link time code gen when build ppx exe's.

@jeremiedimino I recall you explained to me once why we had a separate compilation pipeline for ppx drivers instead of reusing `Exe`, but I wasn't entirely convinced. Do you mind explaining again? `Exe` would handle link time code gen for us.

**Comment by jeremiedimino** [comment]
I can't remember either.
