### ISSUE TITLE
Pass flags to ocamlc from command line

### ISSUE THREAD

**Issue by balsoft** [ocaml/dune#3337]
## Desired Behavior

Sometimes, editing `dune` files might be inconvenient, but one might still want to conditionally pass some flags to the compiler (e.g. pass flags only when building executables)

## Example

We're packaging some OCaml software that uses `dune` with `nix`. Among other things, we're interested in getting statically linked executables.

Currently, this requires awkward patches ([1](https://gitlab.com/ligolang/ligo/-/blob/f95be416f689d99054ace92a3a44d6088dcacf00/nix/static.patch), [2](https://github.com/serokell/tezos-packaging/blob/master/nix/fix-master.patch)), which is clearly sub-optimal, especially for projects with a lot of executables. Hence, it would be nice to have a way to pass flags to the compiler without editing any files. I'm not sure about implementation details.

EDIT: I have just noticed the following in the documentation:
> The default value for (flags ...) is taken from the environment

Maybe I'm missing something and there is a way to pass flags to ocamlc?

**Comment by jberdine** [comment]
Not specific to dune, but would setting `OCAMLPARAM` work for you? See https://caml.inria.fr/pub/docs/manual-ocaml/comp.html .

**Comment by balsoft** [comment]
Wow, thanks for the quick reply @jberdine ! I'll look into it.

**Comment by balsoft** [comment]
@jberdine While it technically answers my question, it doesn't actually work for my use-case. The reason is that I want those flags to apply only to executables and not libraries.

Thanks for the suggestion, though.

**Comment by diml** [comment]
If you want this to be applied everywhere, have you considered patching the compiler directly? Or setting the right ./configure option.

**Comment by balsoft** [comment]
On the contrary, I would like to be able to only pass certain flags for executables or libraries, not for everything.

**Comment by diml** [comment]
How would this work from the command line? More precisely, how would you tell dune to apply certain flags to one executable, and some other flags to another executable?

**Comment by balsoft** [comment]
I envision it like this: `--flags-$EXECUTABLE_NAME="-ccopt -static -cclib -ludev"`

**Comment by diml** [comment]
So you would still need to maintain a list of `(executable * flags)`. How is that better to maintaining a patch?

**Comment by balsoft** [comment]
That list can be easily generated from nix, for example, or with some other language. Generating a list of correct patches would be almost impossible without an sexp parser and a lot of other work that would essentially reimplement a chunk of dune, so I figured it would be easier to implement this feature in dune directly.

**Comment by diml** [comment]
I see.  The command line argument feels a bit ad-hoc to me, and opens the door to adding more such ad-hoc command line arguments in the future, which would make the cli of dune more complicated.

I have another suggestion. The [sexp tool](https://github.com/janestreet/sexp) provides a general DSL for querying and editing s-expressions. It won't work on dune files because the format is a bit different, but we could follow the same idea and provide a DSL for editing dune files. Or even just an OCaml API, which would be a lot more powerful. FTR, we do exactly this inside Jane Street when we open-source our code. Our internal `dune` files (that are still called `jbuild`) need to edited to work in the open source word. We rewrite them on the fly using a simple program that only operates at the s-expression layer and doesn't know the grammar of dune file. This work pretty well, which makes me confident such an approach would work here as well.

**Comment by balsoft** [comment]
That would mostly solve my problem, yes.

**Comment by emillon** [comment]
To summarize the discussion, it was agreed that CLI options are too ad-hoc. The mapping can be done directly by editing the dune files, either using a patch or `sexp`. In addition, I'll mention that `(env)` stanzas with the right flags can be added in the directories where executables are defined.
Please reopen if something concrete should be done in dune. Thanks!
