### ISSUE TITLE
version reported in the dune-project file is too high

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#3411]
## Expected Behavior

Fill in the lowest acceptable dune version number, rather than the current dune version number.

I.e. make the dune version constraint as easy to satisfy as possible.

## Actual Behavior

The current dune version is put into that file.

## Reproduction

Call
```
dune build @all
```

In a project without a dune-project file.

## Specifications

- Version of `dune` (output of `dune --version`): 2.5.0
- Version of `ocaml` (output of `ocamlc --version`) 4.08.1
- Operating system (distribution and version): Linux

**Comment by rgrinberg** [comment]
Are you able to reproduce it with 2.5.1?

**Comment by UnixJunkie** [comment]
Yes, same behavior.

**Comment by UnixJunkie** [comment]
The dune-project file created:
```
(lang dune 2.5)
(name hts_shrink)
```
While, I suspect the given project can compiles with much older dune versions.
The src/dune file:
```
(executables
  (names        mop2d_indexer mop2d_encoder dscan)
  (public_names hts_shrink_index hts_shrink_encode hts_shrink_dbbad)
  (libraries batteries dolog parmap minicli bitv bst parany))
```

**Comment by diml** [comment]
That's the expected behaviour. Dune "remembers" what version of Dune you are using by writing it down when creating the `dune-project` for the first time.

Additionally, Dune will never mutate an existing `dune-project` file by itself. So if it would set an older version when creating the file, then the user would have to go and modify the file when they start using newer feature. That doesn't feel right, if the user didn't explicitly specify a version of the language, then they should get all the features the software currently supports.

**Comment by rgrinberg** [comment]
Looks like I misread the bug report, and thought it was related to the dune-package reading problems we've had.

**Comment by UnixJunkie** [comment]
@diml This is not nice in terms of opam packaging:
if the user has to search by hand what is the oldest version of dune that is required
in order to build the project, this is inconvenient.
The lower the dune version required to build a package, the more other opam packages it can co-install with.

**Comment by UnixJunkie** [comment]
cc @kit-ty-kate this is the kind of things that make me want to remove the dune-project file
from all my source trees.

**Comment by kit-ty-kate** [comment]
Can this issue be reopened? I know it's not the first time this issue is brought up in this bug tracker and there is obviously a disparity between what users expects and what dune does, regardless of whether this is the right thing to do or if it requires to much work to do. Can there be a more in depth discussion?

**Comment by avsm** [comment]
Hi @UnixJunkie, dune tries very hard to maintain backwards compatibility across minor releases.  Looking through the opam-repository, I can only find a single package (gopcaml-mode) that has an upper bound on dune < 2.5, and lwt-pipeline that has a speculative upper bound on dune<3.0.0.

All the rest either have no upper bound, or are constrained for dune < 2.0 which was a major release.

So I just wanted to find out if you had a concrete example for this part of your report:
> The lower the dune version required to build a package, the more other opam packages it can co-install with.

The current policy is quite simple (just depend on the latest dune minor revision that you built the project with), and upper bounds can be reserved for major dune releases like dune 2.0 or dune 3.0.

**Comment by Et7f3** [comment]
gopcaml-mode have lifted this constraints in the repo.

**Comment by UnixJunkie** [comment]
@avsm the problem I see is not with upper bounds.
I see a problem with lower bounds:
package A wants dune >= 1.0.
Package B wants dune >= 2.0.
Package A is already installed but now the user wants to install package B.
This triggers an update of dune, while if the dune bound on B was lower,
B could be installed right away.
In the worst case, having forced the update of dune may even break the compilation of A.
I just feel that the dune version inserted by dune in the dune-project file is unnecessarily high.
Maybe this is just a small problem.
Maybe, this means that when we put a package in opam we should disregard the dune
version in the dune-project file and just find out by testing all major dune versions to find the smallest one that succeeds in compiling the package.
But, this is a little cumbersome for people who add packages into opam-repository.

**Comment by rgrinberg** [comment]
> Can this issue be reopened? I know it's not the first time this issue is brought up in this bug tracker and there is obviously a disparity between what users expects and what dune does, regardless of whether this is the right thing to do or if it requires to much work to do. Can there be a more in depth discussion?

For now, this seems like something that would consume a lot of developer time, and the benefits would don't seem tangible enough to justify it. Therefore, I'd like to hear from other users that find the current mechanism to be confusing.

Besides, if dune was to infer an older version automatically, I expect we'd get complaints like:

* why is down generating bad opam files?
* why is dune not checking for this error?
* why is dune not formatting the dune files as it should?

That's because these kinds of checks are also versioned as well, and the most recent version of dune is the one that is guaranteed to give the best behavior to each of those points.

**Comment by UnixJunkie** [comment]
Well, now I understand that:
the dune version in the dune-project file is not what we should use in opam-repository
as the lower bound on the dune version in an opam package.
Which is good to know.

**Comment by jeremiedimino** [comment]
If you have `(lang dune x.y)` in your `dune-project` file, then any dune < x.y will refuse to build your project. So you definitely need a constraint of the form `"dune" {>= x.y}` in your `dune-project` file. That is the constraint dune generates by default if you let `dune` generate your opam files.
