### ISSUE TITLE
Better support for C++

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#3528]
Right now, OCaml uses the compiler specified in the `c_compiler` field of `ocamlc -config` to compile C++ sources. We rely on the C compiler detecting the `.cpp` extension to decide that the language is C++. This works ok with `gcc`, but doesn't work so well with other C compilers such as clang.

As a result, people who are compiling C++ stubs with Dune have to manually add `-x c++ -lstdc++` to their compilation flags, which is not ideal. Instead, we would like Dune to do this automatically. Since the flags are not the same for all C compilers, we will need to construct a small database with the flags for various well-known C compilers.

**Comment by voodoos** [comment]
Do you think these flags should be added to the `:standard` set or systematically prepended to the cxx compiler call ?

**Comment by jeremiedimino** [comment]
Systematically prepended. This flags seems like part of the basic behaviour, i.e. turning the C compiler into a C++ one.

**Comment by voodoos** [comment]
A first survey of the flags that dune could add by itself:

Compiler | C++ flags | Notes
-|-|-
gcc | `-x c++ -lstdc++` | *The G++ driver automatically adds `-shared-libgcc` whenever you build a shared library or a main executable*. Is that something we should do too ?
clang | `-x c++` | *`-stdlib=<library>` Specifies the C++ standard library to use; supported options are libstdc++ and libc++. If not specified, platform default will be used.*
msvc |`/TP` | The specification of the output target is a bit different: `/Fo`

Am I missing any major compiler ? Cygwin-gcc / Mingw should accept the same options as gcc.

Also, `ocamlc -config` sometimes only identifies the c compiler as `cc` which could be a link to various compilers. (On my mac a link to clang). What should we do in that case ? Resolve the symlink ?

**Comment by jeremiedimino** [comment]
@dra27 or @avsm do you have an opinion on these questions?

My intuition is:
- add `-shared-libgcc` when building shared libraries with gcc
- don't pass `-stdlib=...` when using clang

Follow the `cc` symlink to decide whether it is clang or gcc.

**Comment by dra27** [comment]
A few thoughts:

- Dune should be opinionated and trigger this for when the source file ends `.cpp` - i.e. the file name (or the stanza?!) says it's C++, and Dune then does what's necessary to ensure the C compiler is invoked as a C++ compiler. This would make `/TP` unnecessary for MSVC.
- `-shared-libgcc` should be used for C++ yes, or exceptions don't work across shared libraries. Agree for Clang that `-stdlib` should not be used if there's an expected default. I'm not sure what happens if you use `-shared-libgcc -static` - i.e. it should be probably be possible to override it (there's some weirdness with this with ocaml-mccs, for example, but I can't right now remember the exact details)
- Isn't probing the binary more reliable than reading the symlink? (i.e. reading `cc --version` or equivalent) to determine the compiler flavour. Regardless, if Dune would benefit from knowing the precise flavour of the compiler, then it would be worth an upstream PR for OCaml to include it in `-config` (OCaml determines it during `configure` - it's essentially extra information on top of ccomp_type).

**Comment by jeremiedimino** [comment]
> Isn't probing the binary more reliable than reading the symlink? (i.e. reading cc --version or equivalent) to determine the compiler flavour. Regardless, if Dune would benefit from knowing the precise flavour of the compiler, then it would be worth an upstream PR for OCaml to include it in -config (OCaml determines it during configure - it's essentially extra information on top of ccomp_type).

@dra27, we discussed these points with @voodoos yesterday. Regarding changing the configure script, our thinking is that it would be quite a lot more work than we anticipated for this feature, making the ratio work/benefit less worth it. Additionally, we would need a story for older OCaml compilers anyway. So for now we plan to stick to doing this in Dune only, which will be enough for solving the original problem.

Regarding probing binary, agreed that this feels more reliable. At the same time it is a bigger change as well as we need to turn a static value into a dynamic one, and from what we know checking the binary name seems enough. Do you have existing cases in mind where this would break?

**Comment by dra27** [comment]
Reading the symlink might go wrong on Windows (there’s an open issue for absolute symlinks), but it’s only theoretical - I don’t know of any issues with this, indeed
