### ISSUE TITLE
dune cache trim fails when upgading from dune 2.5 to 2.6

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/dune#3542]
## Description of the issue
Using dune cache with dune 2.5.1, then upgrading to dune 2.6.0 and calling `dune cache trim` gives me the following error message and fails:
```
Error: Unexpected directories found at the cache root:
- /home/opam/.cache/dune/db/v2
These directories are probably used by Dune of a different version. Please
trim the cache manually.
```
This is because the cache layout changed and thus the directory changed from `db/v2` to `db/v3` and `dune cache trim` doesn't know if the user intend to also use the old version of the cache later.

My use case is that I'm using the dune cache in CI (specifically https://github.com/kit-ty-kate/opam-health-check) and it is rather hard for CI systems to do manual tasks like removing old cache directories.

## Proposed solution
I've talked with @snowleopard and we agreed that having a new argument to `dune cache trim` (that could be named `--force` or `--remove-deprecated` for instance) could be a solution. This new argument would make the command clean old layouts without asking. If this happens, a note could be displayed in the console so that users are not surprised.

**Comment by avsm** [comment]
Given that the database seems to be versioned `/home/opam/.cache/dune/db/v2`, why not just bump the version number to generate a new cache for every dune release?  Sharing the cache across dune versions seems fairly impractical anyway, as the rules will change across releases.

**Comment by jeremiedimino** [comment]
@avsm if the rule change the keys will change. In general, I'd expect quite a lot to be shareable between releases.

**Comment by snowleopard** [comment]
> why not just bump the version number to generate a new cache for every dune release? 

@avsm Generating a new cache is not a problem by itself. The problem is that it's not obvious for the trimmer what to do with cache entries created by Dune of a different version. It doesn't seem worth it to overcomplicate the trimmer and make it support all cache format versions. Right now the trimmer just takes a conservative approach of just refusing to trim, which seems too conservative and is annoying in the CI context. So, having a flag that tells the trimmer that it is OK to just nuke all unfamiliar caches from the Dune cache directory seems like a good idea.

**Comment by snowleopard** [comment]
@jeremiedimino, @aalekseyev and I just had a chat and we thought that perhaps implementing the Right Thing, i.e. uniform trimming of new and old cache entries, would be a better way forward because it would allow us to get rid of the new flag. It's a bit more work but not too difficult, so I guess I'll go this way.

**Comment by kit-ty-kate** [comment]
sounds amazing! Thanks a lot!

**Comment by snowleopard** [comment]
In #4047, I've implemented the uniform trimming of Dune cache, as discussed. Dune will no longer be complaining about old versions of the cache after upgrading, but will trim their entries in the same way as entries of the new cache.
