### ISSUE TITLE
dune cache fails if an empty port file is present

### ISSUE THREAD

**Issue by avsm** [ocaml/dune#3564]
This Dockerfile exhibits the problem:

```
FROM alpine:3.12
RUN apk add --update musl-dev gcc g++ make git ocaml ocaml-compiler-libs ocaml-dev
RUN git clone git://github.com/ocaml/dune /src
WORKDIR /src
RUN make release && make install
RUN mkdir /bug
WORKDIR /bug
RUN echo "(executable (name foo))" > dune
RUN touch foo.ml
RUN dune build
ENV DUNE_CACHE=enabled
RUN dune build
RUN dune build || true
RUN rm -f /root/.cache/dune/db/runtime/dune-cache-daemon/port
RUN dune build
RUN dune build
```

When run, the second dune build will fail:

```
Step 16/16 : RUN dune build
 ---> Running in 469c874adad4
Error: invalid endpoint: 
The command '/bin/sh -c dune build' returned a non-zero code: 1
```

This is because the `.cache/dune/db/runtime/dune-cache-daemon/port` is a zero length file, and so `dune cache start` just prints out an empty line.

A couple of things looking at the code: the cache_manager seems to have more sophisticated checks for the port file, but that function isn't used in the main dune binary.  Also, the dune client binary seems to deliberately truncate this port file to 0-length unconditionally.  So this makes me wonder why this works reliably outside of Docker...

**Comment by mefyl** [comment]
Finally looking at this. I can confirm the empty port file is intended. The daemon holds a filesystem lock on the port file to ensure only one instance is ever running. If the file is not locked, a new instance should be started. The file is truncated on exit so that it doesn't hold stale information about an endpoint and the issue is a bit clearer in case of shenanigans - which is exactly the case here.

The unfortunate part is that the dockerfile works as intended for me: the second run locks the file, creates a new instance and fills up the endpoint:

```
Step 15/16 : RUN dune build
 ---> Running in 013e46bf09c5
Removing intermediate container 013e46bf09c5
 ---> 5e6e18fb8db3
Step 16/16 : RUN dune build
 ---> Running in d0b3becbbd86
Removing intermediate container d0b3becbbd86
 ---> 6288c986ba92
Successfully built 6288c986ba92
```

I just did a thorough review of that code and can't find any possible race conditions, provided that fcntl advisory file locking provides the same guarantees. All the magic is in `stdune/daemonize.ml`. Could you check if you can still reproduce ? Maybe it was accidentally fixed.

**Comment by rgrinberg** [comment]
I believe this is no longer a problem since the cache daemon is gone.
