### ISSUE TITLE
Linking order: foreign libraries should be passed as late as possible on the command-line

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#3640]
I have a stanza of the form
```
(executable
 (name fastmath_unit_test)
 (foreign_archives ../intel/intelmath
                   fastmath)
 (foreign_stubs
  (language c)
  (include_dirs ../bindings)
  (names fastmath-caml))
 (modules fastmath fastmath_unit_test))
```
where `fastmath-caml` contains references to functions defined in one of the foreign libraries, `fastmath`. The linking step fails due to undefined references to these functions (under Linux). As far as I can see it is due because in the linking step, `libfastmath.a` appears before than `fastmath-caml.o` in the command-line and the GNU linker discards any symbol from `libfastmath.a` that is not needed *when it sees the archive*.

To avoid this problem, I think it would be a good idea to pass foreign libraries as late as possible in the command line. The relevant code seems to be https://github.com/ocaml/dune/blob/a58aa6ea03f7e157694f5e46e588771503c58f46/src/dune/exe.ml#L155-L176
(where the foreign libraries are passed in `link_args` and the foreign stubs in `o_files`).

cc @snowleopard

**Comment by snowleopard** [comment]
@nojb Thanks for explaining the issue so clearly and identifying a possible solution! What you suggest seems right to me: indeed, by passing foreign archives at the end of the linking command line we can ensure that previously requested symbols are not dropped by the linker.

I guess we don't have any tests where symbols from a foreign archive are referred from foreign code, and this use case may be rare, which is why we never noticed this problem before.

We should add a test for this and make sure that moving `link_args` to the end makes the test pass.

Would you like to implement the suggested fix? I'm happy to review it.
