### ISSUE TITLE
[coqdoc] Add a flag to keep .glob files

### ISSUE THREAD

**Issue by yannl35133** [ocaml/dune#3693]
I am trying to use dune with my coq project. As it is quite simple, the options already available are enough for me right now.
However, I am now trying to compile my documentation, and I run into a problem:
I can write a rule to run coqdoc on my `.v` files, but the `coq.theories` stanza has no flag (or other way) to keep the `.glob` files necessary.

As this seems like an easy fix, could you implement it before trying to achieve "1.0 for Coq support"?

If this would lead to too much trouble regarding forward compatibility, is there a simple translation for the `coq.theories` stanza into a `rule` stanza (I only use the name attribute) so that I can fix my problem at least?

**Comment by yannl35133** [comment]
It seems that, when no errors occur, the `.glob` files are in fact conserved, so I don't have a problem anymore.

**Comment by yannl35133** [comment]
Ok, I think I understand what happens now: for the first build, dune keeps everything.
For the second build, it deletes everything that is not the "supposed" output of coqc (all .vos, .vok, .aux and .glob files).

This is therefore easily mitigated, but still something to address at some point I think.

**Comment by jeremiedimino** [comment]
Assigning to @ejgallego since it's coq related. However, the scope here is wider than coq. The same situation exist in OCaml with `.s` files for instance.

FTR, someone at Jane Street emitted the idea that for such auxiliary file, we could have an editor binding to have the auxiliary contents pop up in a buffer. Which seems like a good user experience. In this case, we could design such features in a similar way to the way merlin works: dune communicates the various compilation flags to the outside tool that then does what it needs outside of Dune.

**Comment by rgrinberg** [comment]
Which rules produce .glob files? Sorry I'm not familiar with the coq build process very much.

> I can write a rule to run coqdoc on my .v files, but the coq.theories stanza has no flag (or other way) to keep the .glob files necessary.

Seems like it would make sense to add first class `coqdoc` rules to dune. Then users would only need to run `dune build @coq-doc` to get the documentation they need.

**Comment by rgrinberg** [comment]
Solved in master. Fix should be released in 2.7.1
