### ISSUE TITLE
Splitting the dune library

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/dune#3703]
We are currently working on splitting the `dune` library that contains both the core engine of Dune as well as all the build rules into:

- an `engine` library
- a `build_api` library
- a `build_rulles` library

Which will both clarify the code base and help with the plan to move from Jenga to Dune inside Jane Street.

The `engine` library should contain nothing specific to OCaml compilation and be a general purpose build engine. The build rules should contain all the logic to interpret dune files and build OCaml and Coq projects.

`build_api` will act as a barrier between the `engine` and `build_rules`, more precisely, `build_rules` should depend on `build_api` but not on `engine`. Since we are using `(implicit_transitive_deps false)` in Dune, we will know for sure that `build_rules` can build with only the `build_api` visible.

The plan of action is as follow:

- [x] do a rough split of the `dune` library into `engine` and `build_rules`, with `build_rules` depending directly on `engine`
- [x] look at the list of modules in both library and mark that are obviously at the wrong place
- [x] do a few PRs to move the modules that are at the wrong place and are easy to move to the other side
- [ ] mint `build_api`, make it depend on `engine`, and replace the dependency from `build_rules` to `engine` by a dependency on `build_api`. Initially , `build_api` will be quite big
- [ ] keep moving code around until `build_api` looks reasonable

**Comment by rgrinberg** [comment]
The names chosen in this proposal are unprefixed. I think it would be better if we were to use names that are prefixed with `dune_`. So for example, `dune_engine` over `engine`. There are no namespaces in OCaml, so we should be careful about using common words like this for what might be public libraries (like engine in this case).

**Comment by cwong-ocaml** [comment]
As we move forward with step 2, I think it would be a good idea if we laid out some semi-objective criteria for what constitutes part of the rules vs part of the engine. From discussions with @jeremiedimino and @aalekseyev , I get the sense that everyone has a slightly different heuristic here, so it would be good to synchronize before proceeding.

Personally, I've been operating under the assumption that anything that is common and generic over all possible rules, and that rule authors should not need to worry about should go into the engine. Interacting with the filesystem, lexing/parsing stanzas, etc.

**Comment by aalekseyev** [comment]
My understanding of Jenga philosophy in how the split was done is as follows:

The responsibility of the engine is to expose a deterministic language for writing rules, built on top of non-deterministic foundation of Unix.
This non-deterministic foundation includes:

- Filesystem access (can change due to the user changing things, or the build rules changing things)
- Job scheduling
- Caching: in-memory memoization of time-varying values, mtimes->digest cache, rule cache, shared cache, distributed cache
- RPC handling

The rules only use deterministic primitives, some of the primitives provided by the engine, some of them provided by shared libraries.

The guiding principle, then, is to put as much as possible into rules, subject to above constraints, because the deterministic world is more well-behaved.

One further minor difference/consequence that we follow in jenga, but not in dune so far is that:
- exceptions in a deterministic world can be tolerated, so jenga rules can use exceptions for error reporting
- exceptions in a mutable world in general leave the system in an ill-defined state, so exceptions in the engine make the build system crash hard.

**Comment by rgrinberg** [comment]
In the current split, the following modules are a part of `dune_engine` that seem to be too specific to the rules:

* Ordered_set_lang
* Format_config
* Format_dune_lang
* Opam_file
* Foreign_language
* Dialect

@cwong-ocaml it probably makes sense to explain why they had to be included.

**Comment by cwong-ocaml** [comment]
I think the shortest explanation is that "something else in the engine requires them". In a case-by-case basis, I feel like `Ordered_set_lang` could probably stay in the backend, or at least have some representation there, but the others we should definitely work to move.

**Comment by rgrinberg** [comment]
I'd like to propose a `dune_file` library to factor out the frontend elements of dune that pertain to OCaml The frontend modules would include dune_project, stanza, and other things necessary to extend the frontend without pulling all the rules. The motivation for this is that I'd like the Coq support to be factored to its own library, and this seems like a necessary start.

In the beginning `Dune_engine` will depend on `Dune_file`, we'll slowly make the two independent with the work that Cameron is doing.

**Comment by cwong-ocaml** [comment]
I have no objections. In general, I'm in favor of any movement to clean up the organization of our source libraries. In a similar vein, it might be nice to have a separate library for things that are common to many rules (`gen_rules`, `expander`) versus particular rules themselves (for example, all the `coq_` modules).

**Comment by jeremiedimino** [comment]
That all seems good to me!

**Comment by cwong-ocaml** [comment]
Closing this, since we seem to have moved away from the idea of an explicit `build_api` library.
