### ISSUE TITLE
Native Windows filesystem in WSL2 

### ISSUE THREAD

**Issue by eaubin** [ocaml/dune#3714]
dune build seems to have difficulty using the native windows filesystem mounted in WSL2. 

## Expected Behavior

I'm not sure whats wrong exactly, I hope it would work or give a hint that the file system is problematic.

## Actual Behavior

Trying to build a project in a windows directory, dune will fail saying:

```
Info: Creating file dune-project with this contents:
| (lang dune 2.6)
File "dune", line 1, characters 0-0:
Error: Rule failed to generate the following targets:
- .merlin
File "dune", line 1, characters 0-0:
Error: Rule failed to generate the following targets:
- test.ml
```

## Reproduction

```
$ cd /mnt/c/Users/Ethan/
eaubin@DESKTOP-8TRKK8A:/mnt/c/Users/Ethan$ mkdir test && cd test
eaubin@DESKTOP-8TRKK8A:/mnt/c/Users/Ethan/test$ dune init exe test
Success: initialized executable component named test
eaubin@DESKTOP-8TRKK8A:/mnt/c/Users/Ethan/test$ dune build test.exe
```

On the Ubuntu filesystem builds without issue.

## Specifications
Dune 2.6.2
Ocaml 4.10.0
Ubuntu 20.04.1 LTS running in WSL2

**Comment by dra27** [comment]
I don’t have a machine with WSL 2 to hand, but what’s the output of `ls -laR /mnt/c/Users/Ethan/test`?

**Comment by dra27** [comment]
And just to be totally clear - `dune init` works, it’s `dune build` which produces the errors?

**Comment by dra27** [comment]
Could you try editing the `dune-project` and changing the `2.6` to `2.3` in `lang dune`?

**Comment by eaubin** [comment]
`dune build` works after setting `lang dune` to `2.3`

**Comment by dra27** [comment]
That’s what I thought - removing the write permissions (added in https://github.com/ocaml/dune/pull/3092 in 2.4.0) is failing owing to https://github.com/microsoft/WSL/issues/81.

I think there are two parts to this - the first is do you have to build in `/mnt/c`? The second (for us, cc @mefyl) is should failing to remove write permissions be a hard error (in which case the default error message should be clearer, given that the target clearly is generated!) or can it be silently ignored (bear in mind this is `chmod` failing on Linux because a file system doesn’t support it).

Amusingly, this is something Cygwin goes to tremendous trouble to get right, given the Cygwin-eliminating hype behind WSL!

**Comment by mefyl** [comment]
This should indeed probably not be a hard error. Problems will arise if they are edited, but that's still better than not being able to build at all.

**Comment by eaubin** [comment]
Thanks for the help, I don't need to use `/mnt/c` and the workarounds are fine.
