### ISSUE TITLE
Dune cannot compile executable with package

### ISSUE THREAD

**Issue by gs0510** [ocaml/dune#3839]
In the dune `executable` stanza, I specify a package in the `package` clause for which a corresponding `.opam` file exists in the root.

## Expected Behavior
Dune is able to compile the executable with the package.

## Actual Behavior
Dune fails to find the package listed in the dune clause. When I run `dune build bin/run.exe -p toto` however, dune is able to find the corresponding package `toto`. Am I wrong in assuming that adding the package in the `package` clause should have the same effect as supplying `dune` with `-p` flag?

## Reproduction

- PR with a reproducing test: 

1. A minimal repository with the file structure is here: https://github.com/dinosaure/foo_bar_dune
The repository contains two `.opam files`. The dune file here contains the `package` clause: https://github.com/dinosaure/foo_bar_dune/blob/master/bin/dune#L3
2. Run `dune build bin/run.exe`
3. Run `dune build bin/run.exe -p toto`

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): 4.11.0
- Operating system (distribution and version): Ubuntu 20.04

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): https://gist.github.com/gs0510/3eba6bc36d9fa6670d7074dbf643d17a

**Comment by gs0510** [comment]
cc @dinosaure

**Comment by rgrinberg** [comment]
> Dune fails to find the package listed in the dune clause

What does it mean for dune to fail to find the package listed? As far as I can see, dune is able to find the package.

>  Am I wrong in assuming that adding the package in the package clause should have the same effect as supplying dune with -p flag?

Adding `(package ..)` tells dune to which package a stanza (in this particular case, an executable0 belongs to. This is needed so that `-p` can work correctly. `-p pkg` runs dune in a mode where it pretends that anything that doesn't belong to `pkg` does not exist in this repo. So `(package ..)` is required for `-p` to work correctly.

**Comment by rgrinberg** [comment]
Hi! Please re-open if there's still any questions.
