### ISSUE TITLE
Understanding new foreign_stubs

### ISSUE THREAD

**Issue by WhoAteDaCake** [ocaml/dune#3877]
Hi, i've started using new `foreign_stubs` feature in my code, but I'm a bit confused, by how the flags work. Do both cxx_flags.sexp and cxx_library_flags.sexp go under flags? My dune file is:

```
(executable
    (name App)
    (package App)
    (preprocess (pps brisk-reconciler.ppx))
    (public_name App)
    (libraries bigarray Revery)
    (flags -g)
    (foreign_stubs (language cxx)
        (names get_windows screenshot_window)
        (flags :standard -Wall -Wextra -Werror --std=c++14 (:include c_flags.sexp) (:include c_library_flags.sexp))
    )
)

(rule
(targets c_flags.sexp c_library_flags.sexp)
(deps (:discover config/discover.exe))
(action (run %{discover})))
```

The discover file looks like: 

```ocaml
open Configurator.V1;

let default_config : Pkg_config.package_conf = {
    libs: [],
    cflags: [],
};

let combine_configs = (pc, items) => List.fold_left((cfg: Pkg_config.package_conf, package) => {
  switch (Pkg_config.query(pc, ~package=package)) {
  | None => cfg
  | Some(conf) => {
      libs: cfg.libs @ conf.libs,
      cflags: cfg.cflags @ conf.cflags,
    }
  }
}, default_config, items);

let get_linux_config = (t) => {
  switch (Pkg_config.get(t)) {
  | None => default_config
  | Some(pc) => combine_configs(pc, ["opencv4", "tesseract", "x11"])
  };
}

main(~name="discover", t => {
  /* Only supports Linux at the moment*/
  let conf = get_linux_config(t);
  /* write_sexp("flags.sexp", conf.flags); */
  Flags.write_sexp("c_flags.sexp", conf.cflags);
  Flags.write_sexp("c_library_flags.sexp", conf.libs);
});
```

When I try to compile, I'm experiencing linking isues with opencv4 (which produces a cflag when pkg-config is ran). I assume that's why it's happening, however, when I tried to add `c_library_flags` field, the only thing I see is:

> Error: Unknown field c_library_flags

My setup:
* `esy dune --version` (2.7.1)
* `esy ocaml --version`  (The OCaml toplevel, version 4.09.1)

**Comment by nojb** [comment]
`c_library_flags` is a top-level field of the `library` stanza, used to pass link-time flags for C stubs. So it cannot be used inside the `foreign_stubs` field nor inside an `executable` stanza.

In order to use it, you probably want to make a separte library with your foreign stubs and the OCaml bindings, use `c_library_flags` there, and then use that library as a dependency of your executable.

**Comment by WhoAteDaCake** [comment]
Yes, thank you so much, that worked perfectly. Is there any reason, why it is not allowed to do this within the `executable` stanza?

**Comment by nojb** [comment]
You can pass link-time flags for `executables` by using `-cclib ...` in the `(flags ...)` field. So am not sure there is a big need to have `c_library_flags` in `executable` stanzas, but am not very familiar with this part of the code, so I may be missing something.

cc @snowleopard

**Comment by snowleopard** [comment]
Sorry for responding late:

> why it is not allowed to do this within the `executable` stanza?

My understanding is that `c_library_flags` is fundamentally a property of the library: if you have multiple executables that depend on it, you'll need to pass these flags in all of them. So, it seems better to specify these flags just once, in the `library` stanza, rather than repeat them in every dependent `executable`.
