### ISSUE TITLE
Done: X/YY (jobs: Z) message remains after dune terminates

### ISSUE THREAD

**Issue by daniel-larraz** [ocaml/dune#4023]
## Expected Behavior

The `Done: X/YY (jobs: Z)` message is only showed in the terminal while dune is running. After dune finishes, it disappears from the console. This is the behavior on my Ubuntu 18.04.5 machine with dune 2.6.2 and below.

## Actual Behavior

The `Done: X/YY (jobs: Z)` message remains in the terminal after dune terminates. I get something like:
```
prompt$ dune build
Done: X/YY (jobs: Z)prompt$
```

## Reproduction

1. Install dune 2.7.0 or above on an Ubuntu 18.04.5 with opam.
1. Run `dune build` to build the [hello_world example](https://dune.readthedocs.io/en/latest/quick-start.html#building-a-hello-world-program)

## Specifications

- Version of `dune` (output of `dune --version`): 2.7.1
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0 (same happens with older versions, e.g. 4.07.1)
- Operating system (distribution and version): Ubuntu 18.04.5

**Comment by yannl35133** [comment]
[DISCLAIMER] I am not a dev.

This is a duplicate of #3737. It is fixed in master, so we just need to wait for the next release.

If you don't mind using the "unstable" dev branch of dune, you can install the patch right now by pinning dune in your opam installation :
```
opam pin add dune https://github.com/ocaml/dune.git
```
Warning : 
- this will prompt you to recompile everything that needs dune, at every update in master (as they happen pretty frequently, this is basically every time you will do `opam update && opam upgrade`)
- this is a dev branch; if you face problem, you can go back to the released version by removing the pin :
```
opam pin remove dune
```

**Comment by nojb** [comment]
Thanks for chiming in @yannl35133! I can only add that 2.8 will hopefully be released soon, it is just a matter of ironing out a couple of remaining kinks.

**Comment by daniel-larraz** [comment]
Hi @yannl35133. Thank you for the reference! Yes, this is a duplicate. Closing issue.
