### ISSUE TITLE
Difference between macOS and Linux on dune 2.7.1

### ISSUE THREAD

**Issue by lindig** [ocaml/dune#4042]
I notice that the same source code causes warnings that break a build on Linux but not on macOS. Both are on dune 2.7.1 but one with OCaml 4.08.1 the other 4.09.0 but I'm pretty sure that is not what causing this. Is there a know difference between the two?

**Comment by voodoos** [comment]
We need more information to be able to help you. What are the warnings your seeing ? Can you provide us a copy of the command output ?

**Comment by lindig** [comment]
I'll provide an example. Warnings that differ are about unused code, for example.

**Comment by lindig** [comment]
* Repo with dead code: https://github.com/lindig/hello/tree/dune-macos
* This code fails with a warning in the CI: https://github.com/lindig/hello/runs/1564595617?check_suite_focus=true
* It does not fail on macOS in a local compilation running 
* The difference could be completely unrelated to Dune

**Comment by voodoos** [comment]
I guess the problem is not dune of compiler or os related, but how you start the build.

Using `dune build`  by default will error on warnings while `dune build -p pkg_name` will not because it switches to "release mode".

Your CI uses `dune build` so it fails on warnings.
Your Make file uses `dune build -p hello` so `make all` doesn't fail on warnings.
Running `dune build` locally does fail with warnings.

**Comment by lindig** [comment]
Thanks. The surprise here is that the CI does not use the method specified in the `*.opam` file. Obviously this is unrelated to dune and we can close the issue.

**Comment by voodoos** [comment]
Well you CI workflow does that explicitely:
`https://github.com/lindig/hello/blob/3d8243216b0473190b31ef42e0fe1936f15d4398/.github/workflows/ci.yml#L19`

You can just switch this line to `build -p hello`
