### ISSUE TITLE
dune exec leaves empty directory in /tmp/

### ISSUE THREAD

**Issue by copy** [ocaml/dune#4243]
## Expected Behavior

`/tmp/` should be cleaned of dune's temporary on a regular run of `dune exec`.

## Actual Behavior

There are empty directories named `buildXXXXXX.dune` left in `/tmp/`

## Reproduction

1. `echo '(executable (name test))' > dune`
1. `echo > test.ml`
1. `dune exec ./test.exe`
2. `ls /tmp |grep dune` # an empty directory is added every time step 3. is repeated

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.2
- Version of `ocaml` (output of `ocamlc --version`): 4.11.1
- Operating system (distribution and version): Arch Linux

**Comment by rgrinberg** [comment]
This is almost certainly because we are using `Unix.exec` in `dune exec`. This omits running the exit hooks which means that the clean up doesn't occur. @jeremiedimino any suggestions on how to fix this? All I can think is creating some wrapper that will allow us to manually run the registered exit hooks.

**Comment by jeremiedimino** [comment]
What about calling `Stdlib.do_at_exit ()`?

**Comment by rgrinberg** [comment]
That's a private api, isn't it? Can we rely on it?

**Comment by jeremiedimino** [comment]
Ah, I didn't realise it was private. Seems safer to do our own thing then.
