### ISSUE TITLE
Dune RPC - Switch from multithreading to select.

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#4244]
Switch csexp_rpc to use select instead of threads. Currently, csexp_rpc is creating two threads per client. This is deemed to be inefficient, and we've decided to use select instead. We already use select for the self pipe trick, so it should be natural.

**Comment by rgrinberg** [comment]
@jeremiedimino did we say we want 1 thread per client and select to multiplex read/write or 1 thread for all clients?

**Comment by rgrinberg** [comment]
@jeremiedimino I have a prototype of this, but it really is much more complicated than the current thread based implementation. In addition, I'm not even sure if we can replace the threads for `dune rpc init` on Windows. I don't think we can read from stdin/stdout in a non blocking way with select there. Are you sure this is worth it?

**Comment by jeremiedimino** [comment]
For stdin/stdout, we could slightly change the design of `dune rpc init`; for instance `dune rpc init` would print a string in the same format as the `DUNE_RPC` variable, and the program would read it and connect to it. This way we would use the same code path whether we connect directly to the RPC or whether we connect via `dune rpc init`. What do you think?

Regarding whether all this is worth it, right now we only have a small number of clients, so it's probably not a big deal. However, once we start using the RPC for command invoked by Dune, it is going to be more relevant. Creating two new threads for every command that uses the RPC seems a bit heavy to me.

Could you open a draft PR so that we can look at the code?

**Comment by rgrinberg** [comment]
> For stdin/stdout, we could slightly change the design of dune rpc init; for instance dune rpc init would print a string in the same format as the DUNE_RPC variable, and the program would read it and connect to it. This way we would use the same code path whether we connect directly to the RPC or whether we connect via dune rpc init. What do you think?

The reason for `dune rpc init` was to abstract away the connection establishing for clients. Moreover, the current code is simpler, already tested, and the there's performance gain from using select here.  Finally, if we want transparent reconnection, ` dune rpc init` would no longer be able that for all clients. So I must say that I'm not a fan of changing the user facing things just to accommodate this.

> Could you open a draft PR so that we can look at the code?

Will do.

**Comment by jeremiedimino** [comment]
I hear you, but if we want to scale there is no two ways about it; we have to be very mindful of our resource usage. You are probably right that changing `dune rpc init` here is not worth it, but for the rest let's give it a proper try.

**Comment by rgrinberg** [comment]
> You are probably right that changing dune rpc init here is not worth it, but for the rest let's give it a proper try.

Yeah, my current position is that `dune rpc init` should remain the same, but we should incorporate this change once we allow actions to access dune with RPC. If we only have editors connecting, it seems like overhead from threads should be minimal.
