### ISSUE TITLE
request: ppx_context not only with pps_staged

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#4284]
I understand that only with the preprocessor directive pps_staged
is the ppx passed the compiler's ppx_context.
but it is not desirable to have a pps_staged because it is not under ppxlib
merging of other ppxes.
so why no context through the normal variety?
I understand ppxlib uses its own frontend parser instead of actually invoking the
regular compiler to generate the AST, but that should not prevent
the creation of an identical context, should it not?

**Comment by jeremiedimino** [comment]
> but it is not desirable to have a pps_staged because it is not under ppxlib merging of other ppxes.

That's not it; the ppx executable used by the two methods is exactly the same. The only difference is in the compilation pipeline. With regular `(preprocess (pps ...))`, you get the following compilation pipeline:

```
                                       +------+
                                       |ocamlc|
                                       +------+
                                           ^
 +-----------+  +-------+  +--------+      |
 |source file+->+ppx.exe+->+ocamldep+------+
 +-----------+  +-------+  +--------+      |
                                           v
                                        +--------+
                                        |ocamlopt|
                                        +--------+
```

while with `(preprocess (pps_staged ...))` you get:

```
                                        +------+
                                       >+ocamlc|
                                       +---+---+
                                       |   |
+-----------+  +--------+              |   | +-------+
|source file+->+ocamldep+--------------+   +>+ppx.exe|
+-----------+  +-+------+              |     +-------+
                 |                     |
                 |                     +---------+
                 |  +-------+          >+ocamlopt|
                 +->+ppx.exe|           +-+------+
                    +-------+             |
                                          |  +-------+
                                          +->+ppx.exe|
                                             +-------+
```

The reason you observe a different context is probably because in the staged case the compiler fills in more things. What are you missing in the regular case from the context?

**Comment by progman1** [comment]
I was prompted to ask about this because I read somewhere that staged ppxes don't compose with non-staged ie. don't combine into a single pass of the AST.
but it looks like I misconstrued that. So they compose but the output is used differently (according to the pipeline used in)? 
In your diagram (did you use a tool for that?) for the staged case - is the ppx being invoked
twice, once for ocamldep, again for the compiler?

I rely on the include/load paths and the five special compiler flags, -recursive-types et al
and running my ppx as regular,  indeed screws things up.
Since the invocation of the compilers or the ppx.exe is under dune control I do not understand why the same context is not being injected.

**Comment by jeremiedimino** [comment]
I used https://asciiflow.com/ to draw the diagram.

Dune makes the assumption that the preprocessing and typing phases are cleanly separated. Which is the case for the vast majority of ppx rewriters. It relies on this assumption to speed up the build as follow:

1. preprocessing a file can start before the dependencies of the file have been built
2. it does the preprocessing step only once and shares the result between the different tools that work on the source file (ocamldep, ocamlc and ocamlopt)
 
Note that for 2, the gain is more than just running ppx.exe less; the way the compiler interacts with ppx rewriters is less efficient than the way Dune does.

However, some ppx rewriters invoke the OCaml typer, hence mixing the preprocessing and typing phase. This is not compatible with the first optimisation because at the time ppx.exe is invoked, the cmi files of the module dependencies are simply not there yet. This is why we introduced the `pps_staged` method, so that users who want to use ppx rewriters using the OCaml typer could do so at the cost of slower build times.

So in the end, even if Dune was passing the include/load paths and other flags used by the typer to ppx.exe in the first pipeline, the ppx rewriters could simply not use them because not enough has been built at this point.

**Comment by Kakadu** [comment]
> > but it is not desirable to have a pps_staged because it is not under ppxlib merging of other ppxes.
> 
> That's not it; the ppx executable used by the two methods is exactly the same. The only difference is in the compilation pipeline. With regular `(preprocess (pps ...))`, you get the following compilation pipeline:
> 
> ```
>                                        +------+
>                                        |ocamlc|
>                                        +------+
>                                            ^
>  +-----------+  +-------+  +--------+      |
>  |source file+->+ppx.exe+->+ocamldep+------+
>  +-----------+  +-------+  +--------+      |
>                                            v
>                                         +--------+
>                                         |ocamlopt|
>                                         +--------+
> ```
> 
> while with `(preprocess (pps_staged ...))` you get:
> 
> ```
>                                         +------+
>                                        >+ocamlc|
>                                        +---+---+
>                                        |   |
> +-----------+  +--------+              |   | +-------+
> |source file+->+ocamldep+--------------+   +>+ppx.exe|
> +-----------+  +-+------+              |     +-------+
>                  |                     |
>                  |                     +---------+
>                  |  +-------+          >+ocamlopt|
>                  +->+ppx.exe|           +-+------+
>                     +-------+             |
>                                           |  +-------+
>                                           +->+ppx.exe|
>                                              +-------+
> ```
> 
> The reason you observe a different context is probably because in the staged case the compiler fills in more things. What are you missing in the regular case from the context?

This is a very cool painting, @jeremiedimino ! Any chance it can get into the manual?

**Comment by jeremiedimino** [comment]
Not sure we want that level of detail in the manual as everything that's documented ends up part of the semantically versioned API of Dune and it is more difficult for us to change, but it could definitely go in `doc/dev`. One part I've been thinking to change for instance is allowing to squash the `ppx.exe` and `ocamldep` steps, given that `ocamldep` does a purely syntactical analysis. That would save one process per file, which should be noticeable on big workspaces.

**Comment by jeremiedimino** [comment]
I thought about this again, and actually I now think this should indeed be documented in the manual. As well as other things we do in Dune that are not completely obvious, such as the way we compile libraries using module aliases, or the way `dune-build-info` or `dune-configurator` do what they do. After all, in open source we like to understand how things work rather than just accept things for granted. Plus having a clear model of how Dune works should help debugging, and not to mention should help people contributing to Dune.

As long as we put a clear disclaimer that these are implementation details that are not covered by the semantic versioning of Dune, we should be fine.

**Comment by jeremiedimino** [comment]
I opened this ticket about it: https://github.com/ocaml/dune/issues/4385
