### ISSUE TITLE
Support alternative name for `dune` files?

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#4386]
The fact that the binary and the build description files are named identically is problematic if a directory that contains `dune` files happens to be in the PATH and the `dune` file happens to have the executable bit set (this can happen easily under Windows).

In order to mitigate this, what do you think about allowing to set the name of the `dune` files on a per-project basis? eg `dunefile`, etc.

**Comment by alainfrisch** [comment]
> this can happen easily under Windows

Apparently, this is always the case when using the Windows native git client.

**Comment by jeremiedimino** [comment]
This feels like an epic fail :facepalm:

More seriously, when does this situation happen?

A per-project setting feels a bit odd. We could allow two names, so that one can use the alternate name in problematic situations.

**Comment by alainfrisch** [comment]
I don't know the details, but I understand this might be a bad interaction between a clone managed by a native git client and Cygwin (each with its own notion of executable mode).

It seems that some filesystems like FAT don't even have this notion of executable mode. Not sure if this is in scope, but anyway, a solution which can avoid the problem seems generally useful. Always accepting two names seems good to me.

**Comment by jeremiedimino** [comment]
I see. But when do you end up with a directory in the `PATH` pointing to a directory with a `dune` file?

**Comment by nojb** [comment]
One case is when you add a directory which is in your dune workspace to which you promote binaries built in the same workspace.

**Comment by jeremiedimino** [comment]
That makes sense. Dune could detect this case BTW, i.e. check whether the `dune` file has the executable bit set when promoting an executable file. Would Dune removing the executable bit in this case cause troubles?

BTW, I was just re-reading my previous message. When I said epic fail I meant on the Dune side, it feels like we should have thought about this when choosing the name for dune files.

**Comment by nojb** [comment]
> That makes sense. Dune could detect this case BTW, i.e. check whether the `dune` file has the executable bit set when promoting an executable file. Would Dune removing the executable bit in this case cause troubles?

No, I don't think it would cause problems, but am not sure it would solve the problem fully, as it assumes that promotion is the only way for binaries to find their way to a directory containing a `dune` file. So to be really fireproof I think it would be a good idea to have an alternative name available instead of `dune` for the "dune files". If no-one objects, I can take a look at proposing a PR in this direction.

> BTW, I was just re-reading my previous message. When I said epic fail I meant on the Dune side, it feels like we should have thought about this when choosing the name for dune files.

Understood! Yes, with the old name we had `jbuilder` and `jbuild` so there was no problem there. But with `dune`...

**Comment by jeremiedimino** [comment]
> No, I don't think it would cause problems, but am not sure it would solve the problem fully, as it assumes that promotion is the only way for binaries to find their way to a directory containing a dune file. So to be really fireproof I think it would be a good idea to have an alternative name available instead of dune for the "dune files". If no-one objects, I can take a look at proposing a PR in this direction.

SGTM. In the long run, it's probably best to have a single name, so we might want to plan a transition. With that in mind, we should choose the alternative name with a bit of care, so that we don't hit the same issue in the future with another tool. It might be worth looking how other tools name such configuration files that lives in software repositories.

**Comment by alainfrisch** [comment]
Quick googling (I'm unfamiliar with most of these tools, so take that with a grain of salt):

make -> Makefile
omake -> OMakefile
cmake -> CMakeLists.txt
ninja -> build.ninja
ant -> build.xml 
cabal -> .cabal
stack -> stack.yaml

My personal preference would be for `Dunefile` (or `dunefile`).

**Comment by jberdine** [comment]
[`buck`](https://buck.build/concept/build_file.html) names its build files `BUCK`

**Comment by jeremiedimino** [comment]
@jberdine does buck has a similar issue on Windows as the one described in this PR? Given that the file system is case-insensitive on Windows.

**Comment by jberdine** [comment]
I don't really know, but I guess so. The contexts I have seen have PATH pretty locked down though. Also, the name can be configured, `BUCK` is just the default. https://buck.build/files-and-dirs/buckconfig.html#buildfile.name

**Comment by jeremiedimino** [comment]
I see. Interesting to see that buck allows to configure this filename. I was thinking that it could make life harder for editors, as they would have to ask dune what the name of these files are.

Regarding the alternative name, I was just thinking that all our other config files are called `dune-<something>`, so we could use `dune-file` to be consistent.

FTR, we are starting to look into replacing the current dune language by a more well defined configuration language, so that we have a better basis to build on. The current language has evolved in pretty ad-hoc ways. This is more a long term goal, but when this happens we might want to rename our config files to `<config-file>.<name-of-the-config-language>`.

**Comment by jeremiedimino** [comment]
Agreed. @nojb, I'd point dune-dev to this ticket just in case we missed something, but otherwise I'd say you can go ahead.

**Comment by nojb** [comment]
> Agreed. @nojb, I'd point dune-dev to this ticket just in case we missed something, but otherwise I'd say you can go ahead.

Done! I will try to submit a PR shortly.
