### ISSUE TITLE
Allow more variables for `enabled_if`

### ISSUE THREAD

**Issue by toots** [ocaml/dune#4455]
`enabled_if` is currently pretty limited. In particular, it is not possible to enable a library depending on run-time configuration as, for instance, determined by `dune-configurator`.

In the case at hand, we want to optionally compile a library that implements support for `OSS` sound output. We have this configuration binary:
```ocaml
module C = Configurator.V1

let oss_test = {|
#include <sys/soundcard.h>

int main() {
   return 0;
}
|}

let () =
  C.main ~name:"liquidsoap" (fun c ->
      let oc = open_out "oss_enabled" in
      output_string oc (string_of_bool (C.c_test oss_test));
      close_out oc)
```
Then this `dune` configuration:
```
(library
 (name liquidsoap_oss)
 (libraries liquidsoap_core)
 (enabled_if (= "true" %{read:oss_enabled}))
 (library_flags -linkall)
 (optional)
 (foreign_stubs
  (language c)
  (names oss_io_c))
 (modules oss_io))
```
But this is currently impossible:
```bash
File "src/lib/dune", line 472, characters 25-42:
472 |  (enabled_if (= "true" %{read:oss_enabled}))
                               ^^^^^^^^^^^^^^^^^
Error: Only architecture, system, model, os_type, ccomp_type, profile,
ocaml_version and context_name variables are allowed in this 'enabled_if'
field. If you think that read should also be allowed, please file an issue
about it.
```

**Comment by jeremiedimino** [comment]
This used to be difficult because of the internals of Dune. i.e. at the time the `enabled_if` was evaluated we couldn't access the results of execution of build rules.

The core of Dune is now more powerful and makes that easy, so we can definitely allow that. However, right now the issue one might run into is that some variables might introduce a computation cycle. For instance, if you use `%{lib-avaiable:...}` in the `enabled_if` of a `library` stanza, it's quite possible that Dune will get into a loop. This will be detected but the error is pretty horrible. That's one reason why the current restrictions on `enabled_if` exist. We have a plan to provide good error messages in such cases. Once that's unrolled, we can relax the set of variables allowed in `enabled_if`.

**Comment by jeremiedimino** [comment]
There is no good workaround unfortunately. You could switch the `dune` file to OCaml syntax and manually call the C compiler. But that might be a bit clunky and that would make the build slower (switch dune files are re-evaluated on every run).

Or alternatively make the library always available but with dummy stubs when oss is not available.

**Comment by rgrinberg** [comment]
> This will be detected but the error is pretty horrible. That's one reason why the current restrictions on enabled_if exist. We have a plan to provide good error messages in such cases. Once that's unrolled, we can relax the set of variables allowed in enabled_if.

@jeremiedimino I think our error are messages are fine now. Should we implement this?

**Comment by jeremiedimino** [comment]
Sounds good to me.
