### ISSUE TITLE
Documentation for `~/.config/dune/config`

### ISSUE THREAD

**Issue by Zimmi48** [ocaml/dune#4555]
Currently, this config file is virtually only documented in `man dune-config`. The documentation at https://dune.readthedocs.io/en/stable/ only mentions this config file in the section on caching (https://dune.readthedocs.io/en/stable/caching.html#configuration). Furthermore, some config options are missing from `man dune-config` (the `cache-trim-period` and `cache-trim-size` options mentioned at https://dune.readthedocs.io/en/stable/caching.html#on-disk-size).

**Comment by jeremiedimino** [comment]
That's definitely not great.

We are making our lives harder by documenting the config file in two different places. We had a quick chat about this in today's meeting and agreed to document the config file only in the online manual. The man page should only have a pointer to the online doc. Then the manual should be updated to cover all available options.

If you'd like to help, any PR in that direction would be most welcome. Otherwise one of us will do it when we get a chance.

BTW, there is an issue causing the online manual to lag behind. We suspect it was caused by renaming "master" to "main". @rgrinberg is looking into this.

**Comment by rgrinberg** [comment]
I should note that I [experimented](https://github.com/ocaml/dune/pull/3923) with shipping the manual with dune itself. I still think it's a good idea, but the implementation has some issues.

**Comment by jeremiedimino** [comment]
Agreed, installing the manual would be nice.

**Comment by emillon** [comment]
Hi,
To conclude on this issue:
- we now have some documentation for the config file
- `cache-trim-period` and `cache-trim-size` are now removed
- we don't have a plan to install the manual

Thanks
