### ISSUE TITLE
Write permissions for test files added with source_tree are not preserved

### ISSUE THREAD

**Issue by alexmusa** [ocaml/dune#4674]
## Expected Behavior

When adding test files with `(deps (source_tree ./my-test-files))`, the test files stay writable.

## Actual Behavior

I get a `Fatal error: exception Sys_error("my-test-files/subdir/test2: Permission denied")` when trying to write to the test file.

## Reproduction

- PR with a reproducing test: #4673

## Specifications

- Version of `dune` (output of `dune --version`): 2.8.5
- Version of `ocaml` (output of `ocamlc --version`): 4.11.1
- Operating system (distribution and version): 20.04.1-Ubuntu

**Comment by voodoos** [comment]
It is expected that rules actions only write to a specific set  of target files declared with the `targets` field (when they cannot be inferred).
These targets should be in the current dir and cannot be the same as the deps because that would cause a dependency cycle.

(Note that your issue is not specific to the usage of `source_tree`, it would be the same using an explicit path)

I do not now what you are trying to achieve but you should probably use an intermediary file.

**Comment by alexmusa** [comment]
Make sense. I was trying to use files `my-test-files` for tests of my program in which they are modified in-place.

```
(rule
  (alias runtest)
  (deps (source_tree ./data))
  (action  (progn
             (run chmod -R ug+w data)
             (run ./test_progam.exe)
)))
```

That `source_tree` is called that and not `data_tree` tells me I am definitely doing something wrong. What would the proper way to have such tests in dune?

**Comment by voodoos** [comment]
You cannot have the test modifying data in-place if the data is not generated by the test or it won't be reproducible twice.

Maybe you can have a look at the [cram framework](https://dune.readthedocs.io/en/stable/tests.html#cram-tests) that allows you to write shell scripts that can prepare your data, run the test program and then diff the result.

**Comment by alexmusa** [comment]
Alright, thanks a lot for the insight
