### ISSUE TITLE
Extract project name from dune-project file

### ISSUE THREAD

**Issue by gpetiot** [ocaml/dune#4820]
## Desired Behavior

It would be great to have an easy way to extract the `name` field from the `dune-project` file without having to parse the file (for some context that's what we do in `dune-release` (cc @NathanReb) and it's an issue for multi-package projects as there are multiple names in that file).

We could imagine needing to extract more fields from this file in the future but for now we would be happy with just the project name.

@emillon suggested that it could be integrated to `dune describe`

**Comment by nojb** [comment]
Yes, it makes sense to add this to `dune describe`. The problem with this command is that today it just dumps a huge amount of information when run most of which may not be desired and that also it may take a bit of time to compute for large repositories.

It would make sense to add a small query language to this command so that it returns only what is wanted. Keep in mind that no-one is working on this at the moment, so it won't be available in the short term.

Possible sources of inspiration: GraphQL, the AWS CLI tool filter language https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html

**Comment by emillon** [comment]
I agree that `dune describe` is the right place to do that today. Actually I worked on a graphql interface to dune describe during the 2020 retreat! To solve the filtering issue it's also possible to add JSON output and use `jq`, or use the corresponding `sexp` tool from JS in the current output.

As an alternative for this particular use case, I wonder if `dune subst` could be modified so that instead of replacing in files, it could expand the placeholders in a string, similarly to `opam config expand PATTERN`. You could then get what you're after using `dune subst --pattern %%NAME%%`. But that seems too ad hoc, especially since most of the other substituted variables can be found in the `dune describe` output.

**Comment by nojb** [comment]
> I agree that `dune describe` is the right place to do that today. Actually I worked on a graphql interface to dune describe during the 2020 retreat!

Cool, what is its status? I think it would be nice to get it in.

> To solve the filtering issue it's also possible to add JSON output and use `jq`, or use the corresponding `sexp` tool from JS in the current output.

Yes, this would be a possibility, but it also means that `dune describe` will always compute "everything". I was wondering if we could make things more efficient by delaying the response after we know what the query is in order to compute only what is needed.

**Comment by emillon** [comment]
Yes, that overfetching part is where graphql shines. My prototype was just that - a prototype. It actually dumped a ton of state into some JSON object and I added a query layer on top of that. I'll see if I can make a blog post out of this. Today the RPC might be a better place to implement this.

To get back to the original question, `dune describe` supports several "things" to query, so we could just add `dune describe project-name` or `dune describe project` with just the contents of `dune-project` to avoid overfetching.

**Comment by gpetiot** [comment]
I don't have the need for this anymore.
I'm okay to close this is this is not something that would make sense in dune anymore.
