### ISSUE TITLE
Check on .cmt load path

### ISSUE THREAD

**Issue by zoggy** [ocaml/dune#4922]
## Desired Behavior

Some packages install `.cmt` files with a load path refering to local directories in the original source tree. For example, 

```
$ ocamlobjinfo ~/.opam/4.12.0/lib/tyxml-ppx/tyxml_ppx_register.cmt
[...]
Load path:  ppx/register/.tyxml_ppx_register.objs/byte [...]  ppx/.tyxml_ppx.objs/byte [...]
```
If one local directory seems ok to be listed, i.e. usually the one with the objects files of the directory where is the corresponding `.ml` file, having more than one may be an error. For example, the `.cmt` file above should have its load path include `[...]/lib/tyxml-ppx/internal` directory where some required files are located.

Do you think that some check could be provided by dune to warn when an installed `.cmt` file has an incomplete load path ? For example by loading the typedtree from the `.cmt`file and rebuilding its environment with something like:

```ocaml
match cmt.cmt_annots with
  | Implementation structure ->
    try
        let map =
           { Tast_mapper.default
             with env = fun _ env -> Envaux.env_of_only_summary env } in
        let structure = map.structure map structure in
        ...
    with
    | Envaux.Error e ->...
    | Persistent_env.Error e -> ..
    | ...
```

**Comment by jeremiedimino** [comment]
If we had such a warning, what should the user do when they see it?

**Comment by zoggy** [comment]
I guess her compilation/installation procedure should be fixed in some way so that all required `.cmt` files can be found from the load path. Having such broken `.cmt` files make the load path useless and one may have to rely on the package system to gather the correct load path, which will make cmt-based tools more complicated.

**Comment by jeremiedimino** [comment]
But concretely, how would they adapt their compilation/installation procedure? The problem is likely to arise with packages that install several libraries. For instance, if package P installs libraries A and B and B depends on A, then the cmt files for B will refer to the local paths for A. If a user gets a warning in such a situation, what should they do?

**Comment by zoggy** [comment]
I see four solutions:

1. make separate packages for A and B. 
1. make a single library. If B requires A and A is only intented to hide things under the carpet and is not intented to be used on its own, then there is no reason to have two libraries. The documentation should state which part of the library is to be used and which part is "private". If A can be used by another package/library, then there should be one package for A and one package for B.
1. install both A and B into the same directory, so even if there are two libraries which should be in two packages, at least the load_path of installed `.cmt`s will be correct.
1. use an additional tool to set a correct load_path in `cmt`s at install time. This seems more difficult.

I think that dune has enough information to recommend on of the two first designs and emit a warning if a package contains at list two libraries with one depending on the other.

**Comment by jeremiedimino** [comment]
It's not clear to me that 1 and 2 capture everything. Maybe there are some packages out there for which it makes sense to install two distinct user facing libraries in a single package.

3 is a no no. In the past, we had to move in the direction of splitting directories for good reasons. Installing several libraries in the same directory is going backward.

BTW, why do you care about paths in cmt files?

**Comment by zoggy** [comment]
I would be curious about the reasons two disting libraries should be in the same package (except for the developer's convenience). It there is no dependency between them, they should be in separate packages. A benefit of a packaging system is supposed to allow a minimal installation. But this case does not break the load path of the `.cmt` file.

The problem is with packages with at least two libraries with one dependency. They should be either merged or in separate packages. I think dune can help to push into this direction.

I do not see other cases to think about: with two libraries, either there is a dependency from one to the other, of there is not. An optional dependency from B to A (for example depending on the availability of a library C) should be considered as a plain dependency.

About splitting directories, can you point me some readings ?

About paths in `.cmt` files: I'm developing a tool which loads a `.cmt` file, then rebuilds the lambda representation to make some computations on it. This requires a typing environment, which requires reading the `.cmi` files. The path to find these `.cmi`s is supposed to be given by the load path, except for the files found in the local tree when compiling, since the destination directory is not knwon at this time. I already add to this load path the directory where the loaded `.cmt` file is, so the `.cmi`s of the library can be found. But if this library B depends on a library A which was not installed at compile time, the install path of A is not in the load path, only its compilation-time path, which is useless. Maybe I could query opam and/or ocamlfind to find the missing directories but I would prefer use the information which is supposed to be here for my purpose.

**Comment by jeremiedimino** [comment]
> I would be curious about the reasons two distinct libraries should be in the same package (except for the developer's convenience). It there is no dependency between them, they should be in separate packages. A benefit of a packaging system is supposed to allow a minimal installation. But this case does not break the load path of the .cmt file.

I don't know either. You'd need to ask people who designed opam and developers who use this feature. Maybe it's just an historical artefact or maybe it's still relevant. In any case, if changing this requires asking a lot of people to change their code then there should be a strong reason for doing so.

> About splitting directories, can you point me some readings ?

This is pretty old stuff so it'd take me some time to dig out, but I can tell you one reason that pushed us towards this change. Let's assume we install two libraries A and B in the same directory and we have a library that depends on A but not C. Because the compiler uses include directories, depending on just A will expose all the cmi files of B. This means that the developer can refer to modules of B in the code of C and C will compile just fine. However, later on when linking an executable that depend on C but not B the linking will fail. This happened several times in the past. Often the problem was not initially detected because the executable depended on B via another path, but eventually this other path dropped the dependency on B and the linking started failing. These problems were pretty difficult to debug. This is still a problem today with the stdlib and unix libraries and missing dependencies on unix still go unnoticed. 

> About paths in .cmt files: I'm developing a tool which loads a .cmt file, then rebuilds the lambda representation to make some computations on it. This requires a typing environment, which requires reading the .cmi files. The path to find these .cmis is supposed to be given by the load path, except for the files found in the local tree when compiling, since the destination directory is not knwon at this time. I already add to this load path the directory where the loaded .cmt file is, so the .cmis of the library can be found. But if this library B depends on a library A which was not installed at compile time, the install path of A is not in the load path, only its compilation-time path, which is useless. Maybe I could query opam and/or ocamlfind to find the missing directories but I would prefer use the information which is supposed to be here for my purpose.

Ok, I can see why you care about the loadpath field of installed cmt files. However, from the point of view of Dune we can't ask people to change their code for the need of one tool that is still in development.

Unless there was a clear consensus that having more than one library per package is a mistake,  your best bet at this point is option 4 or start with a hack calling opam or ocamlfind as you suggest.

**Comment by zoggy** [comment]
Thanks for the explanation regarding splitting directories.

Since there seems to be a large number of packages which install `.cmt`s with a broken load path, I implemented a look up of the `.cmi`s required by a `.cmt`, to add missing directories to the load path. This works fine, except for packages which do not install all required `.cmi`s (but in this case, I can know precisely which file is missing and could report upstream).

I still think that more than one library per package should trigger a warning in dune, but I close this issue by now.
