### ISSUE TITLE
.merlin conflict

### ISSUE THREAD

**Issue by progman1** [ocaml/dune#5272]
I add a 
```
FLG -reader <custom-reader>
```
line to a .merlin file in the source directory.
I do not use promotion yet the file is overwritten by dune.
how is this prevented?
I found the -reader option in its use for Reason syntax files
so this is an established use-case.

thanks.

**Comment by voodoos** [comment]
What version of Dune are you using and what are the step to reproduce ?
In recent versions of Dune `.merlin` files are not written in the source tree any more so your custom file should not be affected.

I am not able to reproduce with the followingf test:
```
  $ cat >dune-project <<EOF
  > (lang dune 2.9)
  > EOF

  $ cat >dune <<EOF
  > (executable
  >  (name main))
  > EOF

  $ cat >main.ml <<EOF
  > print_endline "test"
  > EOF

  $ dune exec ./main.exe
  test
  $ cat >.merlin <<EOF
  > FLG -reader <custom-reader>
  > EOF

  $ ls -a .merlin
  .merlin

  $ dune clean
  $ dune exec ./main.exe
  test

  $ ls -a .merlin
  .merlin
```

**Comment by progman1** [comment]
I'm running 2.6.1
I looked through the changelog but didn't see anything explicit.
from what version of dune is there no writing to src directories?

**Comment by voodoos** [comment]
[The change](https://github.com/ocaml/dune/blob/0794445c55cf2dcfc2e2162893a27b1522ece08c/CHANGES.md?plain=1#L544) happened in v2.8.

However this would not solve your problem in a satisfactory manner since you still want to take advantage of generated  merlin config.

I am not sure of the official workflow to build reason code with Dune and have a correct Merlin configuration ? 
If I am not mistaken Dune should add the `SUFFIX .re .rei` to the Merlin config and Merlin should automatically use the `reason` reader for these files. @rgrinberg can you wonfirm that this is the expected behavior ? 

@progman1 could you share the generated `.merlin` file ?

**Comment by rgrinberg** [comment]
> If I am not mistaken Dune should add the SUFFIX .re .rei to the Merlin config and Merlin should automatically use the reason reader for these files. @rgrinberg can you wonfirm that this is the expected behavior ?

Sounds right to me.

**Comment by progman1** [comment]
I'm not using reason but I am using -reader to supply an alternative parser. So I guess the implication of what you say is that merlin sees a .re and adds the necessary FLG -reader ... ?

While it is certainly welcome to get a generated .merlin initially,
isn't promotion the mechanism to fix it in place?
If dune 2.8.1 and above no longer overwrite the src directories
what is the means of autogenerating the .merlin file and/or maintaining user customisation of it?

**Comment by emillon** [comment]
Hi,
I would say that nowadays the recommended way to support an alternative parser is by defining a dialect using `(dialect)`. It will generate the correct configuration for merlin without any `.merlin` files.
Thanks
