### ISSUE TITLE
Cache: Error: mkdir(/Users/runner/.cache/dune/db/temp): File exists

### ISSUE THREAD

**Issue by smorimoto** [ocaml/dune#5461]
https://github.com/ocsigen/lwt/runs/5262157265?check_suite_focus=true

```
+ /Users/runner/.opam/opam-init/hooks/sandbox.sh "build" "dune" "build" "-p" "csexp" "-j" "3" "@install" (CWD=/Users/runner/work/lwt/lwt/_opam/.opam-switch/build/csexp.1.5.1)
[ERROR] The compilation of csexp.1.5.1 failed at "dune build -p csexp -j 3 @install".
- Error: mkdir(/Users/runner/.cache/dune/db/temp): File exists
- Error: mkdir(/Users/runner/.cache/dune/db/temp): File exists
```

**Comment by smorimoto** [comment]
@snowleopard any idea?

**Comment by snowleopard** [comment]
@smorimoto Sorry, I somehow missed this issue. Do I understand correctly that this failure happened with Dune 3.0.2?

I haven't come across this failure before. It looks like Dune is calling `mkdir` to create a `temp` directory and can't cope with the fact that it already exists. It's a strange reason to fail: I believe this `temp` directory usually remains from the previous build, so I'm not sure why I haven't come across this failure. Perhaps, there is a file (rather than a directory) with the same name?

It looks like this happens on OSX but I don't have access to an OSX machine, so it's tricky for me to debug. Could someone help?
