### ISSUE TITLE
`dune exec` executes in wrong directory

### ISSUE THREAD

**Issue by vrama628** [ocaml/dune#5521]
I have a project with the structure:
```
foo
|- bar.txt
|- dune-project
|- src
|  |- baz.ml
|  |- dune
```
Where `baz.ml` is an executable that reads from the file `bar.txt`. For example, the contents of `baz.ml` are something like
```
let _ = open_in "bar.txt"
```
(To be more specific, I'm using [`dotenv`](https://github.com/thatportugueseguy/ocaml-dotenv)). I'm having difficulty running it in an ergonomic way, and from the output when running `dune exec`, it seems like a bug. When I run `dune exec baz.exe` from _either_ `foo` or `foo/src`, dune prints out `Entering directory '/path/to/foo'`. However, the code that reads the file actually only works properly when I run the command from `foo`, and not when I run it from `foo/src`.

## Expected Behavior

`dune exec baz.exe` executes in the directory it says it will execute in; i.e. the project root.

## Actual Behavior

`dune exec baz.exe` executes in the current directory, but _says_ it will execute in the project root.

## Specifications

- Version of `dune` (output of `dune --version`): `3.0.2`
- Version of `ocaml` (output of `ocamlc --version`): `4.08.1`
- Operating system (distribution and version): Ubuntu 20.04.3 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)

I'm half expecting a reply saying that this is intended behavior, and that the `Entering directory` line that dune prints out means something else entirely (though I struggle to think of what that could be). If this is intentional behavior and I'm being silly for interpreting it the way I am, then my question becomes: what is the intended way to read from files located in a specific place in the project hierarchy, without needing to `cd` every time I want to run `dune exec`? Or, more generally, because I notice that [`dotenv`](https://github.com/thatportugueseguy/ocaml-dotenv) is not a very popular package, what is the common/intended way to do secrets management in OCaml?

**Comment by emillon** [comment]
Hi,

Indeed, the issue here is that "Entering directory X" is printed when the root is detected as a different directory. Some context can be found here:

https://github.com/ocaml/dune/blob/33d625d08bcf596a6c309d791a2cab70f2b8abce/bin/common.ml#L105-L115

I can see why it's confusing in the context of `dune exec`. If you add `print_endline (Sys.getcwd ())` at the beginning of your program you'll see that the program is executed in the same directory as your shell (`restore_cwd_and_execve` is responsible for this - it only happens for `dune utop` and `dune exec`).

> what is the intended way to read from files located in a specific place in the project hierarchy, without needing to cd every time I want to run dune exec?

I don't have a perfect solution but can suggest 2 workarounds:
- always run `dune` at the root of your project - many users use dune this way.
- if you can use an alias instead of `dune exec` (ie if the command you're running is always the same) you have access to variable like `%{project_root}` which you can use to run the command in the right directory.

I suppose we could also try to find a fix for `dune exec` but I'm not sure if a `--cd-to-root` option would make sense.

> what is the common/intended way to do secrets management in OCaml?

I believe that reading from the environment is best practice. If `dotenv` does not work, it's possible to have another program set up the environment. For simple cases you can do it using a shell plugin (that reads `.env` files and start the program with the right environment - this won't work for things like `.env.production` which require the program to determine which file to read).

**Comment by vrama628** [comment]
Thanks!
