### ISSUE TITLE
dune describe workspace --with-deps fails because it doesn't find some rules

### ISSUE THREAD

**Issue by Khady** [ocaml/dune#5680]
## Expected Behavior

`dune describe workspace --with-deps` is supposed to output a sexp similar to the one without `--with-deps` except that it includes dependencies between modules.

## Actual Behavior

`dune describe workspace` creates the expected output 

`dune describe workspace --with-deps` generates an error
```
Error: No rule found for .devkit_core.objs/action.pp.mli.d
Error: No rule found for .devkit_core.objs/action.pp.ml.d
```

## Reproduction

```
git clone https://github.com/ahrefs/devkit.git
cd devkit
opam install . --deps-only # or opam install devkit)
dune workspace describe --deps
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.1.0
- Version of `ocaml` (output of `ocamlc --version`): 4.14.1
- Operating system (distribution and version): debian 10

**Comment by rgrinberg** [comment]
Likely some missing dependencies. @esope mind taking a look?

**Comment by esope** [comment]
Yes, I'll take a look. Thanks.

**Comment by esope** [comment]
The issue seems to be related to ``per_module`` pre-processing.
Currently, the detection for preprocessing in ``dune describe`` is a the granularity of a library or of an executable. The presence of a pre-processor should be detected at the granularity of a module instead.
@rgrinberg : do you have any idea of how to retrieve that information at the granularity of modules ?

**Comment by Khady** [comment]
netstring is part of ocamlnet https://github.com/ahrefs/devkit/blob/a49186da58a399c90b0ee75ac6aa80c097a80d8e/devkit.opam#L21

**Comment by esope** [comment]
Fixed with [PR5682](https://github.com/ocaml/dune/pull/5682).
