### ISSUE TITLE
Dune cram tests has no test reports

### ISSUE THREAD

**Issue by frejsoya** [ocaml/dune#6382]
Dune cram based tests should be able to output a test report.  Similar to other test tools such as alcotest.

**Comment by rgrinberg** [comment]
If this is a proposal, it's missing a lot of details before it can be discussed by the rest of the team. Can you update this issue with more information? Some questions that you might like to answer:

* How would the output look like?
* What is the purpose of this output? In other words, in what situations should users refer to it?

I'm closing until this issue is more actionable.
