### ISSUE TITLE
`dune subst` looks only at annotated tags

### ISSUE THREAD

**Issue by nojb** [ocaml/dune#6391]
I noticed recently that `dune subst` only takes into account _annotated tags_. This behaviour comes from `git describe` which by default only looks at such tags. But it can be made to look also at lightweight tags by passing the `--tags` flag.

Is there a reason not to pass `--tags` to `git describe` for `dune subst` purposes?

**Comment by emillon** [comment]
It came up before. Several tools, in particular `dune-release` settled on using annotated tags. These kinds of tags are recommended for releases (cf. [git-tag](https://git-scm.com/docs/git-tag) manpage) because they can have metadata associated to the tag itself, like specific author info, a signature, or a message (dune-release will attach the changelog, so `git show $tag` will display it).

In contrast, lightweight tags are generally considered to be more local and temporary. We want version numbers to be reproducible so it's best if they only consider the "shared" set of tags.

To the more general question "my team uses lightweight tags, can dune use that", my first answer would be to first recommending switching to annotated tags if possible. If that's not possible, I suppose that we could extend `(subst)` in `dune-project` to support an option to pass `--tags`.

**Comment by nojb** [comment]
Fair enough. Closing, as there is no pressing need for this.
