### ISSUE TITLE
Dune doesn't install dependencies when building pure Coq library

### ISSUE THREAD

**Issue by SmnTin** [ocaml/dune#6531]
## Expected Behavior

Suppose we create the following project structure:
```
├── dune-project
└── src
    ├── dune
    └── Some.v
```
With the following file contents:
- `dune-project`:
  ```
  (lang dune 2.9)
  (using coq 0.3)
  (name my-coq)
  
  (package
   (name my-coq)
   (depends
    coq
    ))
  ```
- `src/dune`:
  ```
  (coq.theory
   (name MyTheory)
   (package my-coq))
  ```
Then we create a new local opam switch, install `dune` and run `dune build`. We expect `dune` to firstly install and compile all the dependencies and only then compile the Coq theory because the theory declares to belong to the package that has the dependencies.

## Actual Behavior

In reality, `dune build` fails:
```console
$ dune build
File "src/dune", line 1, characters 0-49:
1 | (coq.theory
2 |  (name MyTheory)
3 |  (package my-coq))
Error: Program coqdep not found in the tree or in PATH
 (context: default)
Hint: opam install coq
```
Even if we installed Coq manually but added some other dependencies (for example, libraries or frameworks that are available as regular `opam` packages), the dependencies wouldn't be handled properly and build would still fail.

## Possible workaround

We can enable generation of regular `opam`-files in `dune-project`:
```
(generate_opam_files true)
```
So we can just run `opam install . --deps-only` before `dune build` and the build will succeed. However, this draws `dune` as a mere `opam`-files generator which is not particularly useful.

**Comment by Alizter** [comment]
Is this really the expected behaviour? Dune is not a package manager and has no business installing opam packages. Sure there are some features such as projects allowing for the generation of opam files but this is not what Dune is meant for. What Dune can do, and perhaps this is where the confusion comes from, is build and use Coq if it appears in the same workspace. i.e. make a dune-project and plop both Coq and your project sources in this project, then Dune will know to build Coq in order to build the theory. You should not need to specify anything about package dependencies.

**Comment by SmnTin** [comment]
Dune doesn't have to install the depedencies. It would be nice if it at least checked that they are present.

**Comment by Alizter** [comment]
@SmnTin It does check if they are present? It even suggests how to fix the situation:
```
Error: Program coqdep not found in the tree or in PATH
 (context: default)
Hint: opam install coq
```

**Comment by Alizter** [comment]
I'm closing this issue for the moment until you can clarify the behavior you are requesting.
