### ISSUE TITLE
The dune-lang stanza does not override the version condition on Dune

### ISSUE THREAD

**Issue by Halbaroth** [ocaml/dune#6597]
## Expected Behavior
The following `dune-project` file :
```
(lang dune 3.0)

(name bug_dune)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name")

(maintainers "Maintainer Name")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name bug_dune)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml (dune (>= 3.0)))
 (tags
  (topics "to describe" your project)))
```
should generate the below dependencies in the opam file:
```
depends: [
  "ocaml"
  "dune" {>= "3.0"}
  "odoc" {with-doc}
]
```

## Actual Behavior
Dune generates these dependencies:
```
depends: [
  "ocaml"
  "dune" {>= "3.0" & >= "3.0"}
  "odoc" {with-doc}
]
```

## Reproduction

1. Create a new project and use the above dune-project file.

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.0
- Version of `ocaml` (output of `ocamlc --version`) 4.14.0
- Operating system (distribution and version): Archlinux

**Comment by emillon** [comment]
I agree that the interaction you're having is not great, but FYI, you don't have to specify the dune dependency at all. Dune will insert it with the right lower bound by itself. That will solve your issue.

Now, as to how we can be better. The current logic (`Opam_create.insert_dune_dep`) is to add the specified bound as a conjunction. That is but `"dune" >= dune-lang & (constraint in dune-project)`.

We could try to detect when the constraint is duplicated, and either simplify the resulting constraint or warn that it's unnecessary. That's probably better because we can be more lax in how we version warnings compared to how we generate opam files.

**Comment by Halbaroth** [comment]
I totally agree that printing a warning is a better design.

**Comment by sim642** [comment]
I guess this duplicates #3916.
