### ISSUE TITLE
Expand variables in install stanzas

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#690]
Currently `${variables}` aren't expanded in install stanzas as they should be [1].

cc @dilm @wokalski

[1] https://discuss.ocaml.org/t/dune-object-file-output-is-not-using-output-complete-obj/1828/6?u=rgrinberg

**Comment by rgrinberg** [comment]
Thanks for taking intitative @Isweet .

Have a look at jbuild.ml. In particular, you're looking for uses of `String_with_vars.t` uses in the various `t` values which represent sexp parsers. This will you insert variables in the necessary fields.

Then, you'll be to eliminate `String_with_vars.t` values using `String_with_vars.expand` with a correct `~f` function. Here you can refer to the `expand_*` family of functions in super_context.ml

Finally, keep in mind that we cannot support all variables in the installed stanza. For example, `%{read:...}` cannot be supported at the moment, because we're keeping the list of installed artifacts static, and hence cannot build anything before we know the full set of static artifacts.

Feel free to ask more questions.

**Comment by Isweet** [comment]
I was able to figure out the parsing yesterday. I'll open a WIP PR sometime today.

I started looking at the expand functions in `super_context.ml` to get an idea of how to use `expand` in `string_with_vars.ml`.

Thanks for the direction, I'll follow-up if I get stuck.

**Comment by rauanmayemir** [comment]
Has anything changed here recently?

I can compile an executable in `(exe)` linking mode and run it as a standalone program, but I can't link `app.exe.o` built in `(object)` mode with my XCode project because it has its own `libasmrun.a` dependency. (i.e I start having 'duplicate symbol' issues)

I can't remove `libasmrun.a` dependency in my xcode project because I'm running `caml_main` in its `main` function.

I didn't have such issues before, so I'm wondering if something changed in `-output-complete-obj`.

My `jbuild` file:

```
(jbuild_version 1)

(executable (
 (name app)
 (libraries (brisk_cocoa))
 (modes (object))
))

(install (
  (package brisk)
  (section lib)
  (files ((app.exe.o as app.o)))
))
```

And then I run `jbuilder build @install`.

**Comment by diml** [comment]
@rauanmayemir could you open a separate issue?

**Comment by rauanmayemir** [comment]
@diml I created a discuss thread [here](https://discuss.ocaml.org/t/cant-link-complete-object-file-in-a-c-program/2337), should I open a gh issue as well?

**Comment by diml** [comment]
Yes, please. It's easier to track issues at a central place. I believe all dune devs are on discuss, but for instance I personally don't consult discuss on a daily basis.

**Comment by rgrinberg** [comment]
Fixed by @mseri
