### ISSUE TITLE
`dune exec --workspace` results in 'Context "default" not found!'

### ISSUE THREAD

**Issue by maroneze** [ocaml/dune#7124]
## Expected Behavior

`dune exec --workspace <file>` should execute the command using the specified workspace.

## Actual Behavior

`Error: Context "default" not found!`

## Reproduction

```
dune init project proj
cd proj
echo "(lang dune 3.2)
(context
 (default
  (name bench)
  (profile bench)
  (instrument_with landmarks))
)" > dune-workspace.bench
dune build --workspace dune-workspace.bench # works flawlessly
dune exec --workspace dune-workspace.bench -- ls # same result with any command, in fact
```

## Specifications

- Version of `dune` (output of `dune --version`): 3.6.2
- Version of `ocaml` (output of `ocamlc --version`): 4.14.1
- Operating system (distribution and version): Fedora 36

## Additional information 

I tried adding an empty `dune-workspace` file (to provide a "default" workspace, as mentioned in the doc), but it does not change anything.

I looked for some clues in [the Dune documentation about dune-workspace](https://dune.readthedocs.io/en/stable/dune-files.html#dune-workspace) but I couldn't find anything. I wonder if the `dune-workspace.bench` file is incorrect, but the fact that it works when I run `dune build` and `dune install` (and it does install the instrumented version) make me think it should work for `dune exec` as well.

**Comment by emillon** [comment]
I think that what's happening is that because you're not using `--context`, `dune exec` uses the context named `default`. Your workspace does not have a context named like this - the only context in there is named `bench`.

The `(default ...)` constructor has unfortunately a different meaning, it means "look for tools in `$PATH`".

In your case, you can either:
- pass `--context bench` in addition to `--workspace dune-workspace.bench`
- rename the context to `default`. then just passing `--workspace` should work
- if you're in a situation where you have a `dune-workspace` file, you can a define a `(default)` context named `default` and an instrumented one named `bench` and you'll be able to switch between instrumented and non instrumented with just `--context bench`

**Comment by maroneze** [comment]
Thanks for the explanation! Indeed I missed the distinction between the workspace and the context (and because `--context` does not exist for `dune build`, I didn't think much about it).

By the way, since `--context` does not exist for `dune build`, I wonder how it would work with a single `dune-workspace` file. Would `dune build` compile both contexts every time? I believe that's what I had initially tried, but it was doubling the overall compilation time, so my colleague tried the `dune-workspace.bench` approach to avoid unnecessarily compiling it. Or am I mixing things up?

**Comment by emillon** [comment]
You're right: when using a workspace that has several contexts, `dune build` will build for all contexts (it's possible to use `dune build _build/contextname/...` but that's not great). So you're right that would build all variants everytime, so that's probably not a good idea.

**Comment by maroneze** [comment]
Ok, thank you very much. For now we will keep using the `--workspace` (and `--context`, for `dune exec`) to avoid that. It does help understand why both exist.
