### ISSUE TITLE
Bad interaction between _odoc_supports directory and github pages / jekyll

### ISSUE THREAD

**Issue by hhugo** [ocaml/dune#7364]
On http://ocsigen.org/js_of_ocaml/5.1.0/api/index.html, odoc.css is not found. Yet, it is available in https://github.com/ocsigen/js_of_ocaml/blob/gh-pages/5.1.0/api/_odoc_support/odoc.css.

After searching more, it could be an issue with github pages and directories with leading underscores.
- https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
- https://github.com/mpetrovich/stylemark/issues/65

_Originally posted by @hhugo in https://github.com/ocaml/dune/issues/6913#issuecomment-1476655932_

**Comment by yawaramin** [comment]
Any reason the `_odoc_support` directory can't be called something like one of the popular names for these kinds of directories, e.g. `static`, `assets`, or similar?

**Comment by Alizter** [comment]
Suggesting .nojekyll is a workaround but I don't think it is satisfactory. Would a better solution be to rename the directory to something without underscores?

**Comment by emillon** [comment]
Yes, good call on fixing that for 3.8. Renaming the `_odoc` directory sounds good to me.

**Comment by dbuenzli** [comment]
> Any reason the `_odoc_support` directory can't be called something like one of the popular names for these kinds of directories, e.g. `static`, `assets`, or similar?

Because if your are developing a webapp you are extremely likely to have a module that is named that way. `_odoc_support` is out of the module and `.mld` page namespace.

**Comment by emillon** [comment]
I'd like to have a solution that works out of the box for github-pages users.

We have several options here:

1. change the directory name to something that does not start with `_`
2. generate an empty `.nojekyll` file
3. make the directory name configurable

1 is best but as @dbuenzli explained we want to find something that can not collide with generated links. What kind of links can odoc generate? Can we move this one folder up maybe? Would starting with a dot work?

I'm not found of 2 since it's unnecessary for many users. Technically dune has access to whether the user uses github for hosting (through `(source)` and `doc`) but it seems too clever.

I'd like to avoid 3 since it's going to be too difficult to discover: a user that discovers the issue is the name of the support folder can just create a `.nojekyll` file instead.
