### ISSUE TITLE
Out of memory with symlinks

### ISSUE THREAD

**Issue by AltGr** [ocaml/dune#764]
While trying to reproduce my stack overflow issue, stumbled upon this one:
```
$ mkdir foo && cd foo
$ ln -s . x
$ ln -s . y
$ jbuilder build
Fatal error: out of memory.
```
the OOM happening after a while; couldn't find a simple repro case for the stack overflow, which happened with a combination of many files and symlinks, but they seem related.

**Comment by rgrinberg** [comment]
I suppose the issue is that jbuilder will keep iterating `x/y/x/x..` until it will eventually run out of memory.

@diml I guess we can we can fix this by maintainig the cache of `readlink path -> walk path` so that we don't scan anything twice. But isn't that just populating the `dirs` field eagerly? You've put some effort to make sure only the paths that are accessed enter this table. This would ruin that effort.

**Comment by diml** [comment]
I suppose we can start by adding a counter to avoid crashing with out-of-memory.

To detect loop properly we can proceed as follow: in the `walk` function in `File_tree.load`, we can maintain a `real_path` variable that is like `path` but will follow symlinks, as well as a `seen_real_paths` stack of seen paths. That will allow to properly detect and report loops.
