### ISSUE TITLE
dune doesn't build on NetBSD 8.0_RC1

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#773]
But probably not due to dune itself.
nohup.out from 'nohup make release' after a fresh git clone is there:
https://gist.github.com/UnixJunkie/2c10474aa6bdb966f1bcbe5455133c2c

Bottom line:
ocamlopt src/usexp/.usexp.objs/usexp__Table.{cmx,o} (got signal SEGV)

**Comment by UnixJunkie** [comment]
it does compile on freebsd-11.1 though

**Comment by UnixJunkie** [comment]
also ok on openbsd-6.3 with a higher than default ulimit -s

**Comment by UnixJunkie** [comment]
in fact, it also compiles on netbsd if I increase the maximum stack size (ulimit -s 60000). Sorry for the noise.

**Comment by diml** [comment]
No problem. This is the same issue as https://github.com/janestreet/parsexp/issues/1. It is a bit unfortunate that it doesn't build with the default settings. There are other way to implement this file, for instance we could use a big pattern matching instead of an array. We can try that to see if it makes things better.

**Comment by UnixJunkie** [comment]
I would have solved my problem much faster if the error was 'stack overflow'. But seeing a segmentation fault is misleading (I never see those in OCaml!). openbsd says stack overflow for the same problem, hence I had an idea of what to try.
