### ISSUE TITLE
Dune RPC for Visualizing Running Builds

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#7903]
## Problem

It would be nice to get an idea of what dune is doing in a way that can be displayed to the user in the text editor.

## Proposal

My previous idea was to rely on tui to do something like that, but we could also introduce an RPC based API to accomplish the same thing. In particular, we could have RPC calls to visualize dune's internal "job queue" in real time. This job queue would contain the running jobs + a backlog of the jobs waiting to run.

## Implementation

The RPC calls would be quite similar to how we handle progress notification (long polling). Essentially, we'll be syncing the state of this job queue from the server to the client and using diffs/long polling to minimize traffic.

The client would subscribe to job queue updates with:

```ocaml
val jobs : max_backlog:int -> Jobs.t Sub.t (* max_backlog is to make sure the client doesn't get more than what can reasonably be visualized *)
```

The set of jobs would like:
```ocaml
module Job = struct
  type t =  { targets : path list }
end
module Jobs = struct
  type t =
    { running : (Job.t * start_time) list
    ; backlog : Job.t list
    }
end
```

**Comment by snowleopard** [comment]
Some thoughts:
* Some actions declare a crazy number of targets. I think it's probably fine to report just the first target, which is often used to identify the action. Otherwise, you may end up transferring too much stuff and also overwhelming the user with it.
* At first, I'd start just with `running`. As we discussed, it's unclear for now whether `backlog` is going to be useful.
* I don't get what `start_time list` is. Why not just `start_time`?
