### ISSUE TITLE
Treat lockdirs as data-only

### ISSUE THREAD

**Issue by gridbugs** [ocaml/dune#7974]
## Desired Behavior

A dune lockdir contains dependency data in per-package files named after the packages themselves. This creates a problem where if the package "dune" is among the dependencies, its data will be stored in a file named "dune" which leads to dune attempting to interpret the file as a regular dune file.

To solve this we will treat lockdirs as data-only directories which will prevent dune from attempting to parse dune files inside lockdirs. This means that when determining whether a directory is "data-only" dune needs to know which directories are lockdirs. Currently custom lockdirs can be specified in a `dune-workspace` file and they can have any name. This could lead to the following scenario:
1. a user generates a lockdir for their project which depends on the package "dune"
2. they change the name of the default lockdir in `dune-workspace` without deleting the original lockdir
3. `dune build` attempts to interpret the package data in "dune.lock/dune" as a dune file and gives an error like:

```
File "dune.lock/dune", line 1, characters 1-8:
1 | (version 3.7.1)
     ^^^^^^^
Error: Unknown constructor version
```
...which is confusing.

One way of preventing this scenario is to enforce a naming convention for lockdirs: all directories whose names end in ".lock" will be treated as data-only directories, and only direcotries whose names end in ".lock" can be configured as lockdirs.

**Comment by Leonidas-from-XIV** [comment]
I am a little bit averse to "magic" directories, because it might lead to some people having directories named `foo.lock` that suddenly get special treatment by accident (e.g. a lock datastructure subpackage for library `foo`). What I would suggest instead is to create a `dune` file in the folder that declares the folder as data-only.

This of course leads to a conflict with locking dune. In opam-monorepo we deal with this by renaming `dune` to `dune_`, maybe that's an option.

Alternatively, we could programmatically add such a definition on the folder containing the `.lock` directory, but I don't think there is a programmatic way to add stanzas to peoples' rules since they might be autogenerated or from an `.ml` file etc.

**Comment by rgrinberg** [comment]
>  I do understand the value of convention over configuration, but in dune we usually tend towards the "explicit is better than implicit" side of the scale.

I think we tended to go the other way actually. Although I don't think this is a rule that can be consistently applied anyway.

Looking back, I do quite like my initial low tech suggestion of using file extensions. What's the problem of appending `.pkg` to every package definition file? Yeah, it's a little ugly but these things are generated anyway.

**Comment by Alizter** [comment]
@gridbugs is this completed or rather not planned?

**Comment by gridbugs** [comment]
It's not planned. We did https://github.com/ocaml/dune/pull/8014 instead, adding a file extension to lockfiles.
