### ISSUE TITLE
opam-file-generation: example opam file uses wrong field name "maintainers"

### ISSUE THREAD

**Issue by arbipher** [ocaml/dune#8273]
`opam` reports warning on `error 23: Missing field 'maintainer'` in the opam file, while `dune` (dune-project file syntax [highlight](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/syntaxes/dune-project.json#L268C17-L268C17) in vscode-ocaml-platform) seems to use maintainer**s**.

I wonder if there is an agreement inside the OCaml community and keep consistency. (Please forgive if I should not make the issue here)

**Comment by kit-ty-kate** [comment]
That looks to me like a bug in dune (the documentation is also wrong: https://dune.readthedocs.io/en/stable/howto/opam-file-generation.html)

**Comment by emillon** [comment]
It's a doc issue. dune correctly generates `maintainer:` in the opam file.

As for the fact that dune uses `(maintainers)`: this field supports a list of strings. We discussed adding a singular form at some point in the past, but it was decided not to do it in order to have a single way to express this.

**Comment by kit-ty-kate** [comment]
as far as i understand there is also an issue in https://github.com/ocamllabs/vscode-ocaml-platform. Can someone open an issue there?
