### ISSUE TITLE
we can have exe that do not install, but not modules that do not install

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/dune#906]
Sometimes, I'd like to have a module that is used internally but
that is not visible outside.
Currently, we can do this for exe (those which do not have a public name).
It kind of annoys me that we cannot do the same thing for modules.
I think the current way is to hide those modules via an interface file, but this is inconvenient.

For example, the utls module in there:
https://github.com/UnixJunkie/dokeysto/blob/master/src/jbuild

I'd like that all modules of the library can tap into Utls, but that it does not become visible outside.
So, when the library is installed, this module should not ship/become visible.

jbuilder forces me to declare and list this module in the modules section of the library.
Forces me as in "tores my arm into doing it".
And, of course, I don't like when my arm is being torned.

Is it possible to hide this module just via the jbuild file (in some simple way)
or is this a possible missing feature?

I think that with obuild, I could do this. The module was used at compile time but
was not shipping with the library.

**Comment by diml** [comment]
Jbuilder doesn't force you to do anything. There are good reasons why things are the way they are.

Independently of whether a module might be private or public, if you have several libraries in the same directory, then you need to add `modules` fields to the various libraries so that Dune knows how to attach modules to libraries. Otherwise how would Dune know which library Utls should be part of? If the various libraries use different preprocessors, how should Utls be preprocessed?

>I think that with obuild, I could do this. The module was used at compile time but was not shipping with the library.

I don't believe that's true. If you use the Utls module in your library, then it has to be shipped, otherwise what would happen when you link an executable using your library?

I believe that what obuild was doing, which is what some projects sometimes do is not ship the cmi file. This prevents users of your library to use it, and as long as you don't use `(wrapped false)` this also allow them to define their own `Utls` module. We are planning to support this via a `(private_modules ...)` field, but it's not done yet.

**Comment by UnixJunkie** [comment]
Fair enough.
I am not an expert of build systems, so I don't know exactly how obuild was doing its magic.
@jeromemaloberti might know.
I see that the private_modules is tracked somewhere else
https://github.com/ocaml/dune/issues/427
Perfect and thanks!
