### ISSUE TITLE
Support excluding some targets from being built

### ISSUE THREAD

**Issue by hcarty** [ocaml/dune#917]
As an example, say I am working on an application using cohttp.  I can copy/symlink cohttp's source tree into my project.  However, if I'm only using the Lwt support from cohttp I may not have Async installed.  `jbuilder build` will spit out errors saying that it can't build cohttp-async because of the missing dependency.

It would be nice to have a way to exclude certain libraries and executables from a build to avoid this issue.

**Comment by diml** [comment]
It is because the default target is `@install` which includes all packages in the workspace. You can request an individual package by running:

```
$ jbuilder build <package>.install
```

Is that enough for your use case?

**Comment by hcarty** [comment]
@diml That works, thank you!  At least for this case where there is a temporarily linked/included package.

In a situation where there is something more permanent, like cohttp directly in the project as a git submodule or similarly inlined/vendored, I'm guessing I could define a custom `@myproject`-like target to explicitly include the targets I want to build.  Is that the recommended approach?

Closing as the original issue has been addressed.  Thank you again @diml.

**Comment by diml** [comment]
Yes. I have been thinking of adding a special `default` alias that would be defined recursively as follow:

- if the directory contains an explicit definition of `(alias default)`, use it
- otherwise define it as `(alias install)` in this directory + `(alias_in_subdirs default)`

where `(alias_in_subdirs XXX)` correspond to alias `XXX` in all direct sub-directories of the current directory. Then `dune build` would mean `dune build @default` rather than `dune build @install`.

**Comment by rgrinberg** [comment]
I'm for that change as well.

**Comment by diml** [comment]
I implemented something like that in #926. In the end I didn't use `alias_in_subdirs` as it didn't seem very good in practice.

**Comment by hcarty** [comment]
Thank you @diml!
