### ISSUE TITLE
better error message when opam repo lock is around

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9258]
When a user kills dune during the download of an opam repo, the lock file gets left over. If they run dune again the lock will cause a code error to be raised. In this case, rather than raising a code error we should have a user_error telling the user to delete their git-repo cache directory and try again.

cc @Leonidas-from-XIV

**Comment by Leonidas-from-XIV** [comment]
> If they run dune again the lock will cause a code error to be raised.

Does it? I took a look at the code and I don't think this is the case. The existence of a lock file does not imply a lock is actually held, so it is perfectly safe to `Unix.openfile` the lock file even if it exists. The flags it uses are `O_CREAT` (to create if it doesn't exist), `O_WRONLY` (since we only write our PID into the file), `O_SHARE_DELETE` (to allow deletion of the open file on Windows, mirroring Unix defaults) and `O_CLOEXEC` (to close the file on `exec` so subprocesses don't inherit the lock).
