### ISSUE TITLE
Improve the Hacking Manual

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#935]
The current hacking document is a good start, but I'm getting the sense that I'm repeating the same stuff over and over. We should extend the document to cover the following topics:

* Using and extending the test suite

* Defining and modifying stanzas

* Understanding the versioning scheme and how to make backwards compatible changes

* The build arrow

* Fibers

* Ordered set language

Also, this is up for voting, but I think it would be nice to change hacking to org mode. It would make it much simpler to cross link with the source code and org has some really nice organization tools when you're putting everything into one file.

**Comment by diml** [comment]
The only issue with org mode is that it is less widespread, so it is harder for contributors.

**Comment by shonfeder** [comment]
An additional item to clarify: how to run a single cram tests. I just had to search to slack to find @rgrinberg's helpful pointer that an alias is generated for each test suite. So a suite `foot` located at `test-cases/foo.t` can be run via `dune build @foo`.

Since this issue was opened, documentation has found its way into the `hacking.rst` file in the docs. Just had a quick exchange on  slack in which @jeremiedimino suggested we should move the stuff from the `HACKING.md` into the `.rst` file.

**Comment by rgrinberg** [comment]
@Alizter since you've been exploring the codebase recently, your suggestions would be welcome.

**Comment by Alizter** [comment]
Something I've just noticed, there are two hacking documents?

**Comment by rgrinberg** [comment]
That's a good point. hacking.md is out of date and you should refer only to the rst document

Rudi.

**Comment by rgrinberg** [comment]
Closing as we've written quite a bit here already. Thanks @Alizter for helping us polish it recently.
