### ISSUE TITLE
pkg: remove --skip-update

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9354]
After thinking about it some more, it might have been a mistake to add `--skip-update` at this point in time. Since we didn't have a user mandate for it, we could remove it to simplify our pkg implementation and make it easier to work with. In the future, if there turns out to be such a demand, we can always design something.

It should also be noted that the same behaviour is already possible using dune-workspace files.

**Comment by Leonidas-from-XIV** [comment]
> It should also be noted that the same behaviour is already possible using dune-workspace files.

What do you mean? The only way you can get the locking to work offline is to pass local repos/file paths to it.

**Comment by Alizter** [comment]
Wouldn't having an extra workspace file with the repository hash set work?

**Comment by Leonidas-from-XIV** [comment]
If you have one workspace file which specifies the hash (and thus does not trigger an update) and one that doesn't then you can do this:

Assume there is `dune-workspace.head` and `dune-workspace.rev` where the former just specifies the repo with a branch, e.g. the default branch and the latter uses a specific commit id. If the user runs `dune --workspace dune-workspace.rev pkg lock` it can fail, because the revision is not yet in the rev store. Then you'd need to run `dune --workspace dune-workspace.head pkg lock` to update the rev store (while throwing away the lockdir as you're not interested in the solution, just the sideeffect of the update) and only then you can run `dune --workspace dune-workspace.rev pkg lock` successfully because now the rev store has been updated and contains the revision.

So in that configuration you'd probably want `dune --workspace dune-workspace.rev pkg lock --force-update` to make the experience less convoluted, which basically is just a the negation of `--skip-update`.

Or alternatively we can check whether the revision is in the rev store and if not update the rev store automatically. What I don't like about this is that whether `dune pkg lock` works offline or not depends on whether the rev store has the revision cached and not on the contents of the workspace file.

**Comment by rgrinberg** [comment]
> The only way you can get the locking to work offline is to pass local repos/file paths to it.

That would mean we have a bug somewhere. There's no need to do any network access when whatever the user writes resolves to a git object. How do we know something is a git object? When `$obj` is a prefix of `git rev-parse  --revs-only $obj`.

**Comment by Leonidas-from-XIV** [comment]
I should've said "the only way you'd get offline mode when removing that option". I think we agreed that if `$obj` is a revision, and we can't find it in the repo we do an (online) update.
