### ISSUE TITLE
Revision Store for All Git Sources

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#9394]
Currently, we run individual `git clone` commands for every single repository we need to clone when building packages with dune.

This is inefficient because we end up redownloading the same things over and over. We already have the revision storage for opam repositories to fix this problem, and this ticket is a suggestion that we reuse it for package building as well.

The one possible issue that might arise with this is that the git binary might not allow us to setup a remote and then call `git fetch` concurrently in the same repository. Setting up a remote can be done in serial since it's very fast, but the fetch operation must always be done concurrently.

**Comment by Alizter** [comment]
When do we clone sources with git? I'm looking at the opam files in the opam repository and it seems having a tarball on GitHub is the most common kind of source:
```
https://github.com/ocaml/Zarith/archive/release-1.13.tar.gz
```
Is this issue suggesting we detect GitHub urls and use git clone / revision stores for them instead?

**Comment by Leonidas-from-XIV** [comment]
No, it's more for when we're fetching dev-versions, equivalent to pinning a dev-repo.

Detecting sources hosted on git is a fool's errand, because not all of them mirror the release tarballs and pretending to have version 1.13 installed when instead of using the author supplied tarball (and checksums) we pull the git source is misleading and in rare case even wrong

One of these cases is Menhir, where sources and the tarball don't match since the tarball has the manual pregenerated; but it is hosted on GitLib in either case.
