### ISSUE TITLE
pkg: how to build packages with ./configure script

### ISSUE THREAD

**Issue by Alizter** [ocaml/dune#9429]
In opam-repository there are around 2000 build lines that call `./configure` with a `--prefix` argument. These generally have the same issue that we cannot pass relative paths to autoconf configure scripts. Examples include:
- `ocamlfind`
- `ocaml`
- and many more

A common issue with building these packages with `dune pkg` is that we have to sandbox our build enviornments which means we cannot pass absolute paths to configure. However, autoconf only allows absolute paths which causes some friction.

We could just essentially blacklist these packages apart from a core few, but since it is reoccurring it might be worth looking for a general solution.

There are some solutions to this problem, and this issue intends to explore our options:

1. Patch every package that we want to build and add an overlay.
  + Pros:
    + We will know that certain packages are guaranteed to build.
  + Cons:
    + Huge maintenance burden.
    + Each overlay has to be written by hand, and likely wil l cause many users to request them.

2. Use the intended install location absolute paths when we detect a `./configure` script and use the `DESTDIR` env var during the install step to swap that out for the sandboxed path. Afterwards we should be able to copy the installed artefacts back.
  + Pros:
    + Might allow most configure scripts to work out of the box.
  + Cons:
    + Not sure if it even works, we would need to try out a prototype.
    + Detecting configure scripts might not be so straight forward.
    + There may be some custom configure scripts that don't allow us to use this solution.

3. Build packages directly at the install location, in a special sandbox mode.
  + Pros:
    + We won't have to relocate the installed artifacts after they are built meaning we can pass absolute paths to configure.
    + Similar to how nix builds configure scripts, since they are built and installed directly in the nix store.
  + Cons:
    + Built artefacts won't likely be shareable between projects.
    + Maintenance burden on the sandbox mechanism.

**Comment by rgrinberg** [comment]
First, the problem this proposal attempts to address seems to be mischaracterized or described in an incomplete fashion. You've motivated the problem using relative vs absolute paths but omitted the much bigger issue of relocation. It's quite easy to make the paths absolute as I've demonstrated in this PR https://github.com/ocaml/dune/pull/8862. The problem is that it buys us very little because it does not address the issue with relocation.

The issue with relocation is indeed important to solve. Without it, we cannot leverage the dune cache and sandboxing which defeats the whole point of using dune to build a package. This must be adequately solved if dune's package management were to gain adoption. So let me address the various options you've proposed.

You are greatly exaggerating the maintenance burden with overlays. It doesn't matter how many packages exist in opam if the users only care about building the latest version of 1 or 2 of them. In our case, it's more than sufficient to have a few versions of OCaml and a single version of ocamlfind working with dune until the issue of relocation is solved upstream. So there will be little maintenance to do and it will only be done for a temporary period. Given that users will have very little interest in using dune without relocation (remember that it breaks the dune cache), I imagine that important packages will be updated shortly to accommodate us.

The 2nd solution you've proposed allows us to defeat sandboxing, but the actions themselves are still not relocatable. So users will still need to recompile everything for every single project. All the recompilation will make them quickly lose interest in using dune for package management. The other disadvantages that you've listed are all valid as well. Summing up all of them, this solution is basically a "hack". Most good hacks are usually useful in the short term, this one unfortunately is not. It still doesn't allow us to use the cache. A far simpler version of this hack would be to just disable sandboxing. In short, this doesn't sound very convincing.

Your 3rd solution lacks a proper description, so I found it hard to understand. From what I can tell, it's quite similar to https://github.com/ocaml/dune/issues/7502. I would suggest that you would expand your idea in that ticket and describe how your "special sandbox mode" differs from shared sandboxes.
