### ISSUE TITLE
add ellipses for non deterministic cram tests

### ISSUE THREAD

**Issue by zapashcanon** [ocaml/dune#9812]
Hi,

Could it be possible to add something similar to *ellipses* in mdx ?

That is:

```cram
test:
  $ foo
  1
  2
  ...
  3
```

Would match any output where `...` has been replaced by zero, one or more lines.

This is really useful when a part of the output is non deterministic but you still want to check the rest. For instance in Owi, I really would like to be able to replace:

```cram
i32 binop test:
  $ owi sym binop_i32.wat
  Trap: unreachable                                          
  Model:                                                     
    (model                                                   
      (symbol_0 (i32 -2147483618))                           
      (symbol_1 (i32 0))                                     
      (symbol_2 (i32 0))                                     
      (symbol_3 (i32 -2147483648)))     
```

By:

```cram
i32 binop test:
  $ owi sym binop_i32.wat
  Trap: unreachable                                          
  Model:                                                     
    (model                                                   
  ... 
```

Because all those values are depending on both an SMT solver and a multi-core execution which are both non deterministic.

Supporting ellipses could be made a field in the `cram` stanza to avoid surprising people who have actual ellipses in their output.

Thanks.

**Comment by emillon** [comment]
Hi,

We have decided against implementing ellipses or matchers in cram because it does not work with promotion. You can read more in #3858.

The recommended pattern is to postprocess your command.
For example, in your case, print everything up to the "model" line by piping into `awk '/model/{exit} {print}'`.

Thanks

**Comment by zapashcanon** [comment]
I understand promotion could be an issue in these cases.

I still believe it would be nice to support something like this directly and disable it by default (requiring a field in the cram stanza to enable it) but I'm fine with post-processing.

Thanks for the quick answer. :)

**Comment by emillon** [comment]
I have an alternative that I think can interest you.

You can create a program that:
- reads a pattern from a file
- reads a command output from its stdin
- if the input matches the pattern, it exits with 0
- otherwise, it whatever is relevant to you (input, output and pattern, or some more smart matching if you prefer)

That way, you can use this in a cram test. It will not work well with promotion when there's an error message, the user needs a manual step to update the pattern. But you can use any pattern you like, including ones that are specific to your application.

If you're interested, this can also become a general-purpose ellipsis-matcher tool intended to be used with dune.

Does that make sense?
