### ISSUE TITLE
Uniform Caching API in Dune_pkg

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/dune#9952]
We currently have four caches in dune_pkg:

1. candidates cache in the solver
2. availability cache in the solver
3. mount cache in the pin handling
4. download cache in single_run_file_cache

They all have slight differences, but could probably use the same caching API. In particular, they should all create ivars before they do no any work (caches 1. and 2. don't do that).

@gridbugs could you take a look at this one?

**Comment by gridbugs** [comment]
Taking a look at the different caches we have in package management and I'm not convinced it's worth it to unify them with a single api. Possibly it makes sense to unify the two caches used in the solver since they are both just maps (well a map and a table). But `single_run_file_cache` serves a very different purpose than the caches used in the solver - it doesn't cache ocaml values but rather files on disk created as a side effect of calling a function and expects users to open the files and read the contents themselves. I don't see a sensible through line between `single_run_file_cache` and the solver caches.

Also I'm not sure what you mean by the "mount cache in the pin handling". Are you referring to how all the functions in `mount.ml` create a fiber node before doing any work so that the result of the computation is cached in the ivar? This is different to the other types of cache mentioned since it's not associating keys with cache entries.

**Comment by rgrinberg** [comment]
You can start with unifying 1 and 2 as a first step.

> Also I'm not sure what you mean by the "mount cache in the pin handling". Are you referring to how all the functions in mount.ml create a fiber node before doing any work so that the result of the computation is cached in the ivar? This is different to the other types of cache mentioned since it's not associating keys with cache entries.

I mean the code that populates the cache stored in this type:

```
  type state =
    { mutable traversed :
        (DB.t * Dune_lang.Package.t Package_name.Map.t) option Fiber.Ivar.t OpamUrl.Map.t
    }
```

**Comment by gridbugs** [comment]
Even between 1 and 2 it's not clear what common logic could be moved to a common api. 1 is updated asynchronously with a fiber so its cache would need fiber's threaded through it (e.g. `val find_or_add : cache -> 'key -> f:(unit -> 'value Fiber.t) -> 'value Fiber.t)`). But 2 is updated synchronously and it doesn't seem worth it to thread fibers through the logic for checking if a package is available just to share a caching api.

I've thought about adding a cache that supports both synchronous and async updates but decided against it. A proper async cache will guarantee that each computation only happens once, even if a second request for the same key comes in while the computation from the first request for said key is still running (something we don't currently do with the candidates cache). This would involve storing ivars in the cache which would complicate accessing it synchronously.

For the synchronous cache I think we should just refactor the `mutable` map to use `Stdune.Table.find_or_add` instead.

I'll still implement the async cache even though we'd only be using it once so that we get the benefit I mentioned earlier. `single_run_file_cache` works in a similar way so maybe there will be a common mechanism I can factor out.

**Comment by rgrinberg** [comment]
I see. In that case, the candidates cache should still shuffle the ivars like 3 and 4 do.
